Repository namada-net/namada, pull requests merged in 2023-09, with the labels that each got.

#1778 Fix wasm pointer misalignment issues on Apple silicon
  .changelog/unreleased/bug-fixes/1778-fix-wasm-vm-aarch64-mac.md
  Cargo.lock
  shared/Cargo.toml
  shared/src/vm/wasm/run.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: bug, wasm, ready for draft

#1784 Fix IBC amount handling
  .changelog/unreleased/bug-fixes/1744-fix-ibc-amount.md
  Cargo.lock
  Cargo.toml
  apps/src/lib/cli.rs
  core/Cargo.toml
  core/src/ledger/ibc/context/common.rs
  core/src/ledger/ibc/context/storage.rs
  core/src/ledger/ibc/context/transfer_mod.rs
  core/src/ledger/ibc/mod.rs
  core/src/ledger/ibc/storage.rs
  core/src/ledger/tx_env.rs
  core/src/types/token.rs
  shared/src/ledger/args.rs
  shared/src/ledger/ibc/vp/context.rs
  shared/src/ledger/tx.rs
  shared/src/vm/host_env.rs
  shared/src/vm/wasm/host_env.rs
  tests/src/e2e/ibc_tests.rs
  tests/src/vm_host_env/ibc.rs
  tests/src/vm_host_env/mod.rs
  tests/src/vm_host_env/tx.rs
  tx_prelude/src/ibc.rs
  tx_prelude/src/lib.rs
  vm_env/src/lib.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: ready for draft

#1828 "testing" feature guard masp proofs load/save
  .changelog/unreleased/improvements/1828-feature-guard-masp-proof-load.md
  Makefile
  shared/src/ledger/masp.rs
  shared/src/types/control_flow.rs
Labels: ready for draft

#1848 Add the Bridge pool as a default wallet address
  .changelog/unreleased/improvements/1848-wallet-bridge-pool-addr.md
  apps/src/lib/wallet/defaults.rs
Labels: wallet, ethereum-bridge, ready for draft

#1849 Call `Message::parse` directly
  .changelog/unreleased/improvements/1849-call-msg-parse.md
  core/src/types/key/secp256k1.rs
Labels: enhancement, ledger, ready for draft

#1850 Parse Eth addresses from the CLI
  .changelog/unreleased/improvements/1850-cli-parse-eth-addrs.md
  apps/src/lib/cli/context.rs
Labels: enhancement, client, ethereum-bridge, ready for draft

#1860 Log proper duped validator votes on Ethereum tallies
  .changelog/unreleased/bug-fixes/1860-duped-eth-tally-votes.md
  ethereum_bridge/src/protocol/transactions/votes/update.rs
Labels: bug, ledger, ethereum-bridge, merged to draft

#1468 Custom height db dump
  .changelog/unreleased/improvements/1468-custom-height-db-dump.md
  apps/src/lib/cli.rs
  apps/src/lib/node/ledger/mod.rs
  apps/src/lib/node/ledger/storage/rocksdb.rs
Labels: merged to draft

#1755 Implement the Ethereum token whitelist logic in Namada
  .changelog/unreleased/features/1290-token-whitelist.md
  Cargo.lock
  Cargo.toml
  apps/Cargo.toml
  apps/src/lib/cli.rs
  apps/src/lib/config/genesis.rs
  apps/src/lib/node/ledger/ethereum_oracle/events.rs
  apps/src/lib/node/ledger/ethereum_oracle/mod.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs
  core/Cargo.toml
  core/src/ledger/eth_bridge/storage/bridge_pool.rs
  core/src/ledger/eth_bridge/storage/mod.rs
  core/src/ledger/eth_bridge/storage/whitelist.rs
  core/src/ledger/eth_bridge/storage/wrapped_erc20s.rs
  core/src/types/address.rs
  core/src/types/eth_bridge_pool.rs
  core/src/types/ethereum_events.rs
  core/src/types/storage.rs
  ethereum_bridge/src/parameters.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  ethereum_bridge/src/storage/eth_bridge_queries.rs
  ethereum_bridge/src/test_utils.rs
  shared/Cargo.toml
  shared/src/ledger/args.rs
  shared/src/ledger/eth_bridge/bridge_pool.rs
  shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
  shared/src/ledger/native_vp/ethereum_bridge/mod.rs
  shared/src/ledger/native_vp/ethereum_bridge/nut.rs
  shared/src/ledger/native_vp/ethereum_bridge/vp.rs
  shared/src/ledger/protocol/mod.rs
  shared/src/ledger/queries/shell/eth_bridge.rs
  tests/src/native_vp/eth_bridge_pool.rs
  wasm/Cargo.lock
  wasm/wasm_source/src/tx_bridge_pool.rs
  wasm_for_tests/wasm_source/Cargo.lock
Labels: ledger, ethereum-bridge, ready for draft

#1746 Generic IO
  .changelog/unreleased/features/1746-generic-io.md
  apps/src/bin/namada-client/cli.rs
  apps/src/bin/namada-client/main.rs
  apps/src/bin/namada-relayer/main.rs
  apps/src/bin/namada-wallet/main.rs
  apps/src/lib/cli.rs
  apps/src/lib/cli/api.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/cli/context.rs
  apps/src/lib/cli/relayer.rs
  apps/src/lib/cli/utils.rs
  apps/src/lib/cli/wallet.rs
  apps/src/lib/client/rpc.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/shell/testing/client.rs
  benches/lib.rs
  shared/src/ledger/eth_bridge.rs
  shared/src/ledger/eth_bridge/bridge_pool.rs
  shared/src/ledger/eth_bridge/validator_set.rs
  shared/src/sdk/masp.rs
  shared/src/sdk/rpc.rs
  shared/src/sdk/signing.rs
  shared/src/sdk/tx.rs
  shared/src/types/io.rs
  shared/src/types/mod.rs
  test_fixtures/masp_proofs/0DAF8BDF2318129AC828A7149AC83E76506147445D4DC22D57CBC9869BCDDA80.bin
  test_fixtures/masp_proofs/12C933751C24BDC39C9108F5AF5D4C1BF345378A4FB6BB0B179BA8BDB0D2A3C0.bin
  test_fixtures/masp_proofs/5B99F3D7E0CE75AB1F4B737EC88B269A5436CD72AA758686960F409B04841707.bin
  test_fixtures/masp_proofs/889C046FA76727BC97433503BB79BAC90BA1F01653EBCFDCF7CC8AAA1BBEE462.bin
  test_fixtures/masp_proofs/A9FA2730222946FA51E9D587544FDED28D5E7D3C6B52DCF38A5978CEA70D6FD3.bin
  test_fixtures/masp_proofs/AC308C08512AF5DAA364B845D146763B3CE0BACFB7799C6744E50B9E7F43E961.bin
  test_fixtures/masp_proofs/BE57BA4D8FB068F5A933E78DEF2989556FD771D368849D034E22923FD350EEEC.bin
  test_fixtures/masp_proofs/E76E54B7526CD2B5423322FB711C0CA6AA6520A2AC8BC34A84358EA137F138D0.bin
  tests/src/e2e/ledger_tests.rs
  tests/src/integration/masp.rs
  wasm/checksums.json
Labels: merged to draft

#1835 Parallel vps' gas accounting rework
  .changelog/unreleased/bug-fixes/1835-fix-parallel-vps.md
  core/src/ledger/gas.rs
  shared/src/ledger/protocol/mod.rs
Labels: merged to draft

#1865 Rework voting on Ethereum tallies across epoch boundaries
  .changelog/unreleased/improvements/1865-eth-voting-power.md
  core/src/types/token.rs
  core/src/types/voting_power.rs
  ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  ethereum_bridge/src/protocol/transactions/utils.rs
  ethereum_bridge/src/protocol/transactions/validator_set_update/mod.rs
  ethereum_bridge/src/protocol/transactions/votes.rs
  ethereum_bridge/src/protocol/transactions/votes/storage.rs
  ethereum_bridge/src/protocol/transactions/votes/update.rs
  ethereum_bridge/src/test_utils.rs
  proof_of_stake/src/lib.rs
  proof_of_stake/src/pos_queries.rs
  shared/src/ledger/protocol/mod.rs
  shared/src/ledger/queries/shell/eth_bridge.rs
Labels: enhancement, ledger, ethereum-bridge, ready for draft

#1868 Mariari/sdk folder
  .changelog/unreleased/SDK/1868-shared-utils-folder.md
  .changelog/unreleased/improvements/1868-shared-utils-folder.md
  apps/src/lib/cli.rs
  apps/src/lib/cli/api.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/cli/context.rs
  apps/src/lib/cli/wallet.rs
  apps/src/lib/client/rpc.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/client/utils.rs
  apps/src/lib/node/ledger/shell/testing/node.rs
  apps/src/lib/wallet/cli_utils.rs
  apps/src/lib/wallet/defaults.rs
  apps/src/lib/wallet/mod.rs
  apps/src/lib/wallet/pre_genesis.rs
  apps/src/lib/wallet/store.rs
  benches/lib.rs
  shared/src/ledger/eth_bridge/bridge_pool.rs
  shared/src/ledger/eth_bridge/validator_set.rs
  shared/src/ledger/events.rs
  shared/src/ledger/mod.rs
  shared/src/ledger/queries/mod.rs
  shared/src/ledger/queries/types.rs
  shared/src/ledger/queries/vp/mod.rs
  shared/src/ledger/queries/vp/pos.rs
  shared/src/ledger/queries/vp/token.rs
  shared/src/lib.rs
  shared/src/sdk/args.rs
  shared/src/sdk/error.rs
  shared/src/sdk/masp.rs
  shared/src/sdk/mod.rs
  shared/src/sdk/queries.rs
  shared/src/sdk/rpc.rs
  shared/src/sdk/signing.rs
  shared/src/sdk/tx.rs
  shared/src/sdk/wallet/alias.rs
  shared/src/sdk/wallet/derivation_path.rs
  shared/src/sdk/wallet/keys.rs
  shared/src/sdk/wallet/mod.rs
  shared/src/sdk/wallet/pre_genesis.rs
  shared/src/sdk/wallet/store.rs
  shared/src/types/mod.rs
  shared/src/vm/host_env.rs
Labels: ready for draft

#1874 Removes redundant `WasmPayload` enum
  .changelog/unreleased/improvements/1874-remove-redundant-struct.md
  benches/vps.rs
  shared/src/ledger/protocol/mod.rs
  shared/src/vm/wasm/run.rs
Labels: merged to draft

#1876 Update CONTRIBUTING.md to properly outline how to document SDK changes
  .changelog/unreleased/improvements/1876-updating-contributing.md
  CONTRIBUTING.md
Labels: ready for draft

#1877 Refactor get fee unshield
  .changelog/unreleased/improvements/1877-refactor-get-fee-unshield.md
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/shell/prepare_proposal.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  core/src/proto/types.rs
  shared/src/ledger/protocol/mod.rs
Labels: merged to draft

#1878 Removes fee panics from sdk
  .changelog/unreleased/SDK/1878-remove-sdk-fee-panics.md
  .changelog/unreleased/bug-fixes/1878-remove-sdk-fee-panics.md
  shared/src/sdk/error.rs
  shared/src/sdk/signing.rs
  shared/src/sdk/tx.rs
Labels: merged to draft

#1882 changes gas_cost -> minimum_gas_price in the genesis file
  .changelog/unreleased/improvements/1882-minimum-gas-price.md
  apps/src/lib/config/genesis.rs
  apps/src/lib/node/ledger/shell/init_chain.rs
  apps/src/lib/node/ledger/shell/mod.rs
  core/src/ledger/parameters/mod.rs
  core/src/ledger/parameters/storage.rs
  core/src/ledger/storage/mod.rs
  genesis/dev.toml
  genesis/e2e-tests-single-node.toml
Labels: merged to draft

#1885 Migrate to the new Ethereum contracts
  .changelog/unreleased/miscellaneous/1885-migrate-new-contracts.md
  Cargo.lock
  Cargo.toml
  apps/Cargo.toml
  apps/src/lib/cli.rs
  apps/src/lib/cli/relayer.rs
  apps/src/lib/config/genesis.rs
  apps/src/lib/node/ledger/ethereum_oracle/events.rs
  apps/src/lib/node/ledger/ethereum_oracle/mod.rs
  apps/src/lib/node/ledger/ethereum_oracle/test_tools/mod.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/shell/prepare_proposal.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs
  core/src/ledger/eth_bridge/storage/bridge_pool.rs
  core/src/ledger/eth_bridge/storage/mod.rs
  core/src/ledger/parameters/storage.rs
  core/src/types/eth_abi.rs
  core/src/types/eth_bridge_pool.rs
  core/src/types/ethereum_events.rs
  core/src/types/storage.rs
  core/src/types/vote_extensions/ethereum_events.rs
  core/src/types/vote_extensions/validator_set_update.rs
  core/src/types/voting_power.rs
  ethereum_bridge/src/oracle/config.rs
  ethereum_bridge/src/parameters.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  ethereum_bridge/src/protocol/transactions/votes/storage.rs
  ethereum_bridge/src/protocol/transactions/votes/update.rs
  ethereum_bridge/src/storage/eth_bridge_queries.rs
  ethereum_bridge/src/storage/proof.rs
  ethereum_bridge/src/storage/vote_tallies.rs
  ethereum_bridge/src/test_utils.rs
  shared/Cargo.toml
  shared/src/ledger/eth_bridge/bridge_pool.rs
  shared/src/ledger/eth_bridge/validator_set.rs
  shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
  shared/src/ledger/native_vp/ethereum_bridge/vp.rs
  shared/src/ledger/protocol/mod.rs
  shared/src/ledger/queries/mod.rs
  shared/src/ledger/queries/shell/eth_bridge.rs
  shared/src/sdk/args.rs
  tests/src/native_vp/eth_bridge_pool.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: ledger, ethereum-bridge, ready for draft

#1886 Support validators' hostnames in config
  .changelog/unreleased/improvements/1886-validators-by-hostnames.md
  apps/src/lib/cli.rs
  apps/src/lib/client/utils.rs
  apps/src/lib/config/utils.rs
  genesis/e2e-tests-single-node.toml
  tests/src/e2e/helpers.rs
  tests/src/e2e/setup.rs
Labels: merged to draft

#1887 Fix lower bound in client proposal vote check
  .changelog/unreleased/bug-fixes/1887-fix-client-can-be-voted-check.md
  core/src/ledger/governance/storage/proposal.rs
Labels: client, merged to draft

#1889 Respect force option for proposal vote transaction
  .changelog/unreleased/bug-fixes/1889-respect-force-option.md
  shared/src/sdk/tx.rs
Labels: merged to draft

#1892 Validate txs moving 0 value to the Bridge pool
  .changelog/unreleased/improvements/1892-bridge-pool-zero-fees.md
  shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
Labels: enhancement, ledger, ethereum-bridge, ready for draft

#1893 Never overwrite recent Bridge pool proofs in storage
  .changelog/unreleased/bug-fixes/1893-bridge-pool-roots-signing.md
  core/src/types/storage.rs
  ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs
  ethereum_bridge/src/storage/vote_tallies.rs
  shared/src/ledger/protocol/mod.rs
Labels: bug, ledger, ethereum-bridge, ready for draft

#1894 Makes async traits in the SDK be `Send`
  .changelog/unreleased/SDK/1894-sdk-async-traits-send.md
  .changelog/unreleased/improvements/1894-sdk-async-traits-send.md
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/shell/testing/node.rs
  benches/lib.rs
  shared/Cargo.toml
  shared/src/ledger/queries/mod.rs
  shared/src/sdk/masp.rs
  shared/src/sdk/queries.rs
Labels: merged to draft

#1900 fix and check namada_ethereum_bridge crate build with default features
  Makefile
  ethereum_bridge/Cargo.toml
Labels: merged to draft
