Repository namada-net/namada, pull requests merged in 2023-12, with the labels that each got.

#2246 Fix liveness unjailing
  .changelog/unreleased/improvements/2246-fix-liveness.md
  proof_of_stake/src/lib.rs
  sdk/src/queries/vp/pos.rs
  sdk/src/rpc.rs
  sdk/src/tx.rs
Labels: PoS, merged to draft

#2035 Outdated Ethereum event nonce fixes
  .changelog/unreleased/bug-fixes/2035-outdated-eth-nonces.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/shell/prepare_proposal.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  apps/src/lib/node/ledger/shell/vote_extensions.rs
  apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  ethereum_bridge/src/storage/eth_bridge_queries.rs
Labels: bug, ledger, ethereum-bridge, merged to draft

#2210 Misc PoS updates
  apps/src/lib/cli.rs
  apps/src/lib/node/ledger/shell/init_chain.rs
  genesis/localnet/README.md
  proof_of_stake/src/lib.rs
  proof_of_stake/src/rewards.rs
Labels: merged to draft

#2215 wasm: handle cache loading errors
  .changelog/unreleased/improvements/2215-vp-less-permissive.md
  shared/src/vm/wasm/compilation_cache/common.rs
Labels: merged to draft

#2217 Pos Reward Updates
  .changelog/unreleased/improvements/2217-upgrade-pos-rewards.md
  apps/src/lib/cli.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/client/rpc.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  proof_of_stake/src/lib.rs
  sdk/src/args.rs
  sdk/src/queries/vp/pos.rs
  tests/src/e2e/ledger_tests.rs
Labels: PoS, merged to draft

#2223 deps: upgrade ledger-namada version
  Cargo.lock
  Cargo.toml
Labels: merged to draft

#2225 Removed uses of lifetimes in the SDKs Namada trait and implementation
  .changelog/unreleased/SDK/2225-remove-sdk-lifetimes.md
  apps/src/bin/namada-client/main.rs
  apps/src/bin/namada-relayer/main.rs
  apps/src/lib/bench_utils.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/cli/context.rs
  apps/src/lib/cli/relayer.rs
  apps/src/lib/client/rpc.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/shell/testing/client.rs
  benches/native_vps.rs
  benches/txs.rs
  sdk/src/args.rs
  sdk/src/eth_bridge/bridge_pool.rs
  sdk/src/eth_bridge/validator_set.rs
  sdk/src/lib.rs
  sdk/src/masp.rs
  sdk/src/rpc.rs
  sdk/src/signing.rs
  sdk/src/tx.rs
Labels: SDK, merged to draft

#2230 fix masp rewards underflow
  .changelog/unreleased/bug-fixes/2230-masp-rewards.md
  core/Cargo.toml
  core/src/ledger/masp_conversions.rs
  core/src/types/dec.rs
Labels: merged to draft

#2253 Refactor PoS crate
  .changelog/unreleased/improvements/2253-pos-crate-refactor.md
  apps/src/lib/bench_utils.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/governance.rs
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/shell/prepare_proposal.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  apps/src/lib/node/ledger/shell/queries.rs
  apps/src/lib/node/ledger/shell/testing/node.rs
  apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs
  apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs
  apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs
  apps/src/lib/node/ledger/shims/abcipp_shim.rs
  benches/native_vps.rs
  benches/txs.rs
  ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  ethereum_bridge/src/protocol/transactions/votes.rs
  ethereum_bridge/src/protocol/transactions/votes/update.rs
  ethereum_bridge/src/storage/eth_bridge_queries.rs
  proof_of_stake/src/lib.rs
  proof_of_stake/src/pos_queries.rs
  proof_of_stake/src/queries.rs
  proof_of_stake/src/rewards.rs
  proof_of_stake/src/slashing.rs
  proof_of_stake/src/storage.rs
  proof_of_stake/src/storage_key.rs
  proof_of_stake/src/tests.rs
  proof_of_stake/src/tests/helpers.rs
  proof_of_stake/src/tests/mod.rs
  proof_of_stake/src/tests/state_machine.rs
  proof_of_stake/src/tests/state_machine_v2.rs
  proof_of_stake/src/tests/test_helper_fns.rs
  proof_of_stake/src/tests/test_pos.rs
  proof_of_stake/src/tests/test_slash_and_redel.rs
  proof_of_stake/src/tests/test_validator.rs
  proof_of_stake/src/types/mod.rs
  proof_of_stake/src/validator_set_update.rs
  sdk/src/queries/vp/pos.rs
  shared/src/ledger/native_vp/ibc/mod.rs
  shared/src/ledger/pos/vp.rs
  tests/src/native_vp/pos.rs
  tx_prelude/src/proof_of_stake.rs
  wasm/wasm_source/src/tx_bond.rs
  wasm/wasm_source/src/tx_change_validator_commission.rs
  wasm/wasm_source/src/tx_redelegate.rs
  wasm/wasm_source/src/tx_unbond.rs
  wasm/wasm_source/src/tx_withdraw.rs
  wasm/wasm_source/src/vp_implicit.rs
  wasm/wasm_source/src/vp_user.rs
Labels: PoS, merged to draft, ready for draft, modularization

#2260 CLI revamp - 0.28.0
  .changelog/unreleased/features/2260-wallet-cli-revamping-main-rebased.md
  apps/src/lib/cli.rs
  apps/src/lib/cli/wallet.rs
  sdk/src/args.rs
  sdk/src/wallet/mod.rs
  sdk/src/wallet/store.rs
  tests/src/e2e/helpers.rs
  tests/src/e2e/ledger_tests.rs
  tests/src/e2e/wallet_tests.rs
Labels: cli, wallet

#2285 Masp conversions doesn't require all tokens be in genesis
  .changelog/unreleased/improvments/2285-remove-hardcoded-masp-tokens.md
  apps/src/lib/cli.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/client/rpc.rs
  core/src/ledger/masp_conversions.rs
  sdk/src/queries/shell.rs
  sdk/src/rpc.rs
Labels: ready for draft

#2288 Refactor internal structure of the Ethereum bridge crate
  .changelog/unreleased/improvements/2288-refactor-ethbridge-crate.md
  apps/src/lib/config/genesis/templates.rs
  ethereum_bridge/src/lib.rs
  ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
  ethereum_bridge/src/storage/mod.rs
  ethereum_bridge/src/storage/parameters.rs
  ethereum_bridge/src/storage/vp.rs
  ethereum_bridge/src/storage/vp/bridge_pool.rs
  ethereum_bridge/src/storage/vp/ethereum_bridge.rs
  ethereum_bridge/src/test_utils.rs
  sdk/src/eth_bridge/mod.rs
  sdk/src/queries/shell/eth_bridge.rs
  shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
  shared/src/ledger/native_vp/ethereum_bridge/vp.rs
  shared/src/ledger/protocol/mod.rs
Labels: ethereum-bridge, merged to draft, ready for draft, modularization

#2310 Wait for genesis time
  .changelog/unreleased/bug-fixes/2310-wait-for-genesis-time.md
  apps/src/lib/node/ledger/mod.rs
  sdk/src/control_flow/mod.rs
Labels: ready for draft

#2311 Fix ibc-gen-shielded to receive a non-Namada token
  .changelog/unreleased/SDK/2308-fix-ibc-gen-shielded.md
  .changelog/unreleased/bug-fixes/2308-fix-ibc-gen-shielded.md
  apps/src/lib/cli.rs
  sdk/src/args.rs
  sdk/src/rpc.rs
  sdk/src/tx.rs
  tests/src/e2e/ibc_tests.rs
Labels: ready for draft

#1995 Emit Ethereum Bridge pool transfer events
  .changelog/unreleased/SDK/1995-eth-tx-emits-events.md
  .changelog/unreleased/improvements/1995-eth-tx-emits-events.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  core/src/types/ethereum_structs.rs
  core/src/types/keccak.rs
  core/src/types/transaction/mod.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  sdk/src/eth_bridge/bridge_pool.rs
  sdk/src/events/mod.rs
  sdk/src/queries/mod.rs
  sdk/src/queries/shell/eth_bridge.rs
  shared/src/ledger/protocol/mod.rs
Labels: ledger, SDK, ethereum-bridge, ready for draft

#2213 less permissive VPs
  .changelog/unreleased/improvements/2213-vp-less-permissive.md
  benches/vps.rs
  core/src/types/address.rs
  core/src/types/ibc.rs
  proof_of_stake/src/storage.rs
  wasm/wasm_source/src/vp_implicit.rs
  wasm/wasm_source/src/vp_user.rs
Labels: merged to draft

#2240 MASP nullifier uniqueness
  .changelog/unreleased/bug-fixes/2240-nullifier-uniqueness.md
  core/src/ledger/masp_utils.rs
  core/src/ledger/mod.rs
  core/src/ledger/storage/write_log.rs
  core/src/types/token.rs
  shared/src/ledger/native_vp/ibc/context.rs
  shared/src/ledger/native_vp/masp.rs
  shared/src/vm/host_env.rs
  tx_prelude/src/ibc.rs
  tx_prelude/src/token.rs
  wasm/wasm_source/src/tx_transfer.rs
Labels: merged to draft, ready for draft

#2277 Speed up some PoS tests
  .changelog/unreleased/improvements/2277-speed-up-tests.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  proof_of_stake/src/tests.rs
Labels: merged to draft, ready for draft

#2295 Refactor `apply_inflation`
  .changelog/unreleased/improvements/2295-refactor-apply-inflation.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  core/src/ledger/pgf/inflation.rs
  core/src/ledger/pgf/mod.rs
  proof_of_stake/src/rewards.rs
Labels: ledger, PoS, merged to draft, modularization
