Repository namada-net/namada, pull requests merged in 2023-07, with the labels that each got.

#1578 add tracing-appender for log to files and rolling logs
  .changelog/unreleased/features/1578-fix-init-validator-tm-mode.md
  Cargo.lock
  Cargo.toml
  apps/Cargo.toml
  apps/src/bin/namada-client/main.rs
  apps/src/bin/namada-node/main.rs
  apps/src/bin/namada/main.rs
  apps/src/lib/logging.rs
Labels: merged to draft

#1580 Update clap to the latest v4 version
  .changelog/unreleased/improvements/64-clap-up-v4.md
  Cargo.lock
  Cargo.toml
  apps/src/lib/cli.rs
  apps/src/lib/cli/utils.rs
Labels: cli, refactor / code quality, merged to draft

#1582 PoS: delay slash validator set update when next epoch is done in TM
  .changelog/unreleased/bug-fixes/1582-slash-validator-delay-set-update.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/mod.rs
  proof_of_stake/src/lib.rs
  proof_of_stake/src/tests.rs
  proof_of_stake/src/tests/state_machine.rs
Labels: merged to draft

#1599 wasm secp256k1 sig verification
  .changelog/unreleased/bug-fixes/1599-wasm-secp256k1-sig.md
  apps/src/lib/config/genesis.rs
  apps/src/lib/wallet/defaults.rs
  core/Cargo.toml
  core/src/types/key/secp256k1.rs
  genesis/e2e-tests-single-node.toml
  shared/Cargo.toml
  tests/src/e2e/ledger_tests.rs
  tests/src/e2e/setup.rs
  wasm/checksums.json
Labels: merged to draft

#1604 deps: update wasmer and wasmparser crates
  .changelog/unreleased/improvements/1604-update-wasmer-wasmparser.md
  Cargo.lock
  Cargo.toml
  shared/Cargo.toml
  shared/src/vm/host_env.rs
  shared/src/vm/mod.rs
  shared/src/vm/wasm/run.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: merged to draft

#1615 fix optional prefix iter
  .changelog/unreleased/bug-fixes/1615-fix-optional-prefix-iter.md
  apps/src/lib/node/ledger/storage/rocksdb.rs
Labels: merged to draft

#1628 docs: update rust-analyzer clippy override
  documentation/dev/src/explore/resources/ide.md
Labels: documentation

#1611 Murisi/move init proposal content
  .changelog/unreleased/bug-fixes/1611-move-init-proposal-content.md
  apps/src/bin/namada-client/cli.rs
  apps/src/lib/cli.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  core/src/ledger/storage_api/governance.rs
  core/src/types/transaction/governance.rs
  scripts/generator.sh
  shared/src/ledger/args.rs
  shared/src/ledger/signing.rs
  shared/src/ledger/tx.rs
  wasm/checksums.json
  wasm/wasm_source/src/tx_init_proposal.rs
  wasm_for_tests/tx_memory_limit.wasm
  wasm_for_tests/tx_mint_tokens.wasm
  wasm_for_tests/tx_no_op.wasm
  wasm_for_tests/tx_proposal_code.wasm
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_true.wasm
  wasm_for_tests/vp_eval.wasm
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_read_storage_key.wasm
Labels: merged to draft

#1642 storage prefix iter: skip keys that don't match the full prefix segments
  .changelog/unreleased/improvements/1642-iter-prefix-full-match.md
  apps/src/lib/node/ledger/storage/rocksdb.rs
  core/src/ledger/storage/mockdb.rs
Labels: merged to draft

#1716 test/e2e/slashing: wait for wasm on original validator
  tests/src/e2e/ledger_tests.rs
  tests/src/e2e/setup.rs
Labels: testing, skip-devnet-tests

#1719 ci: clean up
  .github/workflows/automation.yml
  .github/workflows/build-and-test-bridge.yml
  .github/workflows/build-and-test.yml
  .github/workflows/build-tendermint.yml
Labels: CI, skip-devnet-tests

#1735 ci: pre-download masp parameters
  .github/workflows/build-and-test.yml
Labels: CI, skip-devnet-tests

#1759 CI: skip integration tests
  Makefile
Labels: CI
