Repository namada-net/namada, pull requests merged in 2023-06, with the labels that each got.

#1344 pos: add a query to find validator by Tendermint address
  .changelog/unreleased/features/1344-find-validator-by-tm.md
  apps/src/bin/namada-client/cli.rs
  apps/src/lib/cli.rs
  apps/src/lib/client/rpc.rs
  shared/src/ledger/args.rs
  shared/src/ledger/queries/vp/pos.rs
Labels: merged to draft

#1431 app/wallet: rm empty keys mod
  apps/src/lib/wallet/keys.rs
  apps/src/lib/wallet/mod.rs
Labels: merged to draft

#1432 cli: add missing `--wallet-alias-force` and `--alias-force`
  apps/src/lib/cli.rs
Labels: merged to draft

#1434 shared/tx/submit_validator_commission_change: print err even with force
  shared/src/ledger/tx.rs
Labels: merged to draft

#1435 shared/tx: fix err variant typos
  shared/src/ledger/tx.rs
Labels: merged to draft

#1436 cli: rename Tx arg `tx_code_path` to `tx_reveal_code_path`
  apps/src/lib/cli.rs
  shared/src/ledger/args.rs
  shared/src/ledger/tx.rs
Labels: merged to draft

#1444 Common sub-expression elimination in inflation calculation
  shared/src/ledger/inflation.rs
Labels: merged to draft

#1449 Remove ABCI++ dependencies
  Cargo.lock
  Makefile
  apps/Cargo.toml
  core/Cargo.toml
  shared/Cargo.toml
Labels: merged to draft

#1456 client: stop waiting for catch-up when max tries are reached
  .changelog/unreleased/bug-fixes/1456-fix-max-wait-tries.md
  apps/src/bin/namada-client/cli.rs
Labels: merged to draft

#1469 Remove unused module
  .changelog/unreleased/miscellaneous/cwgoes-remove-unused-named-address.md
  core/src/types/named_address.rs
Labels: merged to draft

#1515 Do not ignore control flows in the CLI
  apps/src/bin/namada-client/cli.rs
  apps/src/bin/namada-relayer/cli.rs
Labels: bug, ethereum-bridge

#1519 Refactor timeout logic
  Cargo.lock
  apps/src/lib/client/rpc.rs
  apps/src/lib/client/signing.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/ethereum_oracle/mod.rs
  shared/Cargo.toml
  shared/src/ledger/eth_bridge.rs
  shared/src/ledger/eth_bridge/bridge_pool.rs
  shared/src/ledger/masp.rs
  shared/src/ledger/rpc.rs
  shared/src/ledger/signing.rs
  shared/src/ledger/tx.rs
  shared/src/types/control_flow.rs
  shared/src/types/control_flow/time.rs
  shared/src/vm/wasm/compilation_cache/common.rs
  tests/src/e2e/eth_bridge_tests.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: ledger, refactor / code quality, ethereum-bridge

#1511 test: switch back to upstream proptest release and state-machine
  Cargo.lock
  apps/Cargo.toml
  core/Cargo.toml
  proof_of_stake/Cargo.toml
  proof_of_stake/src/tests/state_machine.rs
  shared/Cargo.toml
  tests/Cargo.toml
  tests/src/native_vp/pos.rs
  tests/src/storage_api/collections/lazy_map.rs
  tests/src/storage_api/collections/lazy_set.rs
  tests/src/storage_api/collections/lazy_vec.rs
  tests/src/storage_api/collections/nested_lazy_map.rs
  wasm/Cargo.lock
  wasm/wasm_source/Cargo.toml
  wasm_for_tests/wasm_source/Cargo.lock
Labels: testing, skip-devnet-tests

#1509 Improve logging related to PoS
  .changelog/unreleased/improvements/1509-improve-pos-logging.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  proof_of_stake/src/lib.rs
  shared/src/ledger/pos/vp.rs
  wasm/checksums.json
Labels: PoS

#1531 Remove `web30` crate and fix Namada interface Ethereum bridge code
  Cargo.lock
  apps/Cargo.toml
  apps/src/bin/namada-relayer/cli.rs
  apps/src/lib/cli.rs
  apps/src/lib/node/ledger/ethereum_oracle/mod.rs
  apps/src/lib/node/ledger/ethereum_oracle/test_tools/mod.rs
  apps/src/lib/node/ledger/mod.rs
  shared/Cargo.toml
  shared/src/ledger/args.rs
  shared/src/ledger/eth_bridge.rs
  shared/src/ledger/eth_bridge/bridge_pool.rs
  shared/src/ledger/eth_bridge/validator_set.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: refactor / code quality, SDK, ethereum-bridge

#1540 fix: wasm unit remove hardcoded vp hash
  wasm/wasm_source/src/vp_implicit.rs
  wasm/wasm_source/src/vp_user.rs
  wasm/wasm_source/src/vp_validator.rs
Labels: testing, skip-devnet-tests

#1534 fix block query to only return committed blocks
  .changelog/unreleased/bug-fixes/1534-fix-block-query.md
  apps/src/lib/client/rpc.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/storage/mod.rs
  apps/src/lib/node/ledger/storage/rocksdb.rs
  core/src/ledger/storage/mockdb.rs
  core/src/ledger/storage/mod.rs
  core/src/types/storage.rs
  core/src/types/time.rs
  proof_of_stake/src/pos_queries.rs
  shared/src/ledger/queries/mod.rs
  shared/src/ledger/queries/shell.rs
  shared/src/ledger/queries/types.rs
  shared/src/ledger/rpc.rs
  tests/src/e2e/ledger_tests.rs
  wasm/checksums.json
Labels: merged to draft

#1558 Small logging fixes for slashing
  .changelog/unreleased/bug-fixes/1558-fix-slash-logging.md
  apps/src/lib/client/rpc.rs
  apps/src/lib/node/ledger/shell/mod.rs
  proof_of_stake/src/lib.rs
Labels: skip-devnet-tests

#1550 test/e2e: wait for wasm pre-compile
  shared/src/vm/wasm/compilation_cache/common.rs
  tests/src/e2e/helpers.rs
  tests/src/e2e/ledger_tests.rs
Labels: testing

#1491 apps: add namadac utils default-base-dir
  .changelog/unreleased/improvements/1491-utils-base-dir.md
  apps/src/bin/namada-client/cli.rs
  apps/src/lib/cli.rs
  apps/src/lib/client/utils.rs
Labels: merged to draft

#1572 ci: added cometbft binaries
  .github/workflows/build-and-test-bridge.yml
  .github/workflows/build-and-test.yml
  .github/workflows/build-tendermint.yml
Labels: CI, skip-devnet-tests

#1575 fix: test_node_connectivity_and_consensus
  tests/src/e2e/ledger_tests.rs
Labels: skip-devnet-tests

#1573 Rebase mariari/key parsing fix
  .changelog/unreleased/bug-fixes/1345-key-parsing-fix.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/init_chain.rs
  apps/src/lib/node/ledger/storage/rocksdb.rs
  core/src/ledger/storage/mod.rs
  core/src/ledger/storage/wl_storage.rs
  core/src/types/storage.rs
Labels: merged to draft

#1404 Add IBC event queries
  .changelog/unreleased/improvements/1404-ibc-event-query.md
  Cargo.lock
  apps/src/lib/node/ledger/shell/finalize_block.rs
  shared/src/ledger/events.rs
  shared/src/ledger/events/log/dumb_queries.rs
  shared/src/ledger/queries/mod.rs
  shared/src/ledger/queries/shell.rs
  tests/Cargo.toml
  tests/src/e2e/ibc_tests.rs
  tests/src/e2e/ledger_tests.rs
  tests/src/e2e/setup.rs
Labels: merged to draft

#1476 Change the tendermint binary ref to `cometbft`
  .changelog/unreleased/miscellaneous/1476-cometbft.md
  .github/workflows/build-and-test-bridge.yml
  .github/workflows/build-and-test.yml
  .github/workflows/build-tendermint.yml
  apps/src/bin/namada-node/cli.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/client/utils.rs
  apps/src/lib/config/mod.rs
  apps/src/lib/node/ledger/mod.rs
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/tendermint_node.rs
  tests/src/e2e/helpers.rs
  tests/src/e2e/ledger_tests.rs
  tests/src/e2e/setup.rs
  wasm/checksums.json
Labels: merged to draft

#1587 docker: update wasm-opt
  docker/namada-wasm/Dockerfile
Labels: CI, skip-devnet-tests

#1589 test/wasm/tx_change_validator_commission: avoid low == high in gen range
  wasm/wasm_source/src/tx_change_validator_commission.rs
Labels: testing, skip-devnet-tests

#1574 Bengt/get comet script
  Makefile
  scripts/get_cometbft.sh
Labels: skip-devnet-tests

#1571 build clean up
  .github/workflows/build-and-test.yml
  Cargo.lock
  Cargo.toml
  Makefile
  apps/Cargo.toml
  apps/src/lib/client/tx.rs
  apps/src/lib/config/genesis.rs
  apps/src/lib/mod.rs
  apps/src/lib/node/ledger/mod.rs
  apps/src/lib/node/ledger/shell/init_chain.rs
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/shims/abcipp_shim_types.rs
  apps/src/lib/node/ledger/tendermint_node.rs
  apps/src/lib/wallet/defaults.rs
  core/Cargo.toml
  encoding_spec/Cargo.toml
  macros/Cargo.toml
  proof_of_stake/Cargo.toml
  shared/Cargo.toml
  shared/src/ledger/ibc/vp/mod.rs
  shared/src/ledger/queries/types.rs
  shared/src/ledger/wallet/store.rs
  shared/src/lib.rs
  test_utils/Cargo.toml
  tests/Cargo.toml
  tests/src/e2e/ibc_tests.rs
  tests/src/e2e/ledger_tests.rs
  tx_prelude/Cargo.toml
  vm_env/Cargo.toml
  vp_prelude/Cargo.toml
  wasm/Cargo.lock
  wasm/Cargo.toml
  wasm/checksums.json
  wasm_for_tests/wasm_source/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.toml
Labels: merged to draft

#1588 shared/masp: add missing await on async load and save calls
  .changelog/unreleased/bug-fixes/1588-fix-masp-missing-await.md
  apps/src/lib/client/rpc.rs
  shared/src/ledger/masp.rs
Labels: merged to draft

#1610 CI: enable debug_assertions in e2e release bins build
  .github/workflows/build-and-test-bridge.yml
  .github/workflows/build-and-test.yml
Labels: skip-devnet-tests

#1614 test/e2e/invalid_txs: wait for a block after restart
  tests/src/e2e/ledger_tests.rs
Labels: testing, skip-devnet-tests
