Repository namada-net/namada, pull requests merged in 2023-11, with the labels that each got.

#2128 Governance `Abstain` vote
  .changelog/unreleased/SDK/2128-governance-abstain-vote.md
  .changelog/unreleased/features/2128-governance-abstain-vote.md
  apps/src/lib/client/rpc.rs
  apps/src/lib/node/ledger/shell/governance.rs
  core/src/ledger/governance/cli/offline.rs
  core/src/ledger/governance/cli/onchain.rs
  core/src/ledger/governance/storage/vote.rs
  core/src/ledger/governance/utils.rs
  sdk/src/signing.rs
  tests/src/e2e/ledger_tests.rs
Labels: merged to draft, ready for draft

#2133 Fix governance bugs
  .changelog/unreleased/bug-fixes/2133-fix-governance-bugs.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  proof_of_stake/src/lib.rs
  shared/src/ledger/governance/mod.rs
Labels: merged to draft, ready for draft

#2126 Fix balance query not to return duplicate results
  .changelog/unreleased/bug-fixes/2125-fix-duplicate-balance.md
  apps/src/lib/client/rpc.rs
Labels: merged to draft, ready for draft

#2100 Win build, attempt #2
  .changelog/unreleased/bug-fixes/2100-win-build.md
  Cargo.toml
Labels: merged to draft

#2062 Remove IBC token denomination and refactoring
  .changelog/unreleased/improvements/2062-ibc-refactoring.md
  core/src/ledger/ibc/context/common.rs
  core/src/ledger/ibc/context/execution.rs
  core/src/ledger/ibc/context/storage.rs
  core/src/ledger/ibc/context/transfer_mod.rs
  core/src/ledger/ibc/context/validation.rs
  core/src/ledger/ibc/mod.rs
  core/src/ledger/storage_api/token.rs
  shared/src/ledger/native_vp/ibc/context.rs
  shared/src/ledger/native_vp/ibc/mod.rs
  shared/src/ledger/native_vp/ibc/token.rs
  shared/src/vm/host_env.rs
  tx_prelude/src/ibc.rs
Labels: merged to draft, ready for draft

#2139 fix: wasm env variables
  apps/src/lib/wasm_loader/mod.rs
Labels: merged to draft, ready for draft

#1905 Replay protection improvements
  .changelog/unreleased/improvements/1905-replay-protection-improvements.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  core/src/ledger/tx_env.rs
  core/src/proto/types.rs
  core/src/types/key/mod.rs
  core/src/types/transaction/mod.rs
  core/src/types/validity_predicate.rs
  shared/src/ledger/native_vp/mod.rs
  shared/src/ledger/protocol/mod.rs
  shared/src/ledger/vp_host_fns.rs
  shared/src/vm/host_env.rs
  shared/src/vm/wasm/host_env.rs
  shared/src/vm/wasm/run.rs
  tests/src/native_vp/mod.rs
  tests/src/vm_host_env/tx.rs
  tests/src/vm_host_env/vp.rs
  tx_prelude/src/lib.rs
  vm_env/src/lib.rs
  wasm/wasm_source/src/tx_bond.rs
  wasm/wasm_source/src/tx_bridge_pool.rs
  wasm/wasm_source/src/tx_change_validator_commission.rs
  wasm/wasm_source/src/tx_ibc.rs
  wasm/wasm_source/src/tx_init_account.rs
  wasm/wasm_source/src/tx_init_proposal.rs
  wasm/wasm_source/src/tx_init_validator.rs
  wasm/wasm_source/src/tx_redelegate.rs
  wasm/wasm_source/src/tx_resign_steward.rs
  wasm/wasm_source/src/tx_reveal_pk.rs
  wasm/wasm_source/src/tx_transfer.rs
  wasm/wasm_source/src/tx_unbond.rs
  wasm/wasm_source/src/tx_unjail_validator.rs
  wasm/wasm_source/src/tx_update_account.rs
  wasm/wasm_source/src/tx_update_steward_commission.rs
  wasm/wasm_source/src/tx_update_vp.rs
  wasm/wasm_source/src/tx_vote_proposal.rs
  wasm/wasm_source/src/tx_withdraw.rs
  wasm_for_tests/tx_fail.wasm
  wasm_for_tests/wasm_source/Cargo.toml
  wasm_for_tests/wasm_source/Makefile
  wasm_for_tests/wasm_source/src/lib.rs
Labels: merged to draft, ready for draft

#1992 PoS rewards
  .changelog/unreleased/features/1992-pos-rewards.md
  .github/workflows/scripts/e2e.json
  apps/src/lib/bench_utils.rs
  apps/src/lib/cli.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  benches/txs.rs
  core/src/ledger/inflation.rs
  core/src/types/token.rs
  core/src/types/transaction/pos.rs
  proof_of_stake/src/lib.rs
  proof_of_stake/src/storage.rs
  proof_of_stake/src/tests.rs
  sdk/src/args.rs
  sdk/src/lib.rs
  sdk/src/signing.rs
  sdk/src/tx.rs
  tests/src/e2e/ledger_tests.rs
  tx_prelude/src/proof_of_stake.rs
  wasm/checksums.json
  wasm/wasm_source/Cargo.toml
  wasm/wasm_source/Makefile
  wasm/wasm_source/src/lib.rs
  wasm/wasm_source/src/tx_claim_rewards.rs
Labels: PoS, merged to draft, ready for draft

#2046 IBC token hash type for addresses
  .changelog/unreleased/improvements/2046-ibc-token-addr.md
  apps/src/lib/client/rpc.rs
  core/src/ledger/ibc/storage.rs
  core/src/types/address.rs
  core/src/types/ibc.rs
  sdk/src/rpc.rs
  tests/src/native_vp/pos.rs
Labels: ledger, IBC, merged to draft, ready for draft

#2050 Reduce merkle tree snapshots
  .changelog/unreleased/improvements/2043-reduce_merkle_stores.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs
  apps/src/lib/node/ledger/storage/mod.rs
  apps/src/lib/node/ledger/storage/rocksdb.rs
  core/src/ledger/storage/merkle_tree.rs
  core/src/ledger/storage/mockdb.rs
  core/src/ledger/storage/mod.rs
  ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs
  ethereum_bridge/src/storage/eth_bridge_queries.rs
  ethereum_bridge/src/test_utils.rs
  sdk/src/queries/shell/eth_bridge.rs
  shared/src/ledger/protocol/mod.rs
Labels: storage, merged to draft, ready for draft

#2082 Validator deactivation and reactivation
  .changelog/unreleased/features/2082-validator-re-de-activate.md
  .github/workflows/scripts/e2e.json
  apps/src/lib/bench_utils.rs
  apps/src/lib/cli.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/client/tx.rs
  benches/txs.rs
  proof_of_stake/src/error.rs
  proof_of_stake/src/lib.rs
  scripts/generator.sh
  sdk/src/args.rs
  sdk/src/error.rs
  sdk/src/lib.rs
  sdk/src/signing.rs
  sdk/src/tx.rs
  tests/src/e2e/ledger_tests.rs
  tx_prelude/src/proof_of_stake.rs
  wasm/checksums.json
  wasm/wasm_source/Cargo.toml
  wasm/wasm_source/Makefile
  wasm/wasm_source/src/lib.rs
  wasm/wasm_source/src/tx_deactivate_validator.rs
  wasm/wasm_source/src/tx_reactivate_validator.rs
Labels: PoS, merged to draft, ready for draft

#2061 ensure that `namada_sdk` crate compiles with default features
  Makefile
  sdk/Cargo.toml
Labels: merged to draft

#2132 print eyre errors with inner errors
  .changelog/unreleased/improvements/2132-better-err-reports.md
  apps/src/lib/config/genesis/templates.rs
  apps/src/lib/node/ledger/shell/mod.rs
  shared/src/ledger/protocol/mod.rs
Labels: merged to draft

#2137 Change validator's consensus key
  .changelog/unreleased/features/2137-consensus-key-change.md
  apps/src/lib/bench_utils.rs
  apps/src/lib/cli.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/client/rpc.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  benches/txs.rs
  core/src/types/transaction/pos.rs
  proof_of_stake/src/error.rs
  proof_of_stake/src/lib.rs
  proof_of_stake/src/tests.rs
  sdk/src/args.rs
  sdk/src/error.rs
  sdk/src/lib.rs
  sdk/src/queries/vp/pos.rs
  sdk/src/rpc.rs
  sdk/src/signing.rs
  sdk/src/tx.rs
  tx_prelude/src/proof_of_stake.rs
  wasm/checksums.json
  wasm/wasm_source/Cargo.toml
  wasm/wasm_source/Makefile
  wasm/wasm_source/src/lib.rs
  wasm/wasm_source/src/tx_change_consensus_key.rs
Labels: PoS, merged to draft

#2145 protocol: remove `panic::catch_unwind` for PoS VP
  .changelog/unreleased/miscellaneous/2145-pos-vp-no-catch.md
  shared/src/ledger/pos/vp.rs
  shared/src/ledger/protocol/mod.rs
Labels: merged to draft, ready for draft

#2163 init validator tx - verify ownership of used keys
  .changelog/unreleased/improvements/2163-init-validator-own-keys.md
  apps/src/lib/bench_utils.rs
  apps/src/lib/client/tx.rs
  benches/host_env.rs
  benches/native_vps.rs
  benches/process_wrapper.rs
  benches/txs.rs
  benches/vps.rs
  core/src/proto/types.rs
  core/src/types/key/mod.rs
  sdk/src/signing.rs
  shared/src/vm/host_env.rs
  shared/src/vm/wasm/host_env.rs
  tests/src/vm_host_env/mod.rs
  tests/src/vm_host_env/tx.rs
  tx_prelude/src/lib.rs
  vm_env/src/lib.rs
  wasm/wasm_source/src/tx_init_validator.rs
Labels: PoS, merged to draft

#2165 Add rand flag for sdk
  .changelog/unreleased/bug-fixes/2164-fix-sdk-feature-flag.md
  sdk/Cargo.toml
Labels: ready for draft

#2169 More checks for certain PoS transactions in validator VP
  .changelog/unreleased/improvements/2169-pos-sigs-for-vp.md
  .github/workflows/scripts/e2e.json
  proof_of_stake/src/storage.rs
  tests/src/e2e/ledger_tests.rs
  vp_prelude/src/lib.rs
  wasm/wasm_source/src/vp_implicit.rs
  wasm/wasm_source/src/vp_user.rs
  wasm/wasm_source/src/vp_validator.rs
Labels: PoS, validity-predicate, merged to draft

#2173 Add redelegation functionality
  .changelog/unreleased/SDK/2140-sdk-redelegate.md
  sdk/src/args.rs
  sdk/src/lib.rs
  sdk/src/tx.rs
Labels: merged to draft

#2178 Misc PoS tasks
  .changelog/unreleased/improvements/2178-misc-pos-tasks.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/init_chain.rs
  apps/src/lib/node/ledger/shell/mod.rs
  ethereum_bridge/src/test_utils.rs
  proof_of_stake/src/epoched.rs
  proof_of_stake/src/lib.rs
  proof_of_stake/src/pos_queries.rs
  proof_of_stake/src/rewards.rs
  proof_of_stake/src/tests.rs
  proof_of_stake/src/types.rs
Labels: PoS, merged to draft, ready for draft

#2184 Fix ABCI queries at the last committed height
  .changelog/unreleased/bug-fixes/2184-fix-abci-last-height-queries.md
  sdk/src/queries/shell.rs
Labels: bug, client, merged to draft
