Repository namada-net/namada, pull requests merged in 2024-05, with the labels that each got.

#2818 Add IBC E2E test with Gaia
  .changelog/unreleased/testing/2232-ibc-namada-gaia-e2e.md
  .github/workflows/scripts/e2e.json
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/setup.rs
Labels: merged to draft, ready for draft

#2832 cli: Propagating errors from fallible `CliToSdk` conversions
  .changelog/unreleased/improvements/2832-cli-fallible-conversions.md
  crates/apps/src/lib/cli.rs
  crates/apps/src/lib/cli/client.rs
  crates/apps/src/lib/cli/relayer.rs
  crates/apps/src/lib/cli/wallet.rs
Labels: merged to draft

#2946 Remove Epoch from WrapperTx
  .changelog/unreleased/improvements/2946-remove-epoch-from-wrappertx.md
  crates/apps/src/lib/bench_utils.rs
  crates/apps/src/lib/config/genesis/transactions.rs
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs
  crates/apps/src/lib/node/ledger/shell/process_proposal.rs
  crates/benches/process_wrapper.rs
  crates/light_sdk/src/transaction/account.rs
  crates/light_sdk/src/transaction/bridge.rs
  crates/light_sdk/src/transaction/governance.rs
  crates/light_sdk/src/transaction/ibc.rs
  crates/light_sdk/src/transaction/mod.rs
  crates/light_sdk/src/transaction/pgf.rs
  crates/light_sdk/src/transaction/pos.rs
  crates/light_sdk/src/transaction/transfer.rs
  crates/namada/src/vm/wasm/run.rs
  crates/sdk/src/eth_bridge/bridge_pool.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tests/src/integration/masp.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/data/wrapper.rs
  crates/tx/src/types.rs
  wasm_for_tests/tx_fail.wasm
  wasm_for_tests/tx_infinite_guest_gas.wasm
  wasm_for_tests/tx_infinite_host_gas.wasm
  wasm_for_tests/tx_invalid_data.wasm
  wasm_for_tests/tx_memory_limit.wasm
  wasm_for_tests/tx_no_op.wasm
  wasm_for_tests/tx_proposal_code.wasm
  wasm_for_tests/tx_proposal_ibc_token_inflation.wasm
  wasm_for_tests/tx_proposal_masp_reward.wasm
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_true.wasm
  wasm_for_tests/vp_eval.wasm
  wasm_for_tests/vp_infinite_guest_gas.wasm
  wasm_for_tests/vp_infinite_host_gas.wasm
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_read_storage_key.wasm
Labels: merged to draft, ready for draft

#3029 Functions to update token balance and supply
  .changelog/unreleased/improvements/3029-token-balance-update-fns.md
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/init_chain.rs
  crates/ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
  crates/ethereum_bridge/src/protocol/transactions/read.rs
  crates/ethereum_bridge/src/protocol/transactions/update.rs
  crates/trans_token/src/storage.rs
Labels: merged to draft, ready for draft

#3030 Update ibc-rs
  .changelog/unreleased/bug-fixes/3011-fix-ibc-client-frozen.md
  Cargo.lock
  Cargo.toml
  crates/apps/src/lib/bench_utils.rs
  crates/apps/src/lib/node/ledger/shell/testing/node.rs
  crates/benches/native_vps.rs
  crates/benches/txs.rs
  crates/core/src/ibc.rs
  crates/ibc/src/context/client.rs
  crates/ibc/src/context/common.rs
  crates/ibc/src/context/execution.rs
  crates/ibc/src/context/mod.rs
  crates/ibc/src/context/validation.rs
  crates/namada/src/ledger/native_vp/ibc/mod.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/vm_host_env/ibc.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft, ready for draft

#3032 Generalize the core API of events
  .changelog/v0.33.0/improvements/3032-generalize-events.md
  .github/workflows/scripts/hermes.txt
  Cargo.lock
  Cargo.toml
  crates/apps/src/lib/client/rpc.rs
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/testing/node.rs
  crates/core/Cargo.toml
  crates/core/src/ethereum_structs.rs
  crates/core/src/event.rs
  crates/core/src/event/extend.rs
  crates/core/src/ibc.rs
  crates/core/src/ibc/event.rs
  crates/core/src/keccak.rs
  crates/core/src/storage.rs
  crates/gas/src/event.rs
  crates/gas/src/lib.rs
  crates/governance/src/utils.rs
  crates/ibc/src/lib.rs
  crates/light_sdk/src/reading/asynchronous/tx.rs
  crates/light_sdk/src/reading/blocking/tx.rs
  crates/namada/Cargo.toml
  crates/namada/src/ledger/governance/utils.rs
  crates/namada/src/ledger/pgf/mod.rs
  crates/namada/src/ledger/pgf/utils.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/events/log.rs
  crates/sdk/src/events/log/dumb_queries.rs
  crates/sdk/src/events/mod.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/queries/shell/eth_bridge.rs
  crates/sdk/src/rpc.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tx/Cargo.toml
  crates/tx/src/data/mod.rs
  crates/tx/src/event.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: refactor / code quality, merged to draft, ready for draft, breaking-change

#3100 Make wasm substorage governable
  .changelog/unreleased/bug-fixes/3100-governable-wasm-txs.md
  crates/core/src/storage.rs
  crates/namada/src/ledger/native_vp/parameters.rs
  wasm/checksums.json
  wasm_for_tests/tx_fail.wasm
  wasm_for_tests/tx_infinite_guest_gas.wasm
  wasm_for_tests/tx_infinite_host_gas.wasm
  wasm_for_tests/tx_invalid_data.wasm
  wasm_for_tests/tx_memory_limit.wasm
  wasm_for_tests/tx_no_op.wasm
  wasm_for_tests/tx_proposal_code.wasm
  wasm_for_tests/tx_proposal_code/src/lib.rs
  wasm_for_tests/tx_proposal_ibc_token_inflation.wasm
  wasm_for_tests/tx_proposal_masp_reward.wasm
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_true.wasm
  wasm_for_tests/vp_eval.wasm
  wasm_for_tests/vp_infinite_guest_gas.wasm
  wasm_for_tests/vp_infinite_host_gas.wasm
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_read_storage_key.wasm
Labels: merged to draft, ready for draft

#3119 Verify the checksum of downloaded wasm files
  .changelog/unreleased/bug-fixes/3119-check-wasm-digests-after-download.md
  crates/apps/src/lib/wasm_loader/mod.rs
Labels: security, merged to draft, ready for draft

#3120 Improve governance voting logic
  .changelog/unreleased/imrpovements/3120-improve-governance-voting-logic.md
  crates/apps/src/lib/config/genesis/templates.rs
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/governance.rs
  crates/benches/native_vps.rs
  crates/benches/txs.rs
  crates/benches/vps.rs
  crates/governance/src/parameters.rs
  crates/governance/src/storage/mod.rs
  crates/governance/src/storage/proposal.rs
  crates/light_sdk/src/transaction/governance.rs
  crates/namada/src/ledger/governance/mod.rs
  crates/proof_of_stake/src/queries.rs
  crates/proof_of_stake/src/storage.rs
  crates/proof_of_stake/src/types/mod.rs
  crates/sdk/src/queries/vp/pos.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tx_prelude/src/proof_of_stake.rs
  wasm/tx_vote_proposal/src/lib.rs
Labels: merged to draft, ready for draft

#3140 Murisi/receive randomness
  Cargo.lock
  Cargo.toml
  crates/apps/src/lib/client/tx.rs
  crates/core/src/masp.rs
  crates/core/src/token.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/tx.rs
  crates/tx/src/lib.rs
  crates/tx/src/types.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft, ready for draft

#3154 More client side checks
  .changelog/unreleased/improvements/3154-minor-cli-fixe4s.md
  crates/governance/src/pgf/cli/steward.rs
  crates/sdk/src/error.rs
  crates/sdk/src/tx.rs
Labels: merged to draft, ready for draft

#3164 Set height for abci_query
  .changelog/unreleased/bug-fixes/3065-abci-query-height.md
  crates/apps/src/lib/node/ledger/shell/queries.rs
  crates/namada/src/ledger/mod.rs
  crates/sdk/src/queries/mod.rs
  crates/sdk/src/queries/router.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/queries/shell/eth_bridge.rs
  crates/sdk/src/queries/types.rs
Labels: merged to draft, ready for draft

#3173 benches: removed outdated benchmarks
  crates/benches/Cargo.toml
  crates/benches/txs.rs
  crates/benches/vps.rs
Labels: merged to draft, ready for draft

#3175 Fix unused import build warnings
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/process_proposal.rs
Labels: merged to draft, ready for draft

#3181 namada/wasm/cache: write the file to cache before updating progress
  .changelog/unreleased/bug-fixes/3181-fix-wasm-cache-pre-compile.md
  crates/namada/src/vm/wasm/compilation_cache/common.rs
Labels: merged to draft, ready for draft

#2975 upgrade docker base images to Debian 12 (Bookworm)
  .changelog/unreleased/improvements/2975-upgrade-docker-images-to-bookworm.md
  docker/namada-wasm/Dockerfile
  docker/namada/Dockerfile
Labels: merged to draft, ready for draft

#3195 Make the internals of ValueSum private
  .changelog/unreleased/improvements/3195-make-internals-value-sum-private.md
  Cargo.lock
  Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft, ready for draft

#3215 Emit CLI warning log msg on non 64-bit hardware
  .changelog/unreleased/miscellaneous/3215-warn-on-non-64bit-arch.md
  crates/apps/src/lib/node/ledger/mod.rs
Labels: ledger, security, merged to draft, ready for draft

#3218 Clean up dependencies
  .changelog/unreleased/improvements/3218-cleanup-dependencies.md
  Cargo.lock
  Cargo.toml
  crates/apps/Cargo.toml
  crates/core/Cargo.toml
  crates/ethereum_bridge/Cargo.toml
  crates/macros/Cargo.toml
  crates/migrations/Cargo.toml
  crates/namada/Cargo.toml
  crates/proof_of_stake/Cargo.toml
  crates/sdk/Cargo.toml
  crates/sdk/src/args.rs
  crates/state/Cargo.toml
  crates/storage/Cargo.toml
  crates/tests/Cargo.toml
  examples/Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft

#3220 Harden max proposal bytes configuration and deserialization
  .changelog/unreleased/bug-fixes/3220-max-proposal-bytes-validation.md
  crates/apps/src/lib/node/ledger/tendermint_node.rs
  crates/core/src/chain.rs
Labels: security, merged to draft, ready for draft

#3226 Add line wrapping to the cli commands
  .changelog/unreleased/improvements/3226-cli-line-wrapping.md
  Cargo.lock
  crates/apps/Cargo.toml
  crates/apps/src/lib/cli.rs
  crates/apps/src/lib/cli/utils.rs
Labels: merged to draft, ready for draft

#3228 Address block rejections resulting from lower validator gas prices
  .changelog/unreleased/bug-fixes/3228-fix-validator-gas-prices.md
  crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs
Labels: bug, ledger, merged to draft, ready for draft

#3241 Cleans up ferveo
  .changelog/unreleased/improvements/3241-ferveo-cleanup.md
  crates/sdk/src/lib.rs
  crates/tests/src/integration/masp.rs
  crates/tx/src/data/decrypted.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/data/wrapper.rs
Labels: merged to draft, ready for draft

#3258 Remove unused WASM memory export
  .changelog/unreleased/improvements/3258-dont-export-wasm-mem.md
  crates/namada/src/vm/wasm/host_env.rs
  crates/namada/src/vm/wasm/run.rs
Labels: enhancement, refactor / code quality, merged to draft, ready for draft

#2817 added clone to transaction structs
  .changelog/unreleased/bug-fixes/2817-light-sdk-clone.md
  crates/light_sdk/src/transaction/account.rs
  crates/light_sdk/src/transaction/bridge.rs
  crates/light_sdk/src/transaction/governance.rs
  crates/light_sdk/src/transaction/ibc.rs
  crates/light_sdk/src/transaction/mod.rs
  crates/light_sdk/src/transaction/pgf.rs
  crates/light_sdk/src/transaction/pos.rs
  crates/light_sdk/src/transaction/transfer.rs
Labels: merged to draft, ready for draft

#3196 Clean up init/join network CLI commands
  .changelog/unreleased/improvements/3196-chain-init-cleanup.md
  Cargo.lock
  crates/apps/src/lib/cli.rs
  crates/apps/src/lib/cli/client.rs
  crates/apps/src/lib/cli/context.rs
  crates/apps/src/lib/client/utils.rs
  crates/apps/src/lib/config/genesis/chain.rs
  crates/tests/Cargo.toml
  crates/tests/src/e2e/setup.rs
  crates/tests/src/integration/setup.rs
  scripts/gen_localnet.py
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: refactor / code quality, merged to draft, ready for draft, breaking-change

#3209 namada/vm: disable floats in wasm
  .changelog/unreleased/improvements/3209-disable-wasm-floats.md
  crates/namada/src/vm/mod.rs
Labels: merged to draft, ready for draft

#3275 tx_ibc wasm again
  .changelog/unreleased/improvements/1831-tx-ibc-wasm.md
  crates/benches/Cargo.toml
  crates/benches/README.md
  crates/benches/txs.rs
  crates/gas/src/lib.rs
  crates/ibc/src/actions.rs
  crates/ibc/src/context/storage.rs
  crates/ibc/src/lib.rs
  crates/namada/src/ledger/native_vp/ibc/context.rs
  crates/namada/src/vm/host_env.rs
  crates/namada/src/vm/mod.rs
  crates/namada/src/vm/wasm/host_env.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/vm_host_env/mod.rs
  crates/tx_prelude/src/ibc.rs
  crates/tx_prelude/src/lib.rs
  crates/vm_env/src/lib.rs
  wasm/tx_ibc/src/lib.rs
Labels: merged to draft, ready for draft

#3284 Replay protection contributes to App Hash
  .changelog/unreleased/improvements/3284-reprot-merklized-commitment.md
  crates/core/src/address.rs
  crates/core/src/address/raw.rs
  crates/core/src/hash.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/node/src/shell/finalize_block.rs
  crates/replay_protection/src/lib.rs
  crates/state/src/wl_state.rs
Labels: ledger, security, merged to draft, ready for draft

#3293 Merklized but not diffed
  .changelog/unreleased/features/3293-merklized-not-diffed.md
  crates/merkle_tree/Cargo.toml
  crates/merkle_tree/src/lib.rs
  crates/node/src/shell/mod.rs
  crates/node/src/storage/mod.rs
  crates/node/src/storage/rocksdb.rs
  crates/state/Cargo.toml
  crates/state/src/lib.rs
  crates/state/src/wl_state.rs
  crates/storage/src/mockdb.rs
Labels: merged to draft, ready for draft

#3295 Removes old tests from workflow scripts
  .github/workflows/scripts/e2e.json
  .github/workflows/scripts/integration.py
Labels: CI

#3232 Remove masp vp dependency on `Transfer`
  .changelog/unreleased/improvements/3232-masp-no-transfer-dep.md
  crates/core/src/masp.rs
  crates/events/src/extend.rs
  crates/namada/src/ledger/native_vp/masp.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/node/src/bench_utils.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/governance.rs
  crates/sdk/src/masp.rs
  crates/shielded_token/src/utils.rs
  crates/state/src/wl_state.rs
  crates/tx/src/action.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/types.rs
  crates/vp_env/src/lib.rs
  wasm/tx_ibc/src/lib.rs
  wasm/tx_transfer/src/lib.rs
  wasm/vp_implicit/src/lib.rs
  wasm/vp_user/src/lib.rs
Labels: merged to draft, ready for draft

#3235 Minor cleanup
  Cargo.lock
  crates/apps/Cargo.toml
  crates/ethereum_bridge/Cargo.toml
  crates/ibc/Cargo.toml
  crates/namada/Cargo.toml
  crates/parameters/Cargo.toml
  crates/proof_of_stake/Cargo.toml
  crates/proof_of_stake/src/types/mod.rs
  crates/sdk/Cargo.toml
  crates/shielded_token/Cargo.toml
  crates/state/Cargo.toml
  crates/storage/Cargo.toml
  crates/tests/Cargo.toml
  crates/tx_prelude/Cargo.toml
  crates/vp_env/Cargo.toml
  crates/vp_prelude/Cargo.toml
  examples/Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
  wasm_for_tests/tx_fail/Cargo.toml
  wasm_for_tests/tx_infinite_guest_gas/Cargo.toml
  wasm_for_tests/tx_infinite_host_gas/Cargo.toml
  wasm_for_tests/tx_invalid_data/Cargo.toml
  wasm_for_tests/tx_memory_limit/Cargo.toml
  wasm_for_tests/tx_no_op/Cargo.toml
  wasm_for_tests/tx_proposal_code/Cargo.toml
  wasm_for_tests/tx_proposal_ibc_token_inflation.wasm
  wasm_for_tests/tx_proposal_ibc_token_inflation/Cargo.toml
  wasm_for_tests/tx_proposal_masp_reward.wasm
  wasm_for_tests/tx_proposal_masp_reward/Cargo.toml
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_read_storage_key/Cargo.toml
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/tx_write/Cargo.toml
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_false/Cargo.toml
  wasm_for_tests/vp_always_true/Cargo.toml
  wasm_for_tests/vp_eval/Cargo.toml
  wasm_for_tests/vp_infinite_guest_gas.wasm
  wasm_for_tests/vp_infinite_guest_gas/Cargo.toml
  wasm_for_tests/vp_infinite_host_gas/Cargo.toml
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_memory_limit/Cargo.toml
  wasm_for_tests/vp_read_storage_key/Cargo.toml
  wasm_for_tests/wasm_source/Cargo.toml
Labels: merged to draft, ready for draft

#3268 Track caller's emitted events
  .changelog/unreleased/improvements/3268-track-caller-events.md
  crates/events/Cargo.toml
  crates/events/src/lib.rs
  crates/events/src/tracer.rs
Labels: enhancement, merged to draft, ready for draft

#3294 Enforce fee payment
  .changelog/unreleased/bug-fixes/3075-force-fee-payment.md
  crates/namada/src/ledger/mod.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/governance.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tx/src/data/protocol.rs
Labels: merged to draft, ready for draft

#3296 Start including MASP randomness in the test vectors.
  .changelog/unreleased/improvements/3296-test-vectors-with-randomness2.md
  Cargo.lock
  Cargo.toml
  crates/sdk/src/lib.rs
  crates/sdk/src/masp.rs
  examples/Cargo.toml
  examples/tx_schema.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: MASP, merged to draft, ready for draft

#3305 remove deprecated dependency from app crate
  .changelog/unreleased/improvements/3305-update-config-rs.md
  Cargo.lock
  Cargo.toml
  crates/apps_lib/src/config/global.rs
  crates/apps_lib/src/config/mod.rs
Labels: merged to draft, ready for draft

#3319 Store IBC trace when minting
  .changelog/unreleased/improvements/3317-store-ibc-trace-when-minting.md
  crates/ibc/src/actions.rs
  crates/ibc/src/context/nft_transfer.rs
  crates/ibc/src/context/storage.rs
  crates/ibc/src/context/token_transfer.rs
  crates/ibc/src/event.rs
  crates/ibc/src/lib.rs
  crates/namada/src/ledger/native_vp/ibc/context.rs
  crates/tx_prelude/src/ibc.rs
Labels: merged to draft, ready for draft

#3321 export more ibc storage keys to wasm
  crates/tx_prelude/src/ibc.rs
Labels: merged to draft, ready for draft
