Repository namada-net/namada, pull requests merged in 2024-11, with the labels that each got.

#3956 Updated gas
  .changelog/unreleased/improvements/3956-adjusted-gas-prices.md
  crates/benches/process_wrapper.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
  crates/sdk/src/lib.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  genesis/hardware/parameters.toml
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: non-breaking-change, merge, backport-44

#3959 Test enabling rewards after shielding and large amounts in the masp
  .changelog/unreleased/bug-fixes/3959-fix-masp-change.md
  crates/apps_lib/src/cli.rs
  crates/core/src/masp.rs
  crates/core/src/token.rs
  crates/core/src/uint.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/tx.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/shielded_token/src/storage.rs
  crates/tests/src/integration/masp.rs
Labels: MASP, breaking:cli, merge, breaking:SDK

#3969 Removes `disposable-gas-payer` arg for custom txs
  .changelog/unreleased/improvements/3969-remove-custom-tx-arg.md
  crates/apps_lib/src/cli.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/tx.rs
Labels: breaking:cli, merge

#3968 New client utils
  .changelog/unreleased/improvements/3968-derive-ibc-token-address.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/utils.rs
Labels: client, non-breaking-change, merge

#3973 make: change "make build" recipe to build in release
  .changelog/unreleased/miscellaneous/3971-make-build-in-release.md
  Makefile
Labels: merge

#3979 Enforce gas spending key usage with disposable gas payers
  .changelog/unreleased/bug-fixes/3979-restore-purged-commits.md
  crates/apps_lib/src/cli.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/tests/src/integration/masp.rs
Labels: cli, MASP, merge

#3971 fix config from env var
  .changelog/unreleased/bug-fixes/3971-fix-config-from-env.md
  Cargo.lock
  Cargo.toml
  crates/apps_lib/src/config/mod.rs
Labels: merge

#3983 Reworks masp fee payment error handling
  .changelog/unreleased/improvements/3983-improve-masp-fee-messages.md
  crates/node/src/protocol.rs
  crates/node/src/shell/process_proposal.rs
Labels: refactor / code quality, UX, non-breaking-change, merge

#3982 Test NAM reward unshields in `values_spanning_multiple_masp_digits`
  .changelog/unreleased/testing/3982-test-unshields-multiple-digits.md
  crates/tests/src/integration/masp.rs
  genesis/hardware/parameters.toml
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: testing, MASP, merge

#3988 ci: increase test integration step timeout
  .github/workflows/ci.yml
Labels: CI, merge

#3947 Update flume
  .changelog/unreleased/bug-fixes/3947-update-flume.md
  Cargo.lock
  Cargo.toml
  wasm/Cargo.lock
Labels: bug, wasm, SDK, dependencies, merge

#3992 mergify: update backporting for maint-0.45 branch
  .mergify.yml
Labels: CI, merge, backport-45

#3993 about: add new required license from ring crate
  about.toml
Labels: merge, backport-45

#3996 fix release.sh script
  scripts/release.sh
Labels: merge

#4000 CI: run on maintenance branches prefixed with "maint-"
  .github/workflows/ci.yml
Labels: CI, merge, backport-45

#3892 update mergify
  .mergify.yml
Labels: CI, merge, backport-45

#4003 Improve MASP sdk errors
  .changelog/unreleased/improvements/4003-better-masp-balance-errors.md
  crates/sdk/src/tx.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
Labels: UX, MASP, SDK, merge, breaking:SDK

#4016 Improve the performance of the shielded sync ledger client
  .changelog/unreleased/improvements/4016-ss-ledger-client-improvements.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/masp.rs
  crates/core/src/control_flow/time.rs
  crates/node/src/bench_utils.rs
  crates/sdk/src/args.rs
  crates/sdk/src/masp/utilities.rs
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
Labels: cli, UX, MASP, SDK, merge, breaking:SDK

#4004 Added more info to gas errors
  .changelog/unreleased/improvements/4004-gas-failure-error-improvements.md
  crates/gas/src/lib.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/mod.rs
Labels: merge

#3974 MASP rewards estimation
  .changelog/unreleased/features/3974-masp-rewards-estimation.md
  Cargo.lock
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/rpc.rs
  crates/core/src/masp.rs
  crates/sdk/src/args.rs
  crates/shielded_token/Cargo.toml
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/shielded_token/src/masp/test_utils.rs
  crates/tests/src/integration/masp.rs
Labels: merge

#4007 docs: Fix broken CometBFT installation guide link
  .changelog/unreleased/docs/4006-fix-cometbft-install-link.md
  README.md
Labels: merge

#3925 Test malleability attacks
  .changelog/unreleased/testing/3925-test-malleability-attacks.md
  crates/apps_lib/src/client/tx.rs
  crates/light_sdk/src/writing/asynchronous/mod.rs
  crates/light_sdk/src/writing/blocking/mod.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/block_alloc.rs
  crates/node/src/shell/block_alloc/states.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
  crates/test_utils/src/lib.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/data/wrapper.rs
  crates/tx/src/types.rs
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Cargo.toml
  wasm_for_tests/Makefile
  wasm_for_tests/vp_verify_signature/Cargo.toml
  wasm_for_tests/vp_verify_signature/src/lib.rs
Labels: testing, merge, backport-45

#4043 Prune more Merkle tree snapshots
  .changelog/unreleased/improvements/4043-prune-more-subtree-snapshots.md
  crates/node/src/storage/mod.rs
  crates/node/src/storage/rocksdb.rs
  crates/state/src/wl_state.rs
  crates/storage/src/db.rs
  crates/storage/src/mockdb.rs
  wasm_for_tests/Cargo.lock
Labels: merge

#4047 Fix client missing help messages
  .changelog/unreleased/improvements/4047-fix-help-msgs.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/rpc.rs
  crates/sdk/src/args.rs
Labels: merge, breaking:SDK, backport-45

#4018 Avoid updating merkle paths of spent notes
  .changelog/unreleased/improvements/4018-update-witness-map-on-spend.md
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
Labels: enhancement, UX, MASP, SDK, merge, breaking:SDK, backport-45

#4044 Updates masp gas limit in genesis files
  genesis/hardware/parameters.toml
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: non-breaking-change, merge, backport-45

#4055 wrap tx by elsewho
  .changelog/unreleased/bug-fixes/4055-wrap-tx-by-elsewho.md
  crates/apps_lib/src/cli.rs
  crates/sdk/src/signing.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: merge

#4021 Fixups learned from dry-run
  .changelog/unreleased/improvements/4021-dryrun-fixups.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/rpc.rs
  crates/proof_of_stake/src/rewards.rs
  crates/sdk/src/tx.rs
Labels: client, merge

#4039 Improve tx result message
  .changelog/unreleased/improvements/4039-adjust-tx-response-output.md
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
  crates/tests/src/e2e/ibc_tests.rs
Labels: UX, breaking:cli, merge, breaking:SDK, backport-45

#4061 dump tx output for reveal_pk transactions when requested
  .changelog/unreleased/bug-fixes/4061-dump-reveal-pk.md
  crates/apps_lib/src/client/tx.rs
Labels: merge

#3960 Memo integrity check in validity predicates
  .changelog/unreleased/bug-fixes/3960-memo-validation-in-vp.md
  crates/core/src/hash.rs
  crates/node/src/protocol.rs
  crates/sdk/src/lib.rs
  crates/tests/src/integration/masp.rs
  crates/vp_prelude/src/lib.rs
  wasm/vp_implicit/src/lib.rs
  wasm/vp_user/src/lib.rs
  wasm_for_tests/tx_proposal_token_gas/src/lib.rs
  wasm_for_tests/vp_verify_signature/src/lib.rs
Labels: bug, validity-predicate, security, merge

#4079 mergify: update backporting for maint-0.46 branch
  .mergify.yml
Labels: CI, merge, backport-46

#4083 Updates `query-protocol-parameters` to display some missing params
  .changelog/unreleased/improvements/4083-log-implicit-vp.md
  crates/apps_lib/src/client/rpc.rs
Labels: client, non-breaking-change, merge

#4071 Narrow down shielding retry logic
  .changelog/unreleased/improvements/4071-narrow-shielding-retry-logic.md
  crates/apps_lib/src/client/tx.rs
Labels: client, MASP, non-breaking-change

#4089 Fix `gen_localnet.py` json exception
  scripts/gen_localnet.py
Labels: testing, merge, backport-46

#4105 governance client fix proposal type
  crates/sdk/src/tx.rs
Labels: client, governance, merge

#4101 Adds debug trace for masp epochs in asset types
  crates/shielded_token/src/masp/shielded_wallet.rs
Labels: MASP, non-breaking-change, merge, backport-46

#4116 Add a single CometBFT dummy validator
  .changelog/unreleased/bug-fixes/4116-comet-genesis-validator-set.md
  crates/node/src/tendermint_node.rs
Labels: bug, ledger, merge, backport-46
