Repository namada-net/namada, pull requests merged in 2024-08, with the labels that each got.

#3583 ci: fix fmt-check
  .github/workflows/ci.yml
Labels: CI

#3576 ledger: avoid load shedding tower info service
  .changelog/unreleased/bug-fixes/3576-remove-load-shed.md
  crates/node/src/lib.rs
  crates/sdk/src/tx.rs
Labels: merge

#3570 Make genesis file based on hardware wallet.
  .changelog/unreleased/testing/3570-hw-e2e.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/wallet/defaults.rs
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/setup.rs
  genesis/hardware/README.md
  genesis/hardware/balances.toml
  genesis/hardware/parameters.toml
  genesis/hardware/src/pre-genesis/bond/bond-tx-albert.toml
  genesis/hardware/src/pre-genesis/established/established-account-tx-albert.toml
  genesis/hardware/src/pre-genesis/established/established-account-tx-bertha.toml
  genesis/hardware/src/pre-genesis/established/established-account-tx-christel.toml
  genesis/hardware/src/pre-genesis/established/established-account-tx-frank.toml
  genesis/hardware/src/pre-genesis/signed-transactions.toml
  genesis/hardware/src/pre-genesis/unsigned-transactions.toml
  genesis/hardware/src/pre-genesis/validator-0/signed-transactions.toml
  genesis/hardware/src/pre-genesis/validator-0/unsigned-transactions.toml
  genesis/hardware/src/pre-genesis/validator-0/validator-wallet.toml
  genesis/hardware/src/pre-genesis/wallet.toml
  genesis/hardware/tokens.toml
  genesis/hardware/transactions.toml
  genesis/hardware/validity-predicates.toml
  wasm/checksums.json
Labels: testing, merge

#3590 test/e2e/masp: wait for first block instead of epoch
  crates/tests/src/e2e/ledger_tests.rs
Labels: testing, merge

#3592 minor refactor to signing method
  .changelog/unreleased/improvements/3592-improve-signers-sdk.md
  crates/apps_lib/src/client/tx.rs
  crates/sdk/src/eth_bridge/bridge_pool.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
Labels: merge

#3554 Update gas costs
  .changelog/unreleased/improvements/3554-rc-gas-update.md
  crates/benches/native_vps.rs
  crates/benches/process_wrapper.rs
  crates/benches/wasm_opcodes.rs
  crates/gas/src/lib.rs
  crates/sdk/src/lib.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  crates/vm/src/wasm/run.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: gas, breaking: protocol, merge

#3598 ledger: remove wasm downloader
  .changelog/unreleased/improvements/3598-remove-wasm-loader.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/wasm_loader/mod.rs
  crates/node/src/lib.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  scripts/gen_localnet.py
Labels: merge

#3589 Various misc improvements
  .changelog/unreleased/improvements/3589-misc-improvements.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/rpc.rs
  crates/core/src/address.rs
  crates/core/src/uint.rs
  crates/node/src/ethereum_oracle/events.rs
  crates/parameters/src/lib.rs
  crates/proof_of_stake/src/tests/test_validator.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/vm/src/wasm/compilation_cache/common.rs
Labels: merge

#3594 Client improvements
  .changelog/unreleased/bug-fixes/3594-client-fix.md
  crates/apps_lib/src/client/tx.rs
  crates/proof_of_stake/src/error.rs
  crates/proof_of_stake/src/lib.rs
Labels: merge

#3593 Add TCP transport support for Ledger wallet
  .changelog/unreleased/features/3593-ledger-tcp-transport.md
  Cargo.lock
  Cargo.toml
  crates/apps_lib/Cargo.toml
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/wallet.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/apps_lib/src/config/genesis/utils.rs
  crates/apps_lib/src/wallet/mod.rs
  crates/apps_lib/src/wallet/transport.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  genesis/hardware/README.md
Labels: merge

#3614 Support arbitrary addresses in `balances.toml`
  .changelog/unreleased/improvements/3614-implicit-addr-balances-toml.md
  crates/apps_lib/src/config/genesis.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/node/src/shell/init_chain.rs
  crates/tests/src/e2e/setup.rs
Labels: merge

#3613 remove checksums.json, fix release.sh script
  scripts/release.sh
  wasm/checksums.json
Labels: CI, merge

#3611 Murisi/fix masp vp mint case
  .changelog/unreleased/bug-fixes/3611-fix-masp-vp-mint-case.md
  crates/ibc/src/lib.rs
  crates/ibc/src/trace.rs
  crates/shielded_token/src/vp.rs
  crates/systems/src/ibc.rs
  crates/tests/src/e2e/ibc_tests.rs
Labels: breaking: protocol, merge

#3507 Murisi/decode asset types
  .changelog/unreleased/improvements/3507-decode-asset-types.md
  crates/sdk/src/signing.rs
  crates/tx/src/data/pgf.rs
  examples/generate_txs.rs
Labels: merge

#3600 test/e2e: make slashing test more reliable
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/lib.rs
Labels: testing, merge

#3573 Add IBC client upgrade test
  .changelog/unreleased/testing/3535-ibc-client-upgrade-test.md
  .github/workflows/scripts/e2e.json
  .github/workflows/scripts/hermes.txt
  Cargo.lock
  Cargo.toml
  crates/benches/native_vps.rs
  crates/ibc/src/context/validation.rs
  crates/ibc/src/lib.rs
  crates/ibc/src/storage.rs
  crates/ibc/src/vp/mod.rs
  crates/node/src/bench_utils.rs
  crates/test_utils/Cargo.toml
  crates/test_utils/src/ibc.rs
  crates/test_utils/src/lib.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/vm_host_env/ibc.rs
  crates/tx_prelude/src/ibc.rs
  scripts/get_hermes.sh
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Cargo.toml
  wasm_for_tests/Makefile
  wasm_for_tests/tx_fail.wasm
  wasm_for_tests/tx_infinite_guest_gas.wasm
  wasm_for_tests/tx_infinite_host_gas.wasm
  wasm_for_tests/tx_invalid_data.wasm
  wasm_for_tests/tx_memory_limit.wasm
  wasm_for_tests/tx_no_op.wasm
  wasm_for_tests/tx_proposal_code.wasm
  wasm_for_tests/tx_proposal_ibc_client_upgrade.wasm
  wasm_for_tests/tx_proposal_ibc_client_upgrade/Cargo.toml
  wasm_for_tests/tx_proposal_ibc_client_upgrade/src/lib.rs
  wasm_for_tests/tx_proposal_ibc_token_inflation.wasm
  wasm_for_tests/tx_proposal_masp_reward.wasm
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_true.wasm
  wasm_for_tests/vp_eval.wasm
  wasm_for_tests/vp_infinite_guest_gas.wasm
  wasm_for_tests/vp_infinite_host_gas.wasm
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_read_storage_key.wasm
Labels: merge

#3629 Improve governance client validation
  .changelog/unreleased/improvements/3629-improve-init-proposal-validation.md
  crates/apps_lib/src/client/rpc.rs
  crates/governance/src/cli/onchain.rs
  crates/governance/src/cli/validation.rs
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: merge

#3645 Only allow `tnam1...` addresses in `balances.toml`
  .changelog/unreleased/bug-fixes/3645-implicit-addr-balances-toml-fix.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/config/genesis.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/node/src/shell/init_chain.rs
  crates/tests/src/e2e/setup.rs
  genesis/hardware/balances.toml
  genesis/localnet/balances.toml
Labels: prio:high, breaking:genesis, merge

#3615 Remove parallel gas
  .changelog/unreleased/improvements/3615-no-parallel-gas.md
  .github/workflows/scripts/hermes.txt
  crates/gas/src/lib.rs
  crates/node/src/protocol.rs
  crates/shielded_token/src/validation.rs
  crates/tx/src/data/mod.rs
  scripts/get_hermes.sh
Labels: gas, breaking: protocol, merge

#3632 Check masp action
  .changelog/unreleased/improvements/3632-check-masp-action.md
  crates/governance/src/vp/mod.rs
  crates/ibc/src/vp/mod.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
  crates/shielded_token/src/vp.rs
  crates/state/src/wl_state.rs
  crates/state/src/write_log.rs
  crates/tx/src/action.rs
Labels: MASP, breaking: protocol, merge

#3653 Add birthdays to MASP keys
  .changelog/unreleased/features/3653-masp-key-birthdays.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/cli/context.rs
  crates/apps_lib/src/cli/wallet.rs
  crates/apps_lib/src/client/masp.rs
  crates/benches/native_vps.rs
  crates/core/src/masp.rs
  crates/node/src/bench_utils.rs
  crates/sdk/src/args.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/wallet/keys.rs
  crates/sdk/src/wallet/mod.rs
  crates/sdk/src/wallet/store.rs
Labels: merge

#3655 Optimize building chain ctx
  .changelog/unreleased/improvements/3655-speed-up-ctx-build.md
  crates/apps_lib/src/cli/context.rs
  crates/apps_lib/src/config/genesis/chain.rs
Labels: enhancement, cli, UX, merge

#3652 ctxless cli node utils
  .changelog/unreleased/improvements/3652-ctxless-node-utils.md
  .github/workflows/scripts/e2e.json
  crates/apps/src/bin/namada-node/cli.rs
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/node/src/lib.rs
  crates/node/src/shell/testing/client.rs
  crates/tests/src/e2e/ledger_tests.rs
Labels: merge

#3658 rm accidentally revived files
  wasm_for_tests/tx_fail.wasm
  wasm_for_tests/tx_infinite_guest_gas.wasm
  wasm_for_tests/tx_infinite_host_gas.wasm
  wasm_for_tests/tx_invalid_data.wasm
  wasm_for_tests/tx_memory_limit.wasm
  wasm_for_tests/tx_no_op.wasm
  wasm_for_tests/tx_proposal_code.wasm
  wasm_for_tests/tx_proposal_ibc_client_upgrade.wasm
  wasm_for_tests/tx_proposal_ibc_token_inflation.wasm
  wasm_for_tests/tx_proposal_masp_reward.wasm
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_true.wasm
  wasm_for_tests/vp_eval.wasm
  wasm_for_tests/vp_infinite_guest_gas.wasm
  wasm_for_tests/vp_infinite_host_gas.wasm
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_read_storage_key.wasm
Labels: merge

#3578 Shielded sync phase 3 client
  .changelog/unreleased/SDK/3578-masp-ss-client-phase-3.md
  Cargo.lock
  Cargo.toml
  crates/apps_lib/Cargo.toml
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/api.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/masp.rs
  crates/benches/host_env.rs
  crates/benches/native_vps.rs
  crates/benches/process_wrapper.rs
  crates/core/Cargo.toml
  crates/core/src/control_flow/mod.rs
  crates/core/src/dec.rs
  crates/node/src/abortable.rs
  crates/node/src/bench_utils.rs
  crates/node/src/shell/testing/client.rs
  crates/node/src/shell/testing/node.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/args.rs
  crates/sdk/src/eth_bridge/bridge_pool.rs
  crates/sdk/src/eth_bridge/validator_set.rs
  crates/sdk/src/io.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/masp/shielded_sync/dispatcher.rs
  crates/sdk/src/masp/shielded_sync/mod.rs
  crates/sdk/src/masp/shielded_sync/utils.rs
  crates/sdk/src/masp/test_utils.rs
  crates/sdk/src/masp/utils.rs
  crates/sdk/src/task_env.rs
  crates/sdk/src/wallet/keys.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/setup.rs
  crates/tx/src/lib.rs
  crates/tx/src/types.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: client, MASP, SDK, merge

#3660 check pre genesis signing
  .changelog/unreleased/features/3660-check-pre-genesis-signing.md
  crates/apps/src/bin/namada-node/cli.rs
  crates/apps_lib/src/cli.rs
  crates/node/src/utils.rs
  crates/tests/src/e2e/ledger_tests.rs
Labels: merge

#3445 fuzz test txs
  .changelog/unreleased/testing/3445-fuzz-tx.md
  Cargo.lock
  Cargo.toml
  Makefile
  crates/account/Cargo.toml
  crates/account/src/types.rs
  crates/core/Cargo.toml
  crates/core/src/address.rs
  crates/core/src/chain.rs
  crates/core/src/dec.rs
  crates/core/src/eth_bridge_pool.rs
  crates/core/src/ethereum_events.rs
  crates/core/src/hash.rs
  crates/core/src/ibc.rs
  crates/core/src/key/common.rs
  crates/core/src/key/ed25519.rs
  crates/core/src/key/mod.rs
  crates/core/src/key/secp256k1.rs
  crates/core/src/masp.rs
  crates/core/src/storage.rs
  crates/core/src/time.rs
  crates/core/src/token.rs
  crates/core/src/uint.rs
  crates/governance/Cargo.toml
  crates/governance/src/storage/proposal.rs
  crates/governance/src/storage/vote.rs
  crates/ibc/Cargo.toml
  crates/ibc/src/msg.rs
  crates/node/Cargo.toml
  crates/node/src/protocol.rs
  crates/node/src/shell/init_chain.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/sdk/Cargo.toml
  crates/token/Cargo.toml
  crates/token/src/lib.rs
  crates/trans_token/src/storage.rs
  crates/tx/Cargo.toml
  crates/tx/src/data/mod.rs
  crates/tx/src/data/pgf.rs
  crates/tx/src/data/pos.rs
  crates/tx/src/data/protocol.rs
  crates/tx/src/data/wrapper.rs
  crates/tx/src/types.rs
  fuzz/.gitignore
  fuzz/Cargo.toml
  fuzz/README.md
  fuzz/fuzz_targets/txs_finalize_block.rs
  fuzz/fuzz_targets/txs_mempool.rs
  fuzz/fuzz_targets/txs_prepare_proposal.rs
  fuzz/fuzz_targets/txs_process_proposal.rs
  fuzz/fuzz_targets/txs_wasm_run.rs
  wasm/Cargo.lock
  wasm/Makefile
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Makefile
Labels: merge

#3667 fix rustdoc issues
  README.md
  crates/ethereum_bridge/src/storage/eth_bridge_queries.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/masp/shielded_sync/dispatcher.rs
Labels: merge

#3669 Fix masp events
  .changelog/unreleased/improvements/3669-fix-masp-ident.md
  crates/apps_lib/src/cli.rs
  crates/node/src/protocol.rs
  crates/shielded_token/src/vp.rs
  crates/tests/src/integration/masp.rs
Labels: IBC, MASP, merge

#3646 Support only a transparent address as a refund target
  .changelog/unreleased/bug-fixes/3620-ibc-refund-transparent.md
  crates/ibc/build.rs
  crates/ibc/src/context/nft_transfer.rs
  crates/ibc/src/context/token_transfer.rs
  crates/ibc/src/lib.rs
  crates/ibc/src/msg.rs
  crates/sdk/src/tx.rs
  crates/tests/src/e2e/ibc_tests.rs
Labels: merge

#3673 Amend comment in genesis sign txs
  crates/apps_lib/src/config/genesis/transactions.rs
Labels: documentation, merge

#3676 Remove unused deps for `wasm_for_tests`
  .changelog/unreleased/improvements/3676-fix-wasm-test-deps.md
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Makefile
  wasm_for_tests/tx_fail/Cargo.toml
  wasm_for_tests/tx_infinite_guest_gas/Cargo.toml
  wasm_for_tests/tx_infinite_host_gas/Cargo.toml
  wasm_for_tests/tx_invalid_data/Cargo.toml
  wasm_for_tests/tx_memory_limit/Cargo.toml
  wasm_for_tests/tx_no_op/Cargo.toml
  wasm_for_tests/tx_proposal_code/Cargo.toml
  wasm_for_tests/tx_proposal_ibc_client_upgrade/Cargo.toml
  wasm_for_tests/tx_proposal_ibc_token_inflation/Cargo.toml
  wasm_for_tests/tx_proposal_masp_reward/Cargo.toml
  wasm_for_tests/tx_read_storage_key/Cargo.toml
  wasm_for_tests/tx_write/Cargo.toml
  wasm_for_tests/vp_always_false/Cargo.toml
  wasm_for_tests/vp_always_true/Cargo.toml
  wasm_for_tests/vp_eval/Cargo.toml
  wasm_for_tests/vp_infinite_guest_gas/Cargo.toml
  wasm_for_tests/vp_infinite_host_gas/Cargo.toml
  wasm_for_tests/vp_memory_limit/Cargo.toml
  wasm_for_tests/vp_read_storage_key/Cargo.toml
Labels: wasm, testing, dependencies, ready-for-draft, merge

#3675 token: fix transfer to self
  .changelog/unreleased/bug-fixes/3675-improve-init-proposal-validation.md
  crates/trans_token/src/storage.rs
Labels: breaking: protocol, merge

#3678 make build: exclude fuzz targets
  Makefile
Labels: merge

#3680 Augment the functionality of `gen_localnet.py`
  .changelog/unreleased/testing/3680-gen-localnet-fullnodes.md
  scripts/gen_localnet.py
  scripts/localnet-2.sh
Labels: testing, merge

#3677 sdk: use client instead of context
  crates/apps_lib/src/client/rpc.rs
  crates/sdk/src/rpc.rs
Labels: merge

#3689 Minor fixes to governance cli/msgs
  .changelog/unreleased/improvements/3689-misc-gov-fixes.md
  crates/apps_lib/src/cli.rs
  crates/governance/src/vp/mod.rs
  wasm/vp_implicit/src/lib.rs
Labels: cli, governance, non-breaking-change, merge

#3694 fix wasm dir during join-network
  .changelog/unreleased/bug-fixes/3694-fix-join-network-wasm-dir.md
  crates/apps_lib/src/client/utils.rs
Labels: merge

#3700 Propagates error from `is_proposal_accepted`
  .changelog/unreleased/bug-fixes/3700-fix-error-mishandling.md
  crates/governance/src/vp/mod.rs
  crates/governance/src/vp/pgf.rs
  crates/ibc/src/vp/mod.rs
  crates/trans_token/src/vp.rs
Labels: breaking: protocol, merge

#3705 wallet decoding err
  .changelog/unreleased/bug-fixes/3705-wallet-decoding-err.md
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/wallet/mod.rs
  crates/apps_lib/src/wallet/store.rs
  crates/sdk/src/wallet/mod.rs
  crates/tests/src/integration/setup.rs
Labels: merge

#3709 Add test coverage on token transfer struct
  crates/token/src/lib.rs
Labels: testing, merge

#3687 Apply snapshot for state sync
  .changelog/unreleased/improvements/3687-apply-snapshots.md
  crates/apps_lib/src/config/mod.rs
  crates/merkle_tree/src/lib.rs
  crates/node/src/lib.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/snapshots.rs
  crates/node/src/shell/testing/node.rs
  crates/node/src/shims/abcipp_shim.rs
  crates/node/src/storage/mod.rs
  crates/node/src/storage/rocksdb.rs
  crates/node/src/tendermint_node.rs
  crates/state/src/wl_state.rs
  crates/storage/src/db.rs
  crates/storage/src/mockdb.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: merge

#3701 Optimize state sync snapshot format
  .changelog/unreleased/improvements/3701-snapshot-improvements.md
  Cargo.lock
  Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/shell/mod.rs
  crates/node/src/shell/snapshots.rs
  crates/node/src/shims/abcipp_shim.rs
  crates/node/src/shims/abcipp_shim_types.rs
  crates/node/src/storage/mod.rs
  crates/node/src/storage/rocksdb.rs
  crates/storage/src/db.rs
  crates/storage/src/mockdb.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: enhancement, merge

#3697 refactor tendermint-rs reexports
  .changelog/unreleased/improvements/3697-refactor-tm-reexports.md
  crates/apps/src/bin/namada-client/main.rs
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/api.rs
  crates/apps_lib/src/client/rpc.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/config/genesis/chain.rs
  crates/apps_lib/src/config/mod.rs
  crates/apps_lib/src/config/utils.rs
  crates/apps_lib/src/lib.rs
  crates/apps_lib/src/tendermint_node.rs
  crates/core/src/lib.rs
  crates/events/src/extend.rs
  crates/events/src/lib.rs
  crates/ibc/src/event.rs
  crates/node/src/bench_utils.rs
  crates/node/src/broadcaster.rs
  crates/node/src/lib.rs
  crates/node/src/shell/block_alloc.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/init_chain.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
  crates/node/src/shell/snapshots.rs
  crates/node/src/shell/testing/client.rs
  crates/node/src/shell/testing/node.rs
  crates/node/src/shell/vote_extensions/bridge_pool_vext.rs
  crates/node/src/shell/vote_extensions/eth_events.rs
  crates/node/src/shell/vote_extensions/val_set_update.rs
  crates/node/src/shims/abcipp_shim.rs
  crates/node/src/shims/abcipp_shim_types.rs
  crates/node/src/tendermint_node.rs
  crates/node/src/utils.rs
  crates/sdk/src/queries/types.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/setup.rs
  fuzz/fuzz_targets/txs_prepare_proposal.rs
Labels: merge

#3703 Change default proposal quorum
  .changelog/unreleased/improvements/3703-change-default-gov-quorum.md
  crates/core/src/dec.rs
  crates/governance/src/utils.rs
Labels: breaking: protocol, merge

#3702 derive Serialize for PosParams, OwnedPosParams, GovernanceParameters
  .changelog/unreleased/improvements/3702-main.md
  crates/governance/src/parameters.rs
  crates/proof_of_stake/src/parameters.rs
Labels: merge

#3720 Batch `reveal_pk`
  .changelog/unreleased/improvements/3720-batch-reveal-pk.md
  crates/apps_lib/src/client/tx.rs
Labels: merge

#3693 Clean IBC E2E tests
  .changelog/unreleased/testing/3601-clean-ibc-e2e.md
  .github/workflows/scripts/e2e.json
  crates/test_utils/src/lib.rs
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Cargo.toml
  wasm_for_tests/Makefile
  wasm_for_tests/tx_proposal_ibc_client_upgrade/Cargo.toml
  wasm_for_tests/tx_proposal_ibc_client_upgrade/src/lib.rs
  wasm_for_tests/tx_proposal_ibc_token_inflation/src/lib.rs
Labels: merge

#3725 Improve `gen_localnet.py` and `localnet-2.sh` scripts
  scripts/gen_localnet.py
  scripts/localnet-2.sh
Labels: testing, merge

#3691 CLI queries for total supply info
  .changelog/unreleased/improvements/3691-cli-commands.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/rpc.rs
  crates/sdk/src/args.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: client, merge
