Repository namada-net/namada, pull requests merged in 2024-10, with the labels that each got.

#3857 Batch events tests
  .changelog/unreleased/testing/3857-batch-events-tests.md
  crates/events/src/extend.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
  crates/test_utils/src/lib.rs
  crates/tx_prelude/src/lib.rs
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Cargo.toml
  wasm_for_tests/Makefile
  wasm_for_tests/tx_fail_event/Cargo.toml
  wasm_for_tests/tx_fail_event/src/lib.rs
  wasm_for_tests/tx_no_op_event/Cargo.toml
  wasm_for_tests/tx_no_op_event/src/lib.rs
Labels: testing, non-breaking-change, merge, backport-44

#3862 ci/mergify: add merge rule for backport to 0.44
  .mergify.yml
Labels: merge, backport-44

#3868 add tests & refactor tx crate - alt
  .changelog/unreleased/improvements/3835-refactor-tx-crate.md
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/client/utils.rs
  crates/node/src/dry_run_tx.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
  crates/node/src/shell/vote_extensions.rs
  crates/sdk/src/masp/utilities.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  crates/tx/src/action.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/lib.rs
  crates/tx/src/section.rs
  crates/tx/src/sign.rs
  crates/tx/src/types.rs
  wasm/tx_ibc/src/lib.rs
  wasm/tx_transfer/src/lib.rs
  wasm/tx_update_account/src/lib.rs
Labels: merge, backport-44

#3874 governance: let validator vote even if it doesn't have a self-bond
  crates/tx_prelude/src/proof_of_stake.rs
  wasm/tx_vote_proposal/src/lib.rs
Labels: merge, backport-44

#3882 Avoid duplicated sections in batches
  .changelog/unreleased/improvements/3882-better-batch-construction.md
  crates/sdk/src/signing.rs
  crates/tx/src/types.rs
Labels: non-breaking-change, merge, backport-44

#3891 mergify: unquote base branch name
  .mergify.yml
Labels: merge, backport-44

#3894 Attempt to kill bg process in tests
  crates/tests/src/e2e/setup.rs
Labels: merge, backport-44

#3860 feat: serde rename batch index into masp tx index
  .changelog/unreleased/bug-fixes/3860-serde-rename-batch-index.md
  crates/sdk/src/masp/utilities.rs
Labels: bug, client, SDK, merge, backport-44

#3899 feat: Add new rpc query function to check validators' liveness(uptime)
  .changelog/unreleased/improvements/3899-get-validators-livenesses.md
  crates/proof_of_stake/src/types/mod.rs
  crates/sdk/src/queries/vp/pos.rs
  crates/sdk/src/rpc.rs
Labels: merge, backport-44

#3902 Fix integration tests assertions
  crates/node/src/shell/testing/node.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
Labels: testing, merge, backport-44

#3909 test/e2e/ibc: try to killall gaiad before running it
  crates/tests/src/e2e/ibc_tests.rs
Labels: testing

#3840 Masp tests
  .changelog/unreleased/testing/3840-masp-tests.md
  crates/shielded_token/src/vp.rs
  crates/tests/src/integration/masp.rs
Labels: merge, backport-44

#3921 Add a bunch of low hanging fruit masp tests
  crates/core/src/masp.rs
Labels: testing, MASP, merge, backport-44

#3924 Increasing code coverage in sdk/signing
  .changelog/unreleased/testing/3924-testing-core-signing.md
  crates/sdk/src/signing.rs
  crates/wallet/src/lib.rs
Labels: merge, backport-44

#3928 Improve gas messages
  .changelog/unreleased/improvements/3928-improve-gas-msgs.md
  crates/node/src/protocol.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
Labels: non-breaking-change, merge, backport-44

#3936 Adds comment for masp assets' epoch
  crates/shielded_token/src/vp.rs
Labels: merge, backport-44

#3900 Offline wrapper signing
  .changelog/unreleased/features/3900-offline-wrapper-signature.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/sdk/src/args.rs
  crates/sdk/src/error.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
Labels: breaking:client, merge, breaking:SDK

#3940 Small misc fixes
  .changelog/unreleased/improvements/3940-small-tings.md
  crates/apps_lib/src/client/rpc.rs
  crates/governance/src/cli/validation.rs
  crates/proof_of_stake/src/error.rs
  crates/proof_of_stake/src/rewards.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
  crates/tests/src/integration/ledger_tests.rs
  genesis/hardware/parameters.toml
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: merge
