Repository namada-net/namada, pull requests merged in 2024-07, with the labels that each got.

#3455 Adjust IBC e2e test config
  .changelog/unreleased/testing/3455-ibc-e2e-config.md
  .github/workflows/scripts/e2e.json
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
Labels: merged to draft, ready for draft

#3343 cli: add shell completions generator
  .changelog/unreleased/improvements/3343-shell-complete.md
  Cargo.lock
  Cargo.toml
  crates/apps/Cargo.toml
  crates/apps/src/bin/namada/cli.rs
  crates/apps_lib/src/cli.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/args.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft, ready for draft

#3356 Vectorize transfers
  .changelog/unreleased/features/3356-vectorize-transfers.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/tx.rs
  crates/benches/host_env.rs
  crates/benches/native_vps.rs
  crates/benches/process_wrapper.rs
  crates/light_sdk/src/transaction/transfer.rs
  crates/node/src/bench_utils.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/token/src/lib.rs
  crates/tx_prelude/src/token.rs
  wasm/tx_shielding_transfer/src/lib.rs
  wasm/tx_transparent_transfer/src/lib.rs
  wasm/tx_unshielding_transfer/src/lib.rs
Labels: merged to draft, ready for draft

#3366 Remove max block time param
  .changelog/unreleased/improvements/3366-remove-max-block-time-param.md
  .github/workflows/scripts/hermes.txt
  Cargo.lock
  crates/apps_lib/src/client/rpc.rs
  crates/apps_lib/src/config/genesis.rs
  crates/apps_lib/src/config/genesis/chain.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/core/src/parameters.rs
  crates/core/src/time.rs
  crates/ibc/src/context/common.rs
  crates/ibc/src/context/validation.rs
  crates/namada/src/ledger/native_vp/ibc/mod.rs
  crates/node/src/storage/mod.rs
  crates/parameters/Cargo.toml
  crates/parameters/src/lib.rs
  crates/parameters/src/storage.rs
  crates/proof_of_stake/src/lib.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/rpc.rs
  crates/state/src/lib.rs
  crates/storage/src/lib.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/vm_host_env/ibc.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
  scripts/get_hermes.sh
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: ledger, IBC, MASP, SDK, merged to draft, breaking:genesis, ready for draft, breaking:state

#3375 store MASP total rewards
  .changelog/unreleased/bug-fixes/3375-masp-total-rewards.md
  .changelog/unreleased/improvements/3375-masp-total-rewards.md
  crates/apps_lib/src/client/rpc.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
  crates/shielded_token/src/conversion.rs
  crates/shielded_token/src/storage.rs
  crates/shielded_token/src/storage_key.rs
Labels: merged to draft, ready for draft

#3378 Increase disposable key lifetime
  .changelog/unreleased/bug-fixes/3378-increase-disposable-key-lifetime.md
  crates/sdk/src/wallet/mod.rs
Labels: merged to draft, ready for draft

#3380 Remove max number of signatures per tx
  .changelog/unreleased/improvements/3380-remove-max-sigs.md
  crates/apps_lib/src/config/genesis.rs
  crates/apps_lib/src/config/genesis/chain.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/core/src/parameters.rs
  crates/namada/src/ledger/native_vp/masp.rs
  crates/namada/src/vm/host_env.rs
  crates/namada/src/vm/wasm/host_env.rs
  crates/node/src/storage/mod.rs
  crates/parameters/src/lib.rs
  crates/parameters/src/storage.rs
  crates/proof_of_stake/src/lib.rs
  crates/state/src/lib.rs
  crates/tests/src/vm_host_env/mod.rs
  crates/tests/src/vm_host_env/tx.rs
  crates/tests/src/vm_host_env/vp.rs
  crates/tx/src/types.rs
  crates/tx_prelude/src/lib.rs
  crates/vm_env/src/lib.rs
  crates/vp_prelude/src/lib.rs
  genesis/localnet/parameters.toml
  wasm/tx_become_validator/src/lib.rs
  wasm/tx_change_consensus_key/src/lib.rs
  wasm/vp_implicit/src/lib.rs
  wasm/vp_user/src/lib.rs
Labels: merged to draft, breaking:genesis, ready for draft

#3389 Enforce consistent datetime serialization
  .changelog/unreleased/bug-fixes/3389-consistent-datetime-serialization.md
  Cargo.lock
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/config/genesis/chain.rs
  crates/core/src/time.rs
  crates/namada/src/ledger/native_vp/ibc/mod.rs
  crates/node/src/shell/finalize_block.rs
  crates/tests/fixtures/txs.json
  crates/tests/src/e2e/setup.rs
  crates/tx/Cargo.toml
  crates/tx/src/types.rs
  crates/tx_prelude/Cargo.toml
  crates/vp_prelude/Cargo.toml
  genesis/localnet/src/pre-genesis/signed-transactions.toml
  genesis/localnet/src/pre-genesis/validator-0/signed-transactions.toml
  genesis/localnet/transactions.toml
  scripts/gen_localnet.py
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
  wasm_for_tests/tx_fail.wasm
  wasm_for_tests/tx_infinite_guest_gas.wasm
  wasm_for_tests/tx_infinite_host_gas.wasm
  wasm_for_tests/tx_invalid_data.wasm
  wasm_for_tests/tx_memory_limit.wasm
  wasm_for_tests/tx_no_op.wasm
  wasm_for_tests/tx_proposal_code.wasm
  wasm_for_tests/tx_proposal_ibc_token_inflation.wasm
  wasm_for_tests/tx_proposal_masp_reward.wasm
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_true.wasm
  wasm_for_tests/vp_eval.wasm
  wasm_for_tests/vp_infinite_guest_gas.wasm
  wasm_for_tests/vp_infinite_host_gas.wasm
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_read_storage_key.wasm
Labels: bug, merged to draft, ready for draft

#3390 governance: remove epoch multipler check
  .changelog/unreleased/improvements/3390-remove-multipler-check-governance.md
  crates/governance/src/parameters.rs
  crates/namada/src/ledger/governance/mod.rs
  crates/namada/src/ledger/native_vp/ibc/mod.rs
Labels: merged to draft, ready for draft

#3391 Parameterize gas scale
  .changelog/unreleased/improvements/3391-parameterize-gas-scale.md
  crates/apps_lib/src/config/genesis.rs
  crates/apps_lib/src/config/genesis/chain.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/core/src/parameters.rs
  crates/gas/src/lib.rs
  crates/namada/src/ledger/mod.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
  crates/node/src/storage/mod.rs
  crates/parameters/src/lib.rs
  crates/parameters/src/storage.rs
  crates/proof_of_stake/src/lib.rs
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
  crates/state/src/lib.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/data/wrapper.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: merged to draft, ready for draft

#3401 Test batch tx events
  .changelog/unreleased/testing/3401-test-batch-tx-events.md
  crates/node/src/shell/finalize_block.rs
  crates/tx/src/data/mod.rs
Labels: testing, merged to draft, ready for draft

#3410 Fix unwrapped IBC message decoding
  .changelog/unreleased/bug-fixes/3404-fix-ibc-message.md
  crates/ibc/src/lib.rs
Labels: merged to draft, ready for draft

#3412 Upgrade ledger-namada-rs to 0.0.24.
  .changelog/unreleased/improvements/3412-upgrade-ledger-namada-rs-dep.md
  Cargo.lock
  Cargo.toml
Labels: merged to draft, ready for draft

#3416 Index batched txs via their wrapper and commitment hashes
  .changelog/unreleased/improvements/3416-uniquely-identify-inner-txs.md
  Cargo.lock
  Cargo.toml
  crates/apps_lib/Cargo.toml
  crates/apps_lib/src/client/tx.rs
  crates/namada/Cargo.toml
  crates/namada/src/ledger/mod.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/node/Cargo.toml
  crates/node/src/bench_utils.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/governance.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
  crates/tx/Cargo.toml
  crates/tx/src/data/mod.rs
  crates/tx/src/lib.rs
  crates/tx/src/types.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: enhancement, UX, merged to draft, ready for draft

#3419 move masp validation from SDK into shielded_token crate
  .changelog/unreleased/improvements/3419-move-verify-shielded.md
  Cargo.lock
  Cargo.toml
  crates/encoding_spec/Cargo.toml
  crates/namada/Cargo.toml
  crates/namada/src/ledger/native_vp/masp.rs
  crates/node/src/lib.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/masp.rs
  crates/shielded_token/Cargo.toml
  crates/shielded_token/src/lib.rs
  crates/shielded_token/src/validation.rs
  crates/token/Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft, ready for draft

#3432 respect wasm-dir on init-network
  .changelog/unreleased/bug-fixes/3432-respect-wasm-dir.md
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/utils.rs
  crates/tests/src/integration/setup.rs
Labels: merged to draft, ready for draft

#3441 Fallible trait bound for queries' height param
  .changelog/unreleased/improvements/2891-sdk-query-height.md
  crates/node/src/bench_utils.rs
  crates/node/src/shell/testing/node.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/queries/mod.rs
Labels: merged to draft, ready for draft

#3442 Limit number of pgf stewards
  .changelog/unreleased/improvements/3442-limit-pgf-stewards.md
  crates/apps_lib/src/config/genesis/chain.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/governance/src/pgf/parameters.rs
  crates/governance/src/pgf/storage/keys.rs
  crates/node/src/shell/governance.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: merged to draft, ready for draft

#3443 Misc optimizations
  .changelog/unreleased/improvements/3192-opt-recomm.md
  crates/node/src/shell/governance.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/process_proposal.rs
Labels: merged to draft, ready for draft

#3365 masp e2e test
  .github/workflows/scripts/e2e.json
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
Labels: testing, merged to draft, ready for draft

#3471 Minor gov improvements
  .changelog/unreleased/improvements/3471-remove-gov-prop-id-input.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/governance/src/cli/onchain.rs
  crates/governance/src/cli/validation.rs
  crates/governance/src/pgf/inflation.rs
  crates/governance/src/pgf/mod.rs
  crates/governance/src/pgf/storage/mod.rs
  crates/governance/src/pgf/storage/steward.rs
  crates/node/src/shell/governance.rs
  crates/sdk/src/queries/vp/pgf.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/integration/ledger_tests.rs
  scripts/add_proposal_wasm_code.py
  scripts/default_proposal_template.json
  scripts/funding_proposal_template.json
  scripts/steward_proposal_template.json
Labels: merged to draft, ready for draft

#3502 Removed redundant build_pow_flag function.
  .changelog/unreleased/improvements/3502-without-pow.md
  crates/sdk/src/tx.rs
Labels: merged to draft, ready for draft

#3506 Bump tendermint-rs to 0.37
  .changelog/unreleased/improvements/3506-tendermint-0.37.md
  Cargo.lock
  Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft, ready for draft

#3516 Eliminates MASP VP's requirement for all debited accounts to sign Tx
  .changelog/unreleased/improvements/3516-reduce-masp-vp-signatures.md
  crates/namada/src/ledger/native_vp/masp.rs
Labels: merged to draft, ready for draft

#3518 sdk: add impl to shielding transfer
  .changelog/unreleased/bug-fixes/3518-sdk-builder-fix.md
  crates/sdk/src/args.rs
Labels: merged to draft, ready for draft

#3519 rename and split --memo-path of ibc-transfer
  .changelog/unreleased/improvements/3517-rename-ibc-transfer-memo-opt.md
  crates/apps_lib/src/cli.rs
  crates/ibc/src/msg.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/tx.rs
  crates/tests/src/e2e/ibc_tests.rs
Labels: merged to draft, ready for draft

#3428 Improve gas interface
  .changelog/unreleased/improvements/3428-better-gas-interface.md
  .github/workflows/scripts/hermes.txt
  crates/gas/src/event.rs
  crates/gas/src/lib.rs
  crates/light_sdk/src/reading/asynchronous/tx.rs
  crates/light_sdk/src/reading/blocking/tx.rs
  crates/namada/src/ledger/mod.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/node/src/bench_utils.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/governance.rs
  crates/node/src/shell/mod.rs
  crates/node/src/storage/mod.rs
  crates/parameters/src/lib.rs
  crates/proof_of_stake/src/lib.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
  crates/state/src/lib.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/integration/masp.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/data/wrapper.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
  scripts/get_hermes.sh
Labels: merged to draft, ready for draft

#3490 Fix IBC MASP tx extraction
  .changelog/v0.40.0/bug-fixes/3488-fix-ibc-masp-tx-extraction.md
  crates/core/src/ibc.rs
  crates/events/src/extend.rs
  crates/namada/src/ledger/mod.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/node/src/shell/finalize_block.rs
  crates/sdk/src/masp.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/types.rs
Labels: merged to draft, ready for draft

#3529 workaround wasmer leak
  .changelog/unreleased/bug-fixes/3529-leak-workaround.md
  Cargo.lock
  Cargo.toml
  crates/namada/Cargo.toml
  crates/namada/src/vm/host_env.rs
  crates/namada/src/vm/wasm/compilation_cache/common.rs
  crates/namada/src/vm/wasm/memory.rs
  crates/namada/src/vm/wasm/run.rs
  crates/tests/Cargo.toml
  crates/tests/src/vm_host_env/tx.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: ready for draft

#3543 fix possible panic in sig verification
  .changelog/unreleased/bug-fixes/3543-fix-verify-sig-panic.md
  crates/tx/src/types.rs
Labels: ready for draft

#3473 Avoid multiple calls to `process_proposal`
  .changelog/unreleased/improvements/3473-opt-validation-calls.md
  Cargo.lock
  crates/core/src/hash.rs
  crates/node/src/lib.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/prepare_proposal.rs
  crates/node/src/shell/queries.rs
  crates/node/src/shell/testing/node.rs
  crates/node/src/shell/vote_extensions/bridge_pool_vext.rs
  crates/node/src/shell/vote_extensions/eth_events.rs
  crates/node/src/shell/vote_extensions/val_set_update.rs
  crates/node/src/shims/abcipp_shim.rs
  crates/node/src/shims/abcipp_shim_types.rs
  crates/state/Cargo.toml
  crates/state/src/in_memory.rs
  crates/state/src/lib.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merged to draft, ready for draft

#3494 Murisi/expand correct test vectors
  .changelog/unreleased/improvements/3494-expand-correct-test-vectors.md
  crates/governance/src/storage/proposal.rs
  crates/governance/src/storage/vote.rs
  crates/ibc/src/lib.rs
  crates/ibc/src/msg.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/signing.rs
  crates/token/src/lib.rs
  crates/tx/src/data/pgf.rs
  examples/tx_schema.rs
  wasm/checksums.json
Labels: IBC, MASP, merged to draft, ready for draft

#3498 MASP shielded sync client phase 1
  .changelog/unreleased/improvements/3405-phase-1-shielded-sync-refactor.md
  Cargo.lock
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/masp.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/control_flow/mod.rs
  crates/sdk/src/error.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/masp/test_utils.rs
  crates/sdk/src/masp/utils.rs
  crates/sdk/src/queries/mod.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: enhancement, client, SDK, merged to draft, ready for draft

#3540 Use total active voting power in `query_proposal_result`
  .changelog/unreleased/bug-fixes/3540-fix-query-proposal-result-vp.md
  crates/governance/src/utils.rs
  crates/sdk/src/queries/vp/pos.rs
  crates/sdk/src/rpc.rs
Labels: bug, ready for draft, governance

#3557 CI: use the event head sha to check changelog
  .github/workflows/ci.yml
Labels: CI

#3559 CI/changelog: diff PR branch against origin/main
  .github/workflows/scripts/check-changelog.sh
Labels: CI, ready-for-draft

#3472 systems crate
  .changelog/unreleased/improvements/3472-systems-crate.md
  Cargo.lock
  Cargo.toml
  crates/core/src/ibc.rs
  crates/core/src/lib.rs
  crates/core/src/parameters.rs
  crates/core/src/token.rs
  crates/ethereum_bridge/Cargo.toml
  crates/ethereum_bridge/src/vp/bridge_pool_vp.rs
  crates/ethereum_bridge/src/vp/eth_bridge_vp.rs
  crates/ethereum_bridge/src/vp/nut_vp.rs
  crates/governance/Cargo.toml
  crates/governance/src/lib.rs
  crates/governance/src/vp/mod.rs
  crates/ibc/Cargo.toml
  crates/ibc/src/lib.rs
  crates/ibc/src/vp/context.rs
  crates/ibc/src/vp/mod.rs
  crates/parameters/Cargo.toml
  crates/parameters/src/lib.rs
  crates/parameters/src/vp.rs
  crates/proof_of_stake/Cargo.toml
  crates/proof_of_stake/src/lib.rs
  crates/proof_of_stake/src/vp.rs
  crates/shielded_token/Cargo.toml
  crates/shielded_token/src/vp.rs
  crates/state/Cargo.toml
  crates/state/src/lib.rs
  crates/systems/Cargo.toml
  crates/systems/src/ethereum_bridge.rs
  crates/systems/src/governance.rs
  crates/systems/src/ibc.rs
  crates/systems/src/lib.rs
  crates/systems/src/parameters.rs
  crates/systems/src/pgf.rs
  crates/systems/src/proof_of_stake.rs
  crates/systems/src/shielded_token.rs
  crates/systems/src/trans_token.rs
  crates/token/src/lib.rs
  crates/trans_token/Cargo.toml
  crates/trans_token/src/lib.rs
  crates/trans_token/src/vp.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: ready for draft, ready-for-draft

#3565 change the label to trigger PR merge to "merge"
  .mergify.yml
Labels: ready-for-draft

#3566 fix client checks on update account
  .changelog/unreleased/bug-fixes/3566-fix-update-account-client-checks.md
  crates/sdk/src/tx.rs
Labels: merge

#3547 Improve fee tracing message
  .changelog/unreleased/improvements/3547-fix-fee-log-msg.md
  crates/node/src/protocol.rs
Labels: non-breaking-change, merge
