Repository namada-net/namada, pull requests merged in 2024-12, with the labels that each got.

#4128 mergify: add apps backport rules, add prefix for libs
  .mergify.yml
Labels: CI, merge, backport-libs-0.46, backport-1.0

#4131 ci: run on maint-libs PRs
  .github/workflows/ci.yml
Labels: CI, merge, backport-libs-0.46

#4120 Fix offline wrapper signature by elsewho
  .changelog/unreleased/bug-fixes/4120-fix-offline-wrapper-sig.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/client/utils.rs
  crates/sdk/src/tx.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: breaking:cli, breaking:client, merge, backport-libs-0.46

#4127 Murisi/masp for namadillo
  .changelog/unreleased/SDK/4127-masp-for-namadillo.md
  .github/workflows/scripts/hermes.txt
  Cargo.lock
  Cargo.toml
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/cli/context.rs
  crates/apps_lib/src/cli/wallet.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/apps_lib/src/config/genesis/utils.rs
  crates/apps_lib/src/wallet/defaults.rs
  crates/benches/native_vps.rs
  crates/core/src/masp.rs
  crates/node/src/bench_utils.rs
  crates/node/src/shell/testing/client.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/shielded_token/src/validation.rs
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/integration/helpers.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  crates/token/src/lib.rs
  crates/tx/src/types.rs
  crates/wallet/src/keys.rs
  crates/wallet/src/lib.rs
  crates/wallet/src/store.rs
  genesis/hardware/src/pre-genesis/wallet.toml
  genesis/localnet/balances.toml
  genesis/localnet/src/pre-genesis/established/established-account-tx-frank.toml
  genesis/localnet/src/pre-genesis/signed-transactions.toml
  genesis/localnet/src/pre-genesis/unsigned-transactions.toml
  genesis/localnet/src/pre-genesis/wallet.toml
  genesis/localnet/transactions.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: MASP, SDK, merge

#4140 Add Ledger app unit tests to the Namada CI
  .changelog/unreleased/CI/4140-ledger-namada-unit-tests-ci.md
  .github/workflows/ci.yml
  crates/ibc/src/lib.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/signing.rs
Labels: testing, CI, merge

#4155 ci/test-ledger-app: specify container image
  .github/workflows/ci.yml
Labels: CI, merge

#4160 ci/test-ledger-app: undo previous changes and run on ubuntu image
  .github/workflows/ci.yml
Labels: CI, merge

#4166 backport 4155, 4157 and 4160
  .changelog/unreleased/SDK/4127-masp-for-namadillo.md
  .changelog/v1.0.0/miscellaneous/4123-apps-pre-release.md
  .changelog/v1.0.0/summary.md
  .github/workflows/ci.yml
  .github/workflows/scripts/hermes.txt
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/apps/Cargo.toml
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/cli/context.rs
  crates/apps_lib/src/cli/wallet.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/apps_lib/src/config/genesis/utils.rs
  crates/apps_lib/src/wallet/defaults.rs
  crates/benches/native_vps.rs
  crates/core/src/masp.rs
  crates/node/src/bench_utils.rs
  crates/node/src/shell/testing/client.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/shielded_token/src/validation.rs
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/integration/helpers.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  crates/token/src/lib.rs
  crates/tx/src/types.rs
  crates/wallet/src/keys.rs
  crates/wallet/src/lib.rs
  crates/wallet/src/store.rs
  genesis/hardware/src/pre-genesis/wallet.toml
  genesis/localnet/balances.toml
  genesis/localnet/src/pre-genesis/established/established-account-tx-frank.toml
  genesis/localnet/src/pre-genesis/signed-transactions.toml
  genesis/localnet/src/pre-genesis/unsigned-transactions.toml
  genesis/localnet/src/pre-genesis/wallet.toml
  genesis/localnet/transactions.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merge

#4144 deps: switch to released clru version
  Cargo.lock
  Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: dependencies, non-breaking-change, merge, backport-libs-0.46

#4153 deps: Switch to released tower-abci
  Cargo.lock
  Cargo.toml
Labels: merge, backport-libs-0.46

#4148 Update README.md
  CODE_OF_CONDUCT.md
  README.md
  examples/README.md
  fuzz/README.md
  genesis/README.md
Labels: merge

#4154 test/ibc: ensure unique token IDs
  crates/ibc/src/lib.rs
Labels: testing, merge, backport-libs-0.46

#4177 inline the borsh-ext fn in core
  .changelog/unreleased/miscellaneous/4177-inline-borsh-ext.md
  Cargo.lock
  crates/apps_lib/Cargo.toml
  crates/apps_lib/src/cli/wallet.rs
  crates/apps_lib/src/client/rpc.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/config/genesis.rs
  crates/apps_lib/src/config/genesis/chain.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/apps_lib/src/tendermint_node.rs
  crates/benches/Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/address.rs
  crates/core/src/borsh.rs
  crates/core/src/eth_bridge_pool.rs
  crates/core/src/ethereum_events.rs
  crates/core/src/key/common.rs
  crates/core/src/key/ed25519.rs
  crates/core/src/key/mod.rs
  crates/core/src/key/secp256k1.rs
  crates/core/src/lib.rs
  crates/core/src/masp.rs
  crates/core/src/mod.rs
  crates/light_sdk/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/bench_utils.rs
  crates/node/src/dry_run_tx.rs
  crates/node/src/ethereum_oracle/test_tools/events_endpoint.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/snapshots.rs
  crates/node/src/shell/testing/node.rs
  crates/node/src/storage/mod.rs
  crates/node/src/storage/rocksdb.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/eth_bridge/bridge_pool.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/migrations.rs
  crates/sdk/src/queries/mod.rs
  crates/sdk/src/queries/router.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/queries/shell/eth_bridge.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tests/Cargo.toml
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/native_vp/eth_bridge_pool.rs
  crates/tests/src/vm_host_env/mod.rs
  crates/wallet/Cargo.toml
  crates/wallet/src/keys.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: backport-libs-0.46

#4190 switch to published usize-set (previously index-set)
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/storage.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: dependencies, merge, backport-libs-0.46

#4195 deps: use published ethbridge crates
  Cargo.lock
  Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: dependencies, merge, backport-libs-0.46

#4142 Fix unbonding period for IBC client
  .changelog/unreleased/bug-fixes/4142-ibc-unbonding-period.md
  .github/workflows/scripts/hermes.txt
  crates/ibc/src/vp/mod.rs
  crates/proof_of_stake/src/lib.rs
  crates/systems/src/proof_of_stake.rs
Labels: breaking: protocol, merge

#4126 Fraccaman/rpc pgf payments
  .changelog/unreleased/improvements/4126-rpc-pgf-payments.md
  crates/sdk/src/rpc.rs
Labels: SDK, merge

#4205 Improve `namadac next-epoch-info`
  .changelog/unreleased/improvements/4205-improve-next-epoch-info.md
  crates/apps_lib/src/client/rpc.rs
  crates/core/src/time.rs
  crates/sdk/src/rpc.rs
Labels: client, SDK, merge

#4146 Fix masp rewards estimate
  .changelog/unreleased/bug-fixes/4146-fix-masp-rewards-estimate.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/rpc.rs
  crates/sdk/src/args.rs
  crates/shielded_token/src/conversion.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/tests/src/integration/masp.rs
Labels: MASP, breaking:cli, merge, breaking:SDK
