Repository namada-net/namada, pull requests merged in 2024-04, with the labels that each got.

#3037 sdk: refactor `change_consensus_key`
  .changelog/unreleased/sdk/3037-sdk-change-consensus-keys.md
  crates/apps/src/lib/cli/client.rs
  crates/apps/src/lib/client/tx.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/tx.rs
Labels: merged to draft

#3039 sdk: improve update_account
  .changelog/unreleased/sdk/3039-sdk-update-account.md
  crates/sdk/src/lib.rs
Labels: merged to draft

#2735 Fix temporary values read
  .changelog/unreleased/bug-fixes/2735-fix-vps-api.md
  crates/namada/src/ledger/vp_host_fns.rs
  crates/namada/src/vm/host_env.rs
  crates/namada/src/vm/wasm/run.rs
  crates/state/src/lib.rs
  crates/state/src/write_log.rs
Labels: merged to draft, ready for draft, breaking-change

#2845 Limit metadata size
  .changelog/unreleased/improvements/2845-limit-metadata-size.md
  crates/apps/src/lib/config/genesis/transactions.rs
  crates/proof_of_stake/src/parameters.rs
  crates/sdk/src/error.rs
  crates/sdk/src/tx.rs
  wasm/wasm_source/src/vp_user.rs
Labels: merged to draft

#2846 Add a param to enable/disable nam transfers
  .changelog/unreleased/features/2842-nam-transferable.md
  crates/apps/src/lib/config/genesis/chain.rs
  crates/apps/src/lib/config/genesis/templates.rs
  crates/apps/src/lib/node/ledger/storage/mod.rs
  crates/core/src/parameters.rs
  crates/namada/Cargo.toml
  crates/namada/src/ledger/native_vp/multitoken.rs
  crates/parameters/Cargo.toml
  crates/parameters/src/lib.rs
  crates/parameters/src/storage.rs
  crates/proof_of_stake/src/lib.rs
  crates/shielded_token/Cargo.toml
  crates/shielded_token/src/conversion.rs
  crates/state/src/lib.rs
  crates/tests/src/vm_host_env/ibc.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: merged to draft, ready for draft

#2848 IBC tx - simplify storage iter prefix
  .changelog/unreleased/bug-fixes/2848-ibc-tx-simplify.md
  crates/ibc/src/actions.rs
  crates/ibc/src/lib.rs
  crates/namada/src/vm/host_env.rs
Labels: merged to draft, breaking-change

#2852 Always use storage errors on native VPs
  .changelog/unreleased/improvements/2852-vps-use-storage-err.md
  crates/ethereum_bridge/src/storage/parameters.rs
  crates/namada/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
  crates/namada/src/ledger/native_vp/ethereum_bridge/nut.rs
  crates/namada/src/ledger/native_vp/ethereum_bridge/vp.rs
  crates/namada/src/ledger/native_vp/mod.rs
  crates/storage/src/error.rs
Labels: merged to draft, ready for draft, non-breaking-change

#2928 only trigger VPs from a fst addr of a key segment
  .changelog/unreleased/bug-fixes/2928-fst-addr-vps.md
  crates/apps/src/lib/bench_utils.rs
  crates/benches/native_vps.rs
  crates/benches/vps.rs
  crates/core/src/storage.rs
  crates/state/src/write_log.rs
  crates/tx_prelude/src/proof_of_stake.rs
  crates/tx_prelude/src/token.rs
  wasm/wasm_source/src/tx_init_proposal.rs
  wasm/wasm_source/src/tx_resign_steward.rs
  wasm/wasm_source/src/tx_update_account.rs
  wasm/wasm_source/src/tx_update_steward_commission.rs
  wasm/wasm_source/src/tx_vote_proposal.rs
Labels: merged to draft

#2932 Remove the superfluous addition of .0 to Ledger test vectors.
  .changelog/unreleased/improvements/2932-fix-ledger-significant-digits.md
  crates/sdk/src/signing.rs
Labels: merged to draft, non-breaking-change

#2933 Migrated many e2e tests to integration tests
  .changelog/unreleased/improvements/2933-migrated-e2e-to-int.md
  .github/workflows/scripts/e2e.json
  Cargo.lock
  crates/apps/src/lib/client/tx.rs
  crates/apps/src/lib/node/ledger/mod.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/testing/node.rs
  crates/apps/src/lib/node/ledger/shell/testing/utils.rs
  crates/apps/src/lib/node/ledger/shims/abcipp_shim_types.rs
  crates/core/src/address.rs
  crates/proof_of_stake/src/rewards.rs
  crates/proof_of_stake/src/tests/test_pos.rs
  crates/tests/Cargo.toml
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/integration.rs
  crates/tests/src/integration/helpers.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  crates/tests/src/integration/setup.rs
  crates/tx/src/data/mod.rs
  genesis/localnet/balances.toml
Labels: merged to draft

#2952 add become_validator to sdk
  Cargo.lock
  crates/account/src/lib.rs
  crates/apps/src/lib/client/tx.rs
  crates/sdk/src/args.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/tx.rs
Labels: merged to draft, ready for draft, non-breaking-change

#2964 fix non-persisted diffs
  .changelog/unreleased/bug-fixes/2964-fix-non-persisted-diffs.md
  crates/apps/src/lib/node/ledger/storage/mod.rs
  crates/apps/src/lib/node/ledger/storage/rocksdb.rs
  crates/core/src/storage.rs
  crates/state/src/wl_state.rs
  crates/storage/src/db.rs
  crates/storage/src/mockdb.rs
Labels: merged to draft

#3002 Remove PGF balance from total native supply
  .changelog/unreleased/improvements/3002-remove-from-total-supply.md
  crates/governance/src/pgf/inflation.rs
  crates/proof_of_stake/src/rewards.rs
  crates/proof_of_stake/src/tests/test_pos.rs
  crates/sdk/src/queries/vp/token.rs
  crates/shielded_token/src/conversion.rs
  crates/trans_token/src/storage.rs
Labels: merged to draft, ready for draft

#3023 test/e2e/init_validator: restart new validator node right after its tx
  crates/tests/src/e2e/ledger_tests.rs
Labels: testing, merged to draft

#2621 Fix nullifiers check
  .changelog/unreleased/bug-fixes/2621-fix-nullifier-check.md
  crates/namada/src/ledger/native_vp/masp.rs
Labels: merged to draft, ready for draft, breaking-change

#2790 Fix how masp tx's are identified
  .changelog/unreleased/bug-fixes/2790-fix-masp-tx-identification.md
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/shielded_token/src/utils.rs
Labels: merged to draft, ready for draft

#2840 Fix ibc-transfer dry-run
  .changelog/unreleased/bug-fixes/2730-fix-ibc-transfer-dry-run.md
  crates/ibc/src/context/common.rs
Labels: merged to draft, ready for draft

#2861 Cleanup from auditing abci shims
  .changelog/unreleased/improvements/2861-shim-audit.md
  crates/apps/src/lib/node/ledger/shims/abcipp_shim.rs
  crates/apps/src/lib/node/ledger/shims/abcipp_shim_types.rs
Labels: merged to draft, ready for draft

#2956 Replay protection refactor
  .changelog/unreleased/improvements/2956-refactor-reprot.md
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs
  crates/apps/src/lib/node/ledger/shell/process_proposal.rs
  crates/apps/src/lib/node/ledger/storage/rocksdb.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/replay_protection/src/lib.rs
  crates/state/src/wl_state.rs
  crates/state/src/write_log.rs
  crates/storage/src/db.rs
  crates/storage/src/mockdb.rs
Labels: merged to draft, ready for draft

#3031 Various small PoS improvements
  .changelog/unreleased/improvements/3031-various-pos.md
  README.md
  crates/apps/src/lib/bench_utils.rs
  crates/apps/src/lib/client/rpc.rs
  crates/apps/src/lib/node/ledger/shell/governance.rs
  crates/governance/src/storage/keys.rs
  crates/governance/src/utils.rs
  crates/light_sdk/src/reading/asynchronous/pos.rs
  crates/proof_of_stake/src/types/mod.rs
  crates/sdk/src/queries/vp/pos.rs
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
Labels: client, merged to draft, ready for draft

#3087 fix governance proposal execution
  .changelog/unreleased/improvements/3087-fix-governance-proposal-execution.md
  crates/apps/src/lib/client/rpc.rs
  crates/apps/src/lib/node/ledger/shell/governance.rs
  crates/governance/src/storage/proposal.rs
  crates/namada/src/ledger/governance/mod.rs
Labels: merged to draft, ready for draft, governance

#3092 Fix denom in PGF over IBC
  .changelog/unreleased/bug-fixes/3085-fix-pgf-ibc-denom.md
  crates/ibc/src/actions.rs
  crates/tests/src/e2e/ibc_tests.rs
Labels: merged to draft, ready for draft

#3093 Improve UX of validator's address
  .changelog/unreleased/improvements/3093-validator-addresses-ux.md
  crates/apps/src/lib/client/tx.rs
  crates/apps/src/lib/client/utils.rs
  crates/apps/src/lib/config/genesis/chain.rs
  crates/sdk/src/wallet/alias.rs
  crates/sdk/src/wallet/store.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/integration/ledger_tests.rs
  wasm/checksums.json
Labels: merged to draft, ready for draft

#3107 Governance: add `latency` to genesis parameters
  .changelog/unreleased/improvements/3107-governance-latency.md
  crates/apps/src/lib/config/genesis/chain.rs
  crates/apps/src/lib/config/genesis/templates.rs
  crates/governance/src/parameters.rs
  crates/governance/src/pgf/storage/steward.rs
  crates/governance/src/storage/keys.rs
  crates/governance/src/storage/mod.rs
  crates/namada/src/ledger/governance/mod.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: merged to draft, breaking:genesis, ready for draft

#3108 Common default gas limit
  .changelog/unreleased/improvements/2981-default-gas-limit.md
  crates/apps/src/lib/cli.rs
  crates/apps/src/lib/config/genesis/transactions.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs
  crates/sdk/src/lib.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/data/wrapper.rs
Labels: merged to draft, ready for draft

#3110 state/write_log: refactor temp key-vals for better type-safety
  .changelog/unreleased/improvements/3110-write-log-t-safety.md
  crates/namada/src/ledger/native_vp/ibc/context.rs
  crates/namada/src/ledger/vp_host_fns.rs
  crates/namada/src/vm/host_env.rs
  crates/state/src/lib.rs
  crates/state/src/wl_state.rs
  crates/state/src/write_log.rs
Labels: merged to draft, ready for draft

#3117 Borsh serialization
  .changelog/unreleased/improvements/2868-borsh-serialize.md
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/init_chain.rs
  crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs
  crates/apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs
  crates/benches/txs.rs
  crates/ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs
  crates/ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
  crates/ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  crates/ethereum_bridge/src/protocol/transactions/read.rs
  crates/ethereum_bridge/src/protocol/transactions/update.rs
  crates/ethereum_bridge/src/protocol/transactions/votes/storage.rs
  crates/ethereum_bridge/src/storage/eth_bridge_queries.rs
  crates/ethereum_bridge/src/storage/parameters.rs
  crates/governance/src/storage/mod.rs
  crates/namada/src/ledger/governance/mod.rs
  crates/namada/src/ledger/mod.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/namada/src/vm/wasm/run.rs
  crates/parameters/src/lib.rs
  crates/tests/src/vm_host_env/mod.rs
Labels: merged to draft, ready for draft

#3121 remove `show-transfer`
  .changelog/unreleased/miscellaneous/3121-remove-show-transfer.md
  crates/apps/src/lib/cli.rs
  crates/apps/src/lib/cli/client.rs
  crates/apps/src/lib/client/rpc.rs
Labels: merged to draft, ready for draft

#3122 Adjusted test vector printing to simplify hardware wallet implementations
  .changelog/unreleased/improvements/3122-test-vectors-0.33.0.md
  crates/governance/src/storage/proposal.rs
  crates/sdk/src/signing.rs
Labels: merged to draft, ready for draft

#3123 Default tx expiration
  .changelog/unreleased/improvements/3123-default-tx-expiration.md
  crates/apps/src/lib/cli.rs
  crates/apps/src/lib/config/genesis/transactions.rs
  crates/sdk/src/args.rs
  crates/sdk/src/eth_bridge/bridge_pool.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/tx.rs
Labels: merged to draft, ready for draft

#3124 `GasLimit` cleanup
  .changelog/unreleased/improvements/2620-clean-gas-limit.md
  crates/tx/src/data/wrapper.rs
Labels: merged to draft, ready for draft, breaking: tx format

#3125 Merklize commitment tree anchor keys
  .changelog/unreleased/improvements/2794-merkle-masp-hashes.md
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/shielded_token/src/storage_key.rs
Labels: merged to draft, ready for draft, breaking: protocol

#3130 Keep generated dates in the current era so that parsing RFC 3339 works.
  .changelog/unreleased/bug-fixes/3130-gen-in-current-era.md
  crates/sdk/src/lib.rs
Labels: merged to draft, ready for draft

#3137 deps: switch back to upstream tower-abci v0.11.1
  .changelog/unreleased/miscellaneous/3137-tower-abci-upstream.md
  Cargo.lock
  Cargo.toml
Labels: merged to draft, ready for draft

#2413 No float `epoch_length` in localnet script
  scripts/gen_localnet.py
Labels: ready for draft
