Repository namada-net/namada, pull requests merged in 2024-01, with the labels that each got.

#2221 PoS SM fixes
  proof_of_stake/src/parameters.rs
  proof_of_stake/src/tests/state_machine.rs
  proof_of_stake/src/tests/state_machine_v2.rs
Labels: testing

#1797 Add IBC E2E test with Hermes
  .changelog/unreleased/testing/773-ibc-e2e-hermes.md
  .github/workflows/scripts/e2e.json
  .github/workflows/scripts/schedule-e2e.py
  tests/src/e2e/helpers.rs
  tests/src/e2e/ibc_tests.rs
  tests/src/e2e/setup.rs
Labels: merged to draft

#2289 Move Ethereum bridge components from `apps` to their own crate
  .changelog/v0.29.0/improvements/2289-ethbridge-move-from-apps.md
  Cargo.lock
  apps/src/lib/node/ledger/shell/mod.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  apps/src/lib/node/ledger/shell/vote_extensions.rs
  apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs
  apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs
  apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs
  ethereum_bridge/Cargo.toml
  ethereum_bridge/src/protocol/mod.rs
  ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs
  ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
  ethereum_bridge/src/protocol/transactions/validator_set_update/mod.rs
  ethereum_bridge/src/protocol/validation.rs
  ethereum_bridge/src/protocol/validation/bridge_pool_roots.rs
  ethereum_bridge/src/protocol/validation/ethereum_events.rs
  ethereum_bridge/src/protocol/validation/validator_set_update.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: ethereum-bridge, merged to draft, ready for draft, modularization

#2330 Governance queries improvements
  .changelog/unreleased/SDK/2330-governance-tests.md
  .changelog/unreleased/improvements/2330-governance-tests.md
  apps/src/lib/cli.rs
  apps/src/lib/cli/client.rs
  apps/src/lib/client/rpc.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/node/ledger/shell/finalize_block.rs
  benches/native_vps.rs
  benches/txs.rs
  benches/vps.rs
  core/src/ledger/governance/cli/offline.rs
  core/src/ledger/governance/cli/onchain.rs
  core/src/ledger/governance/storage/vote.rs
  core/src/ledger/governance/utils.rs
  core/src/ledger/storage_api/governance.rs
  core/src/types/transaction/governance.rs
  light_sdk/src/transaction/governance.rs
  sdk/src/args.rs
  sdk/src/queries/vp/governance.rs
  sdk/src/signing.rs
  sdk/src/tx.rs
  shared/src/ledger/governance/mod.rs
  tests/src/e2e/ledger_tests.rs
Labels: merged to draft, ready for draft

#2345 MASP vp panics
  .changelog/unreleased/SDK/2345-masp-vp-panics.md
  .changelog/unreleased/improvements/2345-masp-vp-panics.md
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/init_chain.rs
  benches/native_vps.rs
  core/src/ledger/masp_conversions.rs
  core/src/ledger/masp_utils.rs
  core/src/types/token.rs
  sdk/src/masp.rs
  shared/src/ledger/native_vp/masp.rs
Labels: merged to draft, ready for draft

#2356 Fix querying error while checking token balance
  .changelog/unreleased/bug-fixes/1910-fix-tok-bal-query-errs.md
  apps/src/lib/client/rpc.rs
Labels: merged to draft, ready for draft

#2358 Extend transactions with memo sections
  .changelog/unreleased/SDK/2358-tx-memo-field.md
  .changelog/unreleased/improvements/2358-tx-memo-field.md
  apps/src/lib/cli.rs
  apps/src/lib/config/genesis/transactions.rs
  core/src/proto/mod.rs
  core/src/proto/types.rs
  genesis/localnet/src/pre-genesis/signed-transactions.toml
  genesis/localnet/src/pre-genesis/validator-0/signed-transactions.toml
  genesis/localnet/transactions.toml
  sdk/src/args.rs
  sdk/src/eth_bridge/bridge_pool.rs
  sdk/src/lib.rs
  sdk/src/tx.rs
  wasm_for_tests/tx_fail.wasm
  wasm_for_tests/tx_memory_limit.wasm
  wasm_for_tests/tx_mint_tokens.wasm
  wasm_for_tests/tx_no_op.wasm
  wasm_for_tests/tx_proposal_code.wasm
  wasm_for_tests/tx_read_storage_key.wasm
  wasm_for_tests/tx_write.wasm
  wasm_for_tests/tx_write_storage_key.wasm
  wasm_for_tests/vp_always_false.wasm
  wasm_for_tests/vp_always_true.wasm
  wasm_for_tests/vp_eval.wasm
  wasm_for_tests/vp_memory_limit.wasm
  wasm_for_tests/vp_read_storage_key.wasm
Labels: enhancement, cli, SDK, merged to draft, ready for draft

#2359 Include validator avatar in their medatada
  .changelog/unreleased/improvements/2359-validator-avatar.md
  apps/src/lib/cli.rs
  apps/src/lib/client/rpc.rs
  apps/src/lib/client/tx.rs
  apps/src/lib/client/utils.rs
  apps/src/lib/config/genesis.rs
  apps/src/lib/config/genesis/transactions.rs
  benches/txs.rs
  core/src/types/transaction/pos.rs
  genesis/localnet/src/pre-genesis/validator-0/signed-transactions.toml
  genesis/localnet/transactions.toml
  light_sdk/src/transaction/pos.rs
  proof_of_stake/src/lib.rs
  proof_of_stake/src/storage.rs
  proof_of_stake/src/storage_key.rs
  proof_of_stake/src/types/mod.rs
  sdk/src/args.rs
  sdk/src/lib.rs
  sdk/src/queries/vp/pos.rs
  sdk/src/tx.rs
  tx_prelude/src/proof_of_stake.rs
  wasm/wasm_source/src/tx_change_validator_metadata.rs
  wasm/wasm_source/src/vp_user.rs
Labels: enhancement

#2368 look-up validator by native address and query consensus key
  .changelog/unreleased/improvements/2368-lookup-validator-consensus-key.md
  apps/src/lib/cli.rs
  apps/src/lib/client/rpc.rs
  proof_of_stake/src/storage.rs
  sdk/src/args.rs
  sdk/src/queries/vp/pos.rs
  sdk/src/rpc.rs
Labels: merged to draft, ready for draft

#2372 Light sdk dependencies cleanup
  .changelog/unreleased/SDK/2372-light-sdk-deps.md
  Cargo.lock
  Makefile
  light_sdk/Cargo.toml
Labels: merged to draft, ready for draft

#2374 Fix bond amount for addresses
  .changelog/unreleased/improvements/2374-fix-bond-amount.md
  proof_of_stake/src/lib.rs
Labels: merged to draft, ready for draft

#2375 MASP vp expiration
  .changelog/unreleased/improvements/2375-masp-vp-expiration.md
  shared/src/ledger/native_vp/masp.rs
Labels: merged to draft, ready for draft

#2376 Removes the hardcoded masp sentinel key
  .changelog/unreleased/SDK/2376-remove-masp-key.md
  .changelog/unreleased/improvements/2376-remove-masp-key.md
  core/src/types/address.rs
  sdk/src/signing.rs
Labels: merged to draft, ready for draft

#2377 Governance misc refactors
  .changelog/unreleased/improvements/2377-governance-cleanup.md
  core/src/ledger/governance/utils.rs
Labels: merged to draft, ready for draft

#2384 Wasmer alignment fixes
  .changelog/unreleased/bug-fixes/2384-wasmer-alignment-fixes.md
  Cargo.lock
  shared/Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: bug, merged to draft, ready for draft

#2382 Fee validation refactor
  .changelog/unreleased/improvements/2382-fee-refactor.md
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs
  crates/apps/src/lib/node/ledger/shell/process_proposal.rs
Labels: merged to draft

#2383 Mandatory CometBFT timestamp
  .changelog/unreleased/improvements/2383-comet-timestamp.md
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/process_proposal.rs
  crates/apps/src/lib/node/ledger/shell/testing/node.rs
Labels: merged to draft, ready for draft

#2395 Sets gas sentinel in `ibc_tx_charge_gas`
  .changelog/unreleased/improvements/2395-gas-sentinel-fix.md
  crates/namada/src/vm/host_env.rs
Labels: merged to draft, ready for draft

#2398 Fix E2E test for PGF over IBC by waiting before the balance check
  .changelog/unreleased/testing/2398-fix-e2e-pgf-ibc.md
  crates/tests/src/e2e/ibc_tests.rs
Labels: ready for draft

#2400 sdk: more rpc
  .changelog/unreleased/SDK/2400-sdk-rpc-queries.md
  crates/apps/src/lib/client/rpc.rs
  crates/governance/src/storage/mod.rs
  crates/governance/src/utils.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/queries/vp/governance.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
Labels: merged to draft

#2380 fix fst epoch start height in apps tests
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/shell/queries.rs
  crates/state/src/wl_storage.rs
Labels: testing, merged to draft

#2399 Async light SDK
  .changelog/unreleased/SDK/2399-async-light-sdk.md
  Cargo.lock
  crates/light_sdk/Cargo.toml
  crates/light_sdk/src/lib.rs
  crates/light_sdk/src/reading/asynchronous/account.rs
  crates/light_sdk/src/reading/asynchronous/governance.rs
  crates/light_sdk/src/reading/asynchronous/mod.rs
  crates/light_sdk/src/reading/asynchronous/pgf.rs
  crates/light_sdk/src/reading/asynchronous/pos.rs
  crates/light_sdk/src/reading/asynchronous/tx.rs
  crates/light_sdk/src/reading/blocking/account.rs
  crates/light_sdk/src/reading/blocking/governance.rs
  crates/light_sdk/src/reading/blocking/mod.rs
  crates/light_sdk/src/reading/blocking/pgf.rs
  crates/light_sdk/src/reading/blocking/pos.rs
  crates/light_sdk/src/reading/blocking/tx.rs
  crates/light_sdk/src/reading/mod.rs
  crates/light_sdk/src/transaction/account.rs
  crates/light_sdk/src/transaction/bridge.rs
  crates/light_sdk/src/transaction/governance.rs
  crates/light_sdk/src/transaction/ibc.rs
  crates/light_sdk/src/transaction/mod.rs
  crates/light_sdk/src/transaction/pgf.rs
  crates/light_sdk/src/transaction/pos.rs
  crates/light_sdk/src/transaction/transfer.rs
  crates/light_sdk/src/writing/asynchronous/mod.rs
  crates/light_sdk/src/writing/blocking/mod.rs
  crates/light_sdk/src/writing/mod.rs
Labels: merged to draft, ready for draft

#2401 tx host env panics fixes
  .changelog/unreleased/bug-fixes/2401-tx-host-env.md
  Cargo.lock
  crates/namada/src/ledger/vp_host_fns.rs
  crates/namada/src/vm/host_env.rs
  crates/namada/src/vm/wasm/compilation_cache/common.rs
  crates/namada/src/vm/wasm/memory.rs
  crates/tests/Cargo.toml
  crates/tests/src/vm_host_env/tx.rs
Labels: merged to draft

#2415 Fix governance tally
  .changelog/unreleased/bug-fixes/2415-governance-tally.md
  crates/apps/src/lib/node/ledger/ethereum_oracle/mod.rs
  crates/apps/src/lib/node/ledger/shell/governance.rs
  crates/governance/src/storage/mod.rs
  crates/governance/src/utils.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
  crates/tests/src/e2e/ledger_tests.rs
Labels: merged to draft

#2417 Integrate ZIP32 functionality for MASP keys
  .changelog/unreleased/features/2417-wallet-zip32-0.30.1.md
  crates/apps/src/lib/cli.rs
  crates/apps/src/lib/cli/wallet.rs
  crates/apps/src/lib/client/tx.rs
  crates/apps/src/lib/wallet/mod.rs
  crates/sdk/src/args.rs
  crates/sdk/src/wallet/derivation_path.rs
  crates/sdk/src/wallet/mod.rs
  crates/sdk/src/wallet/store.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/e2e/wallet_tests.rs
  crates/tests/src/strings.rs
Labels: wallet, merged to draft

#2419 protocol tx and VP code allowlist
  .changelog/unreleased/improvements/2419-protocol-tx-allowlist.md
  crates/apps/src/lib/client/rpc.rs
  crates/apps/src/lib/config/genesis.rs
  crates/apps/src/lib/config/genesis/chain.rs
  crates/apps/src/lib/config/genesis/templates.rs
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/init_chain.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/storage/mod.rs
  crates/benches/Cargo.toml
  crates/benches/README.md
  crates/benches/txs.rs
  crates/benches/vps.rs
  crates/core/src/types/parameters.rs
  crates/namada/src/ledger/protocol/mod.rs
  crates/namada/src/vm/host_env.rs
  crates/parameters/src/lib.rs
  crates/parameters/src/storage.rs
  crates/parameters/src/wasm_allowlist.rs
  crates/shielded_token/src/conversion.rs
  crates/state/src/lib.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tests/src/vm_host_env/mod.rs
  crates/tests/src/vm_host_env/tx.rs
  crates/vp_prelude/src/lib.rs
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
  wasm/wasm_source/src/vp_implicit.rs
  wasm/wasm_source/src/vp_testnet_faucet.rs
  wasm/wasm_source/src/vp_user.rs
  wasm_for_tests/wasm_source/src/lib.rs
Labels: merged to draft

#2428 Validate balance in masp vp
  .changelog/unreleased/bug-fixes/2428-fix-shielded-actions.md
  crates/namada/src/ledger/native_vp/masp.rs
  crates/sdk/src/tx.rs
Labels: merged to draft, ready for draft

#2432 Adjust MASP inflation param values
  crates/tests/src/integration/setup.rs
  genesis/localnet/tokens.toml
  genesis/starter/tokens.toml
Labels: merged to draft

#2435 enable rocksdb jemalloc only for make build-release
  .changelog/unreleased/improvements/2435-opt-jemalloc.md
  Makefile
  crates/apps/Cargo.toml
  crates/apps/src/lib/mod.rs
  crates/apps/src/lib/node/ledger/mod.rs
  crates/apps/src/lib/node/ledger/shims/abcipp_shim.rs
  crates/apps/src/lib/node/ledger/storage/rocksdb.rs
Labels: merged to draft

#2438 New Storage Write API REDO
  .changelog/unreleased/improvements/2438-new-storage-write.md
  crates/apps/src/lib/node/ledger/shell/finalize_block.rs
  crates/apps/src/lib/node/ledger/shell/init_chain.rs
  crates/apps/src/lib/node/ledger/shell/mod.rs
  crates/apps/src/lib/node/ledger/storage/mod.rs
  crates/apps/src/lib/node/ledger/storage/rocksdb.rs
  crates/benches/host_env.rs
  crates/ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
  crates/ethereum_bridge/src/protocol/transactions/read.rs
  crates/ethereum_bridge/src/protocol/transactions/update.rs
  crates/ethereum_bridge/src/protocol/transactions/votes/storage.rs
  crates/ethereum_bridge/src/storage/parameters.rs
  crates/ethereum_bridge/src/storage/vp/ethereum_bridge.rs
  crates/ibc/src/storage.rs
  crates/namada/src/ledger/ibc/mod.rs
  crates/namada/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
  crates/namada/src/ledger/native_vp/ethereum_bridge/vp.rs
  crates/parameters/src/lib.rs
  crates/sdk/src/queries/shell/eth_bridge.rs
  crates/state/src/lib.rs
  crates/state/src/write_log.rs
  crates/storage/src/db.rs
  crates/storage/src/lib.rs
  crates/storage/src/mockdb.rs
  wasm/wasm_source/src/tx_bridge_pool.rs
Labels: merged to draft

#2440 pgf: added reward distribution limit for stewards
  .changelog/unreleased/bug-fixes/2440-pgf-minors.md
  .github/workflows/scripts/e2e.json
  crates/governance/src/pgf/cli/steward.rs
  crates/governance/src/pgf/mod.rs
  crates/governance/src/pgf/storage/steward.rs
  crates/namada/src/ledger/pgf/mod.rs
  crates/tests/src/e2e/ledger_tests.rs
Labels: merged to draft

#2454 test/tx_redelegate: prevent redelegation delegator from being validator
  wasm/wasm_source/src/tx_redelegate.rs
Labels: testing

#2471 genesis: use the configured native token name for validation
  .changelog/unreleased/bug-fixes/2471-genesis-native-token.md
  crates/apps/src/lib/config/genesis/templates.rs
  crates/core/src/types/token.rs
  genesis/starter/balances.toml
Labels: merged to draft

#2473 Fix empty password panic; unify `list` and `find` commands output
  .changelog/unreleased/bug-fixes/2473-wallet-fix-empty-password-panic.md
  crates/apps/src/lib/cli/wallet.rs
  crates/sdk/src/wallet/keys.rs
Labels: wallet, merged to draft

#2476 `I128Sum` checked ops
  .changelog/unreleased/improvements/2476-masp-checked-ops.md
  Cargo.lock
  Cargo.toml
  crates/namada/Cargo.toml
  crates/namada/src/ledger/native_vp/masp.rs
  wasm/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: ready for draft
