Repository namada-net/namada, pull requests merged in 2024-09, with the labels that each got.

#3741 Dynamic ledger managed tasks
  .changelog/unreleased/improvements/3741-run-aux-arbitrary-tasks.md
  crates/node/src/abortable.rs
  crates/node/src/ethereum_oracle/mod.rs
  crates/node/src/lib.rs
Labels: enhancement, ledger, merge

#3742 include wasm tests in code cov
  .github/workflows/ci.yml
  Makefile
  wasm/Makefile
Labels: CI, merge

#3752 Don't build namadar
  .changelog/unreleased/improvements/3752-dont-build-namadar.md
  crates/apps/Cargo.toml
  crates/apps/src/bin/namada-relayer/_main.rs
Labels: merge

#3756 fix next epoch
  crates/node/src/shell/testing/node.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
Labels: testing, merge

#3745 use test-dir for network archive to avoid re-compilations after test run
  crates/apps_lib/build.rs
  crates/tests/src/integration/setup.rs
Labels: testing, merge

#3718 mv gov sub-module from shell into gov crate
  .changelog/unreleased/improvements/3718-gov-refactor.md
  Cargo.lock
  crates/governance/src/finalize_block.rs
  crates/governance/src/lib.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/governance.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/utils.rs
  crates/proof_of_stake/src/lib.rs
  crates/proof_of_stake/src/storage.rs
  crates/sdk/src/queries/vp/pos.rs
  crates/systems/Cargo.toml
  crates/systems/src/proof_of_stake.rs
  crates/systems/src/trans_token.rs
  crates/trans_token/src/lib.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merge

#3751 set cometbft to 0.37.11
  .changelog/unreleased/improvements/3751-upgrade-cometbft-0.37.11.md
  Dockerfile
  README.md
Labels: merge

#3757 Improve custom tx error and help msg
  .changelog/unreleased/improvements/3757-better-custom-tx-error.md
  crates/apps_lib/src/cli.rs
  crates/sdk/src/tx.rs
Labels: merge

#3715 improve offline tx handling
  .changelog/unreleased/improvements/3715-improve-offline-tx-handling.md
  .github/workflows/scripts/e2e.json
  Cargo.lock
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/tx.rs
  crates/apps_lib/src/client/utils.rs
  crates/core/src/hash.rs
  crates/core/src/key/common.rs
  crates/core/src/key/secp256k1.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/integration/helpers.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tx/src/lib.rs
  crates/tx/src/sign.rs
  crates/tx/src/types.rs
Labels: merge

#3735 Update tendermint-rs to v0.38
  .changelog/unreleased/improvements/3735-update-tendermint-rs.md
  Cargo.lock
  Cargo.toml
  crates/ibc/src/actions.rs
  crates/ibc/src/context/common.rs
  crates/ibc/src/event.rs
  crates/ibc/src/lib.rs
  crates/ibc/src/vp/mod.rs
  crates/node/src/bench_utils.rs
  crates/node/src/shell/testing/node.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tests/src/vm_host_env/ibc.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merge

#3724 Fixes MASP tx expiration in the SDK
  .changelog/unreleased/bug-fixes/3724-fix-masp-expiration.md
  crates/apps_lib/src/cli.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/shell/testing/node.rs
  crates/sdk/src/args.rs
  crates/sdk/src/tx.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  crates/tests/src/integration/setup.rs
  crates/tx/src/data/mod.rs
Labels: merge

#3746 Update storage gas cost
  .changelog/unreleased/improvements/3746-fix-storage-gas-cost.md
  crates/gas/src/lib.rs
  crates/node/src/dry_run_tx.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/sdk/src/lib.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tests/src/integration/masp.rs
  genesis/hardware/parameters.toml
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: gas, breaking: protocol, merge

#3734 rpc: add query consensus validators
  .changelog/unreleased/improvements/3734-query-active-validators.md
  crates/sdk/src/rpc.rs
Labels: merge

#3530 [feature] Allow balance querying at specified block height
  .changelog/unreleased/improvements/3530-balance-query-at-height.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/rpc.rs
  crates/apps_lib/src/client/tx.rs
  crates/light_sdk/src/reading/asynchronous/account.rs
  crates/sdk/src/args.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
Labels: merge

#3781 Improve dry run rebase
  .changelog/unreleased/improvements/3758-improve-dry-run.md
  crates/gas/src/lib.rs
  crates/governance/src/vp/mod.rs
  crates/node/src/dry_run_tx.rs
  crates/node/src/protocol.rs
  crates/shielded_token/src/utils.rs
  crates/trans_token/src/storage.rs
  crates/vm/src/host_env.rs
Labels: merge

#3783 fix e2e logs
  .github/workflows/ci.yml
Labels: merge

#3730 Enable the signing logic to fall back to the hardware wallet if secret key is not found.
  .changelog/unreleased/bug-fixes/3730-enable-hw-fallback.md
  crates/sdk/src/signing.rs
Labels: merge

#3779 Check length of validator name in metadata
  .changelog/unreleased/improvements/3779-restrict-metadat-name-len.md
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/sdk/src/tx.rs
Labels: merge

#3788 Update parameters query
  .changelog/unreleased/improvements/3788-update-params-query.md
  crates/apps_lib/src/client/rpc.rs
Labels: merge

#3792 Refactor `Gas` type
  .changelog/unreleased/improvements/3792-gas-type-refactor.md
  Cargo.lock
  crates/benches/host_env.rs
  crates/ethereum_bridge/src/vp/bridge_pool_vp.rs
  crates/ethereum_bridge/src/vp/eth_bridge_vp.rs
  crates/ethereum_bridge/src/vp/nut_vp.rs
  crates/gas/src/lib.rs
  crates/governance/src/vp/mod.rs
  crates/ibc/src/vp/context.rs
  crates/ibc/src/vp/mod.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/node/src/storage/mod.rs
  crates/node/src/storage/rocksdb.rs
  crates/shielded_token/src/validation.rs
  crates/state/src/host_env.rs
  crates/state/src/in_memory.rs
  crates/state/src/lib.rs
  crates/state/src/wl_state.rs
  crates/state/src/write_log.rs
  crates/storage/Cargo.toml
  crates/storage/src/db.rs
  crates/storage/src/mockdb.rs
  crates/tests/src/native_vp/pos.rs
  crates/trans_token/src/vp.rs
  crates/vm/src/host_env.rs
  crates/vm/src/memory.rs
  crates/vm/src/wasm/memory.rs
  crates/vm/src/wasm/run.rs
  crates/vp/src/native_vp.rs
  crates/vp/src/vp_host_fns.rs
  crates/vp_env/Cargo.toml
  crates/vp_env/src/lib.rs
  crates/vp_prelude/Cargo.toml
  crates/vp_prelude/src/lib.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: gas, refactor / code quality, non-breaking-change, merge

#3795 sdk: propagate std feature to wallet
  .changelog/unreleased/improvements/3795-wallet-std-from-sdk.md
  crates/sdk/Cargo.toml
  wasm/Cargo.lock
Labels: merge

#3796 ledger wallet automation test
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/shielded_token/src/utils.rs
  crates/tests/Cargo.toml
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/hw_wallet_automation.rs
  crates/tests/src/lib.rs
  genesis/hardware/README.md
  wasm/Cargo.lock
Labels: testing, CI

#3800 test/e2e: offset non-validator node ports to avoid conflict with gaia
  crates/tests/src/e2e/setup.rs
Labels: testing, merge

#3801 automate an e2e test with Ledger hardware wallet emulator - 1st follow-up
  .github/workflows/ci.yml
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
  genesis/hardware/README.md
Labels: testing

#3805 Better conversions debugging
  .changelog/unreleased/improvements/3805-better-conversions-logging.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/rpc.rs
  crates/sdk/src/args.rs
Labels: merge

#3806 Validate genesis NAM MaspParams
  .changelog/unreleased/improvements/3806-validate-nam-masp-params.md
  crates/node/src/shell/init_chain.rs
Labels: merge

#3809 add memo builder fun to tx builder
  crates/sdk/src/args.rs
Labels: merge

#3811 try to strip namada version from moniker
  crates/node/src/tendermint_node.rs
Labels: merge

#3807 env agnostic VPs
  .changelog/unreleased/improvements/3807-env-agnostic-vps.md
  Cargo.lock
  crates/benches/native_vps.rs
  crates/ethereum_bridge/Cargo.toml
  crates/ethereum_bridge/src/vp/bridge_pool_vp.rs
  crates/ethereum_bridge/src/vp/eth_bridge_vp.rs
  crates/ethereum_bridge/src/vp/nut_vp.rs
  crates/governance/Cargo.toml
  crates/governance/src/vp/mod.rs
  crates/governance/src/vp/pgf.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/parameters/Cargo.toml
  crates/parameters/src/vp.rs
  crates/proof_of_stake/Cargo.toml
  crates/proof_of_stake/src/vp.rs
  crates/sdk/src/validation.rs
  crates/shielded_token/Cargo.toml
  crates/shielded_token/src/vp.rs
  crates/state/src/lib.rs
  crates/state/src/wl_state.rs
  crates/storage/src/conversion_state.rs
  crates/storage/src/lib.rs
  crates/tests/src/native_vp/eth_bridge_pool.rs
  crates/tests/src/native_vp/mod.rs
  crates/tests/src/native_vp/pos.rs
  crates/tests/src/vm_host_env/ibc.rs
  crates/trans_token/Cargo.toml
  crates/trans_token/src/vp.rs
  crates/vp/src/native_vp.rs
  crates/vp_env/src/lib.rs
  wasm/Cargo.lock
  wasm/tx_bond/src/lib.rs
  wasm/tx_change_validator_commission/src/lib.rs
  wasm/tx_redelegate/src/lib.rs
  wasm/tx_unbond/src/lib.rs
  wasm/tx_withdraw/src/lib.rs
  wasm_for_tests/Cargo.lock
Labels: merge

#3816 Estimate annual staking rewards rate
  .changelog/unreleased/improvements/3816-estimate-staking-reward-rate.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/client.rs
  crates/apps_lib/src/client/rpc.rs
  crates/proof_of_stake/src/rewards.rs
  crates/sdk/src/args.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: merge

#3804 Fix transfer triggered vps
  .changelog/unreleased/bug-fixes/3804-fix-transfer-dest-vp-trigger.md
  Cargo.lock
  clippy.toml
  crates/apps_lib/src/client/utils.rs
  crates/governance/src/finalize_block.rs
  crates/governance/src/utils.rs
  crates/governance/src/vp/pgf.rs
  crates/ibc/src/lib.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/snapshots.rs
  crates/node/src/shell/testing/node.rs
  crates/node/src/shims/abcipp_shim_types.rs
  crates/proof_of_stake/src/rewards.rs
  crates/proof_of_stake/src/tests/test_pos.rs
  crates/proof_of_stake/src/tests/test_slash_and_redel.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/queries/vp/token.rs
  crates/sdk/src/rpc.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/shielded_token/Cargo.toml
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
  crates/shielded_token/src/storage_key.rs
  crates/shielded_token/src/utils.rs
  crates/shielded_token/src/vp.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/integration/masp.rs
  crates/tests/src/vm_host_env/mod.rs
  crates/token/src/lib.rs
  crates/trans_token/src/vp.rs
  crates/tx_prelude/src/token.rs
  genesis/hardware/parameters.toml
  genesis/localnet/parameters.toml
  genesis/starter/parameters.toml
Labels: bug, ledger, breaking: protocol, merge

#3821 Unify MASP refs events
  .changelog/unreleased/bug-fixes/3821-fix-masp-events.md
  crates/core/src/ibc.rs
  crates/core/src/masp.rs
  crates/events/src/extend.rs
  crates/node/src/bench_utils.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/masp/utilities.rs
  crates/shielded_token/src/lib.rs
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
  crates/shielded_token/src/masp/shielded_sync/utils.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/tests/src/integration/masp.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/types.rs
Labels: bug, ledger, IBC, MASP, breaking:client, breaking-change, merge, breaking:SDK

#3826 Reduce event's masp attributes
  .changelog/unreleased/improvements/3826-reduce-masp-events.md
  crates/events/src/extend.rs
  crates/node/src/bench_utils.rs
  crates/node/src/shell/finalize_block.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/masp/utilities.rs
Labels: merge, breaking:SDK

#3830 Remove relayer and bridge pool from help msgs
  .changelog/unreleased/improvements/3830-rem-eth-help-msg.md
  crates/apps_lib/src/cli.rs
Labels: merge

#3736 refactor token transfer and add more tests
  .changelog/unreleased/improvements/3736-refactor-token-transfer.md
  Cargo.lock
  crates/core/src/address.rs
  crates/core/src/masp.rs
  crates/core/src/uint.rs
  crates/shielded_token/src/lib.rs
  crates/tests/src/vm_host_env/tx.rs
  crates/token/Cargo.toml
  crates/token/src/lib.rs
  crates/token/src/tx.rs
  crates/trans_token/Cargo.toml
  crates/trans_token/src/lib.rs
  crates/trans_token/src/storage.rs
  crates/trans_token/src/tx.rs
  crates/tx_env/src/lib.rs
  crates/tx_prelude/src/ibc.rs
  crates/tx_prelude/src/lib.rs
  crates/tx_prelude/src/token.rs
  wasm/Cargo.lock
  wasm/tx_ibc/src/lib.rs
  wasm/tx_transfer/src/lib.rs
  wasm_for_tests/Cargo.lock
Labels: merge

#3841 [fix]: Fix clap panic on parsing relayer commands
  crates/apps_lib/src/cli.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
Labels: merge

#3833 genesis: use env to configure pre-genesis chain-id
  .changelog/unreleased/improvements/3833-pre-genesis-chain-id.md
  .github/workflows/scripts/e2e.json
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/node/src/utils.rs
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/e2e/setup.rs
Labels: merge

#3846 Fix max proposal code size docstring
  crates/apps_lib/src/client/rpc.rs
  crates/apps_lib/src/config/genesis/templates.rs
  crates/governance/src/parameters.rs
Labels: merge

#3849 mergify: add backport strategy
  .mergify.yml
Labels: CI, merge

#3851 update hermes
  .github/workflows/scripts/hermes.txt
  README.md
  crates/tests/src/e2e/setup.rs
  scripts/get_hermes.sh
Labels: merge, backport-44

#3854 ci: run checks on release branches
  .github/workflows/ci.yml
  .github/workflows/docker.yml
Labels: merge
