Repository namada-net/namada, pull requests merged in 2025-04, with the labels that each got.

#4497 Remove duplicated events
  .changelog/unreleased/improvements/4497-no-duplicated-events.md
  .github/workflows/scripts/hermes.txt
  crates/apps_lib/src/client/rpc.rs
  crates/light_sdk/src/reading/asynchronous/tx.rs
  crates/node/src/bench_utils.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/sdk/src/events/log/dumb_queries.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/rpc.rs
  crates/sdk/src/tx.rs
  crates/tests/src/integration/ledger_tests.rs
  crates/tx/src/data/mod.rs
Labels: client, SDK, merge, breaking:SDK, breaking:api

#4545 Upgrade to tendermint 0.40.3
  .changelog/unreleased/bug-fixes/4545-upgrade-tendermint-rs.md
  Cargo.lock
  Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: backport-libs-0.48

#4550 ci: fix release ci
  .github/workflows/release.yml
Labels: backport-libs-0.48

#4563 apps v1.1.5-rc.2
  .changelog/libs-v0.48.1/bug-fixes/4545-upgrade-tendermint-rs.md
  .changelog/libs-v0.48.1/improvements/4472-generalize-amount-comparison.md
  .changelog/libs-v0.48.1/summary.md
  .changelog/libs-v0.48.2/miscellaneous/4554-maint-lib-ci.md
  .changelog/libs-v0.48.2/summary.md
  .changelog/libs-v0.48.3/miscellaneous/4561-ci-workflow-fixes.md
  .changelog/libs-v0.48.3/summary.md
  .changelog/v1.1.5/miscellaneous/4563-v1.1.5-release.md
  .changelog/v1.1.5/summary.md
  .github/workflows/ci.yml
  .github/workflows/release.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/apps/Cargo.toml
  crates/core/src/token.rs
  crates/ibc/src/context/middlewares/pfm_mod.rs
  crates/sdk/src/rpc.rs
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
  fuzz/Cargo.toml
  wasm/Cargo.lock
  wasm/Cargo.toml
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Cargo.toml
Labels: do-not-merge

#4576 fix core release by symlinking CONSENSUS_VERSION
  crates/core/CONSENSUS_VERSION
  crates/core/build.rs
Labels: merge, backport-libs-0.149

#4580 Change ABI to C-unwind in vm_env when running natively
  .changelog/unreleased/bug-fixes/4580-fix-vm-env-tests.md
  crates/tests/Cargo.toml
  crates/vm_env/Cargo.toml
  crates/vm_env/src/lib.rs
Labels: bug, testing, non-breaking-change, merge, backport-libs-0.149

#4577 test/e2e: hw-wallet-automation improvements
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/hw_wallet_automation.rs
  crates/tests/src/lib.rs
Labels: testing, merge, backport-libs-0.149

#4582 fix: use correct denom calc for osmosis swaps
  .changelog/unreleased/bug-fixes/4582-use-correct-ibc-denom-calc.md
  crates/ibc/src/trace.rs
  crates/sdk/src/args.rs
  crates/sdk/src/rpc.rs
Labels: bug, client, SDK, non-breaking-change, merge, breaking:SDK, backport-libs-0.149, breaking:api

#4587 ci: use nextest to run hardwallet e2e tests
  .github/workflows/ci.yml
Labels: CI, merge, backport-libs-0.149

#4599 CI: fix can-backport
  .github/workflows/pr.yml
Labels: CI, merge, backport-libs-0.149

#4566 Test masp events
  .changelog/unreleased/testing/4566-test-masp-events.md
  crates/node/src/shell/testing/node.rs
  crates/tests/src/integration/masp.rs
Labels: testing, MASP, merge, backport-libs-0.149

#4579 Unique public keys for signing
  .changelog/unreleased/SDK/4579-map-signing-tx-data.md
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/sdk/src/signing.rs
  crates/tests/src/integration/masp.rs
Labels: SDK, merge, breaking:SDK, breaking:api
