Repository namada-net/namada, pull requests merged in 2025-09, with the labels that each got.

#4800 clear the tx gas map after block commit
  .changelog/unreleased/improvements/4800-clear-tx-gas-map.md
  crates/state/src/wl_state.rs
Labels: merge, backport-libs-0.251, backport-201.0

#4810 Changelog: apps v201.0.4
  .changelog/v201.0.4/improvements/4799-safer-wasm-cache-key.md
  .changelog/v201.0.4/improvements/4800-clear-tx-gas-map.md
  .changelog/v201.0.4/summary.md
  CHANGELOG.md
Labels: merge

#4778 PoS: add a token transfer event to withdraw-tokens tx
  .changelog/unreleased/improvements/4778-withdraw-tx-event.md
  crates/proof_of_stake/src/lib.rs
  crates/proof_of_stake/src/tests/mod.rs
Labels: merge

#4821 Fix timeout refund on an unlimited channel
  .changelog/unreleased/bug-fixes/4822-fix-timeout-unlimited.md
  crates/ibc/src/vp/mod.rs
  crates/tests/src/e2e/ibc_tests.rs
Labels: merge, backport-libs-0.251, breaking:api

#4834 test/e2e: fix flakey e2e init-validator test
  crates/tests/src/e2e/ledger_tests.rs
Labels: testing, merge, backport-libs-0.251, backport-201.0

#4847 merge #4839, #4843, #4844
  .changelog/unreleased/bug-fixes/4843-fix-rm-tx-gas-map.md
  .github/workflows/ci.yml
  .github/workflows/release.yml
  crates/proof_of_stake/src/rewards.rs
  crates/proof_of_stake/src/tests/test_pos.rs
  crates/proof_of_stake/src/tests/test_slash_and_redel.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/state/src/wl_state.rs
Labels: merge, queued

#4817 Change MASP zk backend to bellperson
  .changelog/unreleased/improvements/4817-change-masp-zk-backend.md
  Cargo.lock
  Cargo.toml
  crates/benches/Cargo.toml
  crates/benches/native_vps.rs
  crates/node/src/shell/init_chain.rs
  crates/sdk/Cargo.toml
  crates/shielded_token/src/conversion.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/storage_key.rs
  crates/shielded_token/src/vp.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: MASP, merge, backport-libs-0.251, breaking:api, backport-201.0, queued
