Repository namada-net/namada, pull requests merged in 2025-03, with the labels that each got.

#4435 Make `native_token` of `NamadaImpl` public
  crates/sdk/src/lib.rs
Labels: merge, backport-libs-0.47

#4444 enable rocksdb bindgen-runtime by default
  .github/workflows/pr.yml
  Cargo.lock
  Cargo.toml
Labels: merge, backport-libs-0.47

#4441 fix node reset
  .changelog/unreleased/bug-fixes/4441-rust-1.85.md
  crates/apps/src/bin/namada-node/cli.rs
  crates/apps_lib/src/cli.rs
  crates/node/src/lib.rs
  crates/node/src/shell/mod.rs
  crates/node/src/tendermint_node.rs
  crates/tests/src/e2e/ledger_tests.rs
Labels: merge, breaking:api

#4445 Adjusted test vector generator to also generate tokens in whitelist.
  .changelog/unreleased/improvements/4445-generate-whitelisted-addresses.md
  .github/workflows/ci.yml
  crates/core/src/address.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/signing.rs
  crates/token/src/lib.rs
  crates/token/src/tx.rs
  examples/generate_txs.rs
Labels: testing, CI, merge, backport-libs-0.47

#4442 Murisi/client anchor patch optimized
  .changelog/unreleased/bug-fixes/4442-client-anchor-patch-optimized.md
  crates/node/src/bench_utils.rs
  crates/sdk/src/masp/utilities.rs
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
  crates/shielded_token/src/masp/shielded_sync/utils.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/shielded_token/src/masp/test_utils.rs
  crates/tx/src/types.rs
Labels: client, MASP, merge, breaking:api

#4467 add newly required 3rd party licenses
  about.toml
Labels: dependencies, merge, backport-libs-0.47, backport-1.1

#4471 backport last releases
  .changelog/libs-v0.48.0/bug-fixes/4442-client-anchor-patch-optimized.md
  .changelog/libs-v0.48.0/summary.md
  .changelog/v1.1.3/miscellaneous/4464-apps-v1.1.3.md
  .changelog/v1.1.3/summary.md
  .changelog/v1.1.4/summary.md
  .github/workflows/pr.yml
  .mergify.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.toml
  wasm/Cargo.lock
  wasm/Cargo.toml
  wasm_for_tests/Cargo.lock
  wasm_for_tests/Cargo.toml
Labels: merge

#4472 Prevent DenominatedAmount comparison from overflowing.
  .changelog/unreleased/improvements/4472-generalize-amount-comparison.md
  crates/core/src/token.rs
Labels: merge, backport-libs-0.48

#4452 Make sure that the conversion state is also written into memory.
  .changelog/unreleased/improvements/4452-load-conversion-migration.md
  crates/sdk/src/migrations.rs
Labels: MASP, breaking:consensus, merge

#4453 Informal Systems shielded swaps audit
  crates/ibc/src/context/middlewares/pfm_mod.rs
  crates/sdk/src/rpc.rs
Labels: merge, backport-libs-0.48

#4475 Fix masp events [rebase]
  .changelog/unreleased/bug-fixes/4449-fix-masp-events.md
  crates/events/src/extend.rs
  crates/node/src/bench_utils.rs
  crates/node/src/dry_run_tx.rs
  crates/node/src/protocol.rs
  crates/node/src/shell/finalize_block.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/masp/utilities.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
  crates/shielded_token/src/masp/shielded_sync/utils.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/shielded_token/src/masp/test_utils.rs
  crates/tx/src/data/mod.rs
  crates/tx/src/event.rs
  crates/tx/src/types.rs
Labels: ledger, merge, breaking:api

#4480 Improve shielded sync tx fetch errors
  crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
Labels: SDK, non-breaking-change, merge, backport-libs-0.48

#4463 Murisi/load storage conversions
  .changelog/unreleased/improvements/4423-configurable-masp-precision.md
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/core/src/chain.rs
  crates/core/src/masp.rs
  crates/migrations/Cargo.toml
  crates/migrations/src/foreign_types.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/testing/node.rs
  crates/sdk/src/migrations.rs
  crates/shielded_token/src/conversion.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  crates/shielded_token/src/storage_key.rs
  crates/shielded_token/src/vp.rs
  crates/state/src/lib.rs
  crates/storage/src/lib.rs
  crates/tests/Cargo.toml
  crates/tests/src/integration/masp.rs
  crates/token/src/lib.rs
  crates/tx_prelude/src/token.rs
  examples/Cargo.toml
  examples/make-db-migration.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: MASP, breaking:consensus, merge, breaking:api

#4489 Sorted tx results in events
  .changelog/unreleased/improvements/4489-sorted-tx-results.md
  crates/tx/src/data/mod.rs
Labels: ledger, merge, breaking:api

#4491 Added integration test for auto-compounding.
  .changelog/unreleased/testing/4491-test-auto-compounding.md
  crates/tests/src/integration/masp.rs
Labels: testing, MASP, merge, backport-libs-0.48

#4481 allow to dry run a proposal code
  .changelog/unreleased/features/4481-dry-run-proposal.md
  crates/apps/src/bin/namada-node/cli.rs
  crates/apps_lib/src/cli.rs
  crates/node/src/dry_run_tx.rs
  crates/node/src/storage/rocksdb.rs
  crates/node/src/utils.rs
  crates/sdk/src/rpc.rs
  crates/state/src/wl_state.rs
  crates/storage/src/db.rs
  crates/storage/src/mockdb.rs
Labels: merge, breaking:api

#4493 shielded_token/vp: allow any changes by a gov proposal
  .changelog/unreleased/improvements/4493-perm-gov-masp-vp.md
  crates/shielded_token/src/vp.rs
Labels: validity-predicate, breaking:consensus, merge, breaking:api

#4458 shielded_token: fix standalone test build
  crates/shielded_token/Cargo.toml
Labels: testing, merge

#4457 client: also query and print masp epoch
  .changelog/unreleased/improvements/4457-sdk-override-rewards-target.md
  crates/apps_lib/src/cli/client.rs
Labels: merge
