Repository namada-net/namada, pull requests merged in 2025-07, with the labels that each got.

#4702 Indexer client backoff sleep
  .changelog/unreleased/improvements/4702-indexer-client-backoff-sleep.md
  crates/apps_lib/src/client/masp.rs
  crates/sdk/src/masp.rs
  crates/sdk/src/masp/utilities.rs
Labels: enhancement, client, MASP, SDK, merge, breaking:api

#4743 CI: bump maint version libs-v0.251 and apps-201.0
  .github/workflows/pr.yml
  .mergify.yml
Labels: merge, backport-libs-0.251

#4553 Avoid flakiness in IBC e2e tests
  .changelog/unreleased/testing/4553-test-ci-ibc.md
  crates/tests/src/e2e/setup.rs
Labels: merge, backport-libs-0.251

#4759 fix write-log iters test
  crates/state/proptest-regressions/write_log.txt
  crates/state/src/write_log.rs
Labels: testing, merge, backport-libs-0.251

#4763 Murisi/reduce notes heuristic rebased
  .changelog/unreleased/improvements/4748-reduce-notes-heuristic.md
  Cargo.lock
  Cargo.toml
  crates/core/src/arith.rs
  crates/core/src/token.rs
  crates/core/src/uint.rs
  crates/shielded_token/src/masp.rs
  crates/shielded_token/src/masp/shielded_wallet.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merge, breaking:api, backport-201.0

#4775 update wasm_for_tests/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merge
