Repository namada-net/namada, pull requests merged in 2025-02, with the labels that each got.

#4286 Make sure the CI installs libudev-dev before building Namada.
  .changelog/unreleased/CI/4286-fix-ci-udev-dep.md
  .github/workflows/ci.yml
Labels: CI, merge, backport-libs-0.47

#4289 More multisig tests
  .changelog/unreleased/testing/4289-multisig-tests.md
  crates/tx/src/types.rs
Labels: testing, merge, backport-libs-0.47

#4196 [pos] Add epoch argument to vp::pos::rewards
  .changelog/unreleased/SDK/4196-rewards-at-past-epoch.md
  .vscode/launch.json
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/rpc.rs
  crates/sdk/src/args.rs
  crates/sdk/src/queries/shell.rs
  crates/sdk/src/queries/vp/pos.rs
  crates/sdk/src/rpc.rs
  crates/storage/src/mockdb.rs
Labels: PoS, client, merge, backport-libs-0.47

#4280 Hermes for v1.1.0
  .changelog/unreleased/miscellaneous/4280-update-hermes.md
  .github/workflows/ci.yml
  README.md
  scripts/get_hermes.sh
Labels: merge, backport-libs-0.47

#4247 Upgrade ibc-rs to v0.57
  .changelog/unreleased/improvements/4247-bump-ibc-rs.md
  Cargo.lock
  Cargo.toml
  clippy.toml
  crates/ibc/src/actions.rs
  crates/ibc/src/context/client.rs
  crates/ibc/src/context/common.rs
  crates/ibc/src/context/execution.rs
  crates/ibc/src/context/middlewares/pfm_mod.rs
  crates/ibc/src/context/middlewares/shielded_recv.rs
  crates/ibc/src/context/nft_transfer.rs
  crates/ibc/src/context/nft_transfer_mod.rs
  crates/ibc/src/context/token_transfer.rs
  crates/ibc/src/context/transfer_mod.rs
  crates/ibc/src/context/validation.rs
  crates/ibc/src/event.rs
  crates/ibc/src/lib.rs
  crates/ibc/src/nft.rs
  crates/ibc/src/vp/mod.rs
  crates/node/src/bench_utils.rs
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/storage/src/error.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/vm_host_env/ibc.rs
  crates/tests/src/vm_host_env/mod.rs
  crates/tx/build.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merge, backport-libs-0.47

#4299 update recommended CometBFT to 0.37.15
  .changelog/unreleased/improvements/4299-up-cometbft.md
  Dockerfile
  README.md
  scripts/get_cometbft.sh
Labels: merge

#4308 Murisi/improve native rewards precision
  .changelog/unreleased/improvements/4308-improve-native-rewards-precision.md
  crates/shielded_token/src/conversion.rs
Labels: MASP, merge

#4307 wallet: change the derivation path for modified ZIP32
  .changelog/unreleased/improvements/4307-modified-modified-zip32.md
  crates/apps_lib/src/cli/wallet.rs
  crates/wallet/Cargo.toml
  crates/wallet/src/derivation_path.rs
  crates/wallet/src/lib.rs
Labels: merge, backport-libs-0.47

#4312 updates to publish to crates.io
  Cargo.toml
  crates/account/Cargo.toml
  crates/apps/Cargo.toml
  crates/apps_lib/Cargo.toml
  crates/benches/Cargo.toml
  crates/controller/Cargo.toml
  crates/core/Cargo.toml
  crates/encoding_spec/Cargo.toml
  crates/ethereum_bridge/Cargo.toml
  crates/events/Cargo.toml
  crates/gas/Cargo.toml
  crates/governance/Cargo.toml
  crates/ibc/Cargo.toml
  crates/io/Cargo.toml
  crates/light_sdk/Cargo.toml
  crates/macros/Cargo.toml
  crates/merkle_tree/Cargo.toml
  crates/migrations/Cargo.toml
  crates/node/Cargo.toml
  crates/parameters/Cargo.toml
  crates/proof_of_stake/Cargo.toml
  crates/replay_protection/Cargo.toml
  crates/sdk/Cargo.toml
  crates/shielded_token/Cargo.toml
  crates/state/Cargo.toml
  crates/storage/Cargo.toml
  crates/systems/Cargo.toml
  crates/test_utils/Cargo.toml
  crates/tests/Cargo.toml
  crates/token/Cargo.toml
  crates/trans_token/Cargo.toml
  crates/tx/Cargo.toml
  crates/tx_env/Cargo.toml
  crates/tx_prelude/Cargo.toml
  crates/vm/Cargo.toml
  crates/vm_env/Cargo.toml
  crates/vote_ext/Cargo.toml
  crates/vp/Cargo.toml
  crates/vp_env/Cargo.toml
  crates/vp_prelude/Cargo.toml
  crates/wallet/Cargo.toml
  examples/Cargo.toml
  fuzz/Cargo.toml
  release.toml
Labels: merge, backport-libs-0.47

#4332 Print the transaction's chain ID in expert mode.
  .changelog/unreleased/improvements/4282-test-vectors-with-chain-ids.md
  crates/sdk/src/signing.rs
Labels: merge, backport-libs-0.47

#4283 PoS claim rewards - add token transfer event
  .changelog/unreleased/improvements/4283-pos-claim-rewards-events.md
  crates/proof_of_stake/src/lib.rs
Labels: PoS, non-breaking-change, merge, backport-libs-0.47

#4344 backport patch changelogs
  .changelog/libs-v0.47.1/CI/4286-fix-ci-udev-dep.md
  .changelog/libs-v0.47.1/SDK/4196-rewards-at-past-epoch.md
  .changelog/libs-v0.47.1/bug-fixes/4287-consolidate-dust.md
  .changelog/libs-v0.47.1/improvements/4218-normal-mode-display-tx-fees.md
  .changelog/libs-v0.47.1/improvements/4247-bump-ibc-rs.md
  .changelog/libs-v0.47.1/improvements/4283-pos-claim-rewards-events.md
  .changelog/libs-v0.47.1/improvements/4288-reverse-conversion-at-source.md
  .changelog/libs-v0.47.1/improvements/4290-remove-reverse-conversions.md
  .changelog/libs-v0.47.1/improvements/4291-optimize-shielded-balance-queries.md
  .changelog/libs-v0.47.1/improvements/4299-up-cometbft.md
  .changelog/libs-v0.47.1/improvements/4307-modified-modified-zip32.md
  .changelog/libs-v0.47.1/improvements/4308-improve-native-rewards-precision.md
  .changelog/libs-v0.47.1/improvements/4311-refactor-update-allowed-conversions.md
  .changelog/libs-v0.47.1/miscellaneous/4280-update-hermes.md
  .changelog/libs-v0.47.1/summary.md
  .changelog/libs-v0.47.1/testing/4289-multisig-tests.md
  .changelog/v1.1.1/miscellaneous/4343-apps-v1.1.1.md
  .changelog/v1.1.1/summary.md
  CHANGELOG.md
Labels: merge

#4347 sdk/tx-result: print tx events if any
  .changelog/unreleased/improvements/4347-tx-result-events.md
  crates/sdk/src/tx.rs
Labels: client, SDK, merge, backport-libs-0.47

#4351 tx: build tonic artifacts into OUT_DIR
  crates/tx/build.rs
  crates/tx/src/proto/generated.rs
Labels: merge, backport-libs-0.47

#4353 apps_lib: output artifacts from build script into OUT_DIR
  crates/apps_lib/build.rs
  crates/apps_lib/src/cli.rs
Labels: merge, backport-libs-0.47

#4350 keep a separate commit for release changelogs
  scripts/release_bins.sh
  scripts/release_libs.sh
Labels: merge, backport-libs-0.47

#4355 move version detection build script from apps_lib into apps
  Cargo.lock
  crates/apps/Cargo.toml
  crates/apps/build.rs
  crates/apps/src/bin/namada-client/main.rs
  crates/apps/src/bin/namada-node/cli.rs
  crates/apps/src/bin/namada-relayer/_main.rs
  crates/apps/src/bin/namada-wallet/main.rs
  crates/apps/src/bin/namada/cli.rs
  crates/apps/src/lib.rs
  crates/apps_lib/Cargo.toml
  crates/apps_lib/src/cli.rs
  crates/node/src/lib.rs
  crates/node/src/tendermint_node.rs
Labels: merge, backport-libs-0.47

#4364 port patch releases changelogs
  .changelog/libs-v0.47.2/improvements/4347-tx-result-events.md
  .changelog/libs-v0.47.2/summary.md
  .changelog/v1.1.2/miscellaneous/4363-minor-release.md
  .changelog/v1.1.2/summary.md
  CHANGELOG.md
Labels: merge

#4370 test/e2e: fix the test with HW wallet automation
  crates/tests/src/hw_wallet_automation.rs
Labels: testing, merge, backport-libs-0.47

#4367 Use the upstream Hermes
  .changelog/unreleased/miscellaneous/4367-update-hermes.md
  README.md
  scripts/get_hermes.sh
Labels: merge, backport-libs-0.47

#4374 Update genesis files for hardware wallet using modified ZIP 32 derivations
  .changelog/unreleased/testing/4374-update-hardware-genesis.md
  genesis/hardware/src/pre-genesis/wallet.toml
Labels: testing, merge, backport-libs-0.47

#4341 Print the transaction's chain ID in expert mode. (re-opened from #4332 after revert)
  .changelog/unreleased/improvements/4282-test-vectors-with-chain-ids.md
  .github/workflows/ci.yml
  crates/sdk/src/signing.rs
Labels: merge, backport-libs-0.47

#4230 Avoid duplicated signatures when building transactions
  .changelog/unreleased/improvements/4230-remove-duplicated-sigs.md
  crates/sdk/src/signing.rs
  crates/sdk/src/tx.rs
  crates/tx/src/section.rs
  crates/tx/src/types.rs
Labels: SDK, merge, breaking:SDK, backport-libs-0.47

#4371 add VERSIONING.md
  .changelog/unreleased/improvements/4371-versioning.md
  VERSIONING.md
Labels: documentation, merge, backport-libs-0.47

#4284 deps update
  .changelog/unreleased/miscellaneous/4284-deps-update.md
  Cargo.lock
  Cargo.toml
  Makefile
  clippy.toml
  crates/account/src/lib.rs
  crates/apps/src/bin/namada-node/cli.rs
  crates/apps_lib/Cargo.toml
  crates/apps_lib/src/client/utils.rs
  crates/apps_lib/src/config/genesis/transactions.rs
  crates/apps_lib/src/config/genesis/utils.rs
  crates/apps_lib/src/config/global.rs
  crates/apps_lib/src/config/mod.rs
  crates/apps_lib/src/tendermint_node.rs
  crates/apps_lib/src/wallet/mod.rs
  crates/apps_lib/src/wallet/pre_genesis.rs
  crates/apps_lib/src/wallet/store.rs
  crates/benches/Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/address.rs
  crates/core/src/ethereum_structs.rs
  crates/core/src/key/common.rs
  crates/core/src/lib.rs
  crates/core/src/masp.rs
  crates/core/src/string_encoding.rs
  crates/core/src/token.rs
  crates/core/src/uint.rs
  crates/encoding_spec/Cargo.toml
  crates/ethereum_bridge/Cargo.toml
  crates/governance/src/lib.rs
  crates/ibc/src/lib.rs
  crates/light_sdk/Cargo.toml
  crates/macros/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/ethereum_oracle/events.rs
  crates/node/src/ethereum_oracle/test_tools/mod.rs
  crates/node/src/lib.rs
  crates/node/src/shell/mod.rs
  crates/node/src/storage/rocksdb.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/args.rs
  crates/storage/src/lib.rs
  crates/test_utils/Cargo.toml
  crates/tests/Cargo.toml
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/token/src/lib.rs
  crates/tx/src/lib.rs
  crates/vm/Cargo.toml
  crates/vm/src/lib.rs
  crates/vm/src/wasm/compilation_cache/common.rs
  crates/wallet/src/lib.rs
  crates/wallet/src/pre_genesis.rs
  crates/wallet/src/store.rs
  fuzz/Cargo.toml
  fuzz/fuzz_targets/txs_wasm_run.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: dependencies, non-breaking-change, merge, backport-libs-0.47

#4379 sa fixes tests
  .github/workflows/ci.yml
  crates/benches/Cargo.toml
  crates/benches/mempool_validate.rs
  crates/node/src/shell/mod.rs
  crates/node/src/shell/process_proposal.rs
  crates/tx/src/section.rs
  wasm/Cargo.lock
  wasm/tx_become_validator/Cargo.toml
  wasm/tx_become_validator/src/lib.rs
Labels: testing, merge, backport-libs-0.47

#4368 apps: allow to publish namada_apps to crates.io
  crates/apps/release.toml
Labels: merge

#4403 fix crates build with some non-default features
  .changelog/unreleased/bug-fixes/4403-fix-crates-build.md
  Cargo.lock
  crates/governance/Cargo.toml
  crates/proof_of_stake/Cargo.toml
  crates/wallet/Cargo.toml
Labels: merge, backport-libs-0.47

#3890 hw masp auto test
  .changelog/unreleased/testing/3890-hw-masp-auto-test.md
  .github/workflows/ci.yml
  crates/tests/src/e2e/ledger_tests.rs
  crates/tests/src/hw_wallet_automation.rs
Labels: testing, merge, backport-libs-0.47

#4401 ci: check if a PR can be backported
  .github/workflows/pr.yml
Labels: CI, merge, backport-libs-0.47

#4407 Changelog: Release libs v0.47.3
  .changelog/libs-v0.47.3/bug-fixes/4403-fix-crates-build.md
  .changelog/libs-v0.47.3/improvements/4230-remove-duplicated-sigs.md
  .changelog/libs-v0.47.3/improvements/4282-test-vectors-with-chain-ids.md
  .changelog/libs-v0.47.3/improvements/4358-check-ledger-app-version.md
  .changelog/libs-v0.47.3/improvements/4371-versioning.md
  .changelog/libs-v0.47.3/miscellaneous/4284-deps-update.md
  .changelog/libs-v0.47.3/miscellaneous/4367-update-hermes.md
  .changelog/libs-v0.47.3/summary.md
  .changelog/libs-v0.47.3/testing/4374-update-hardware-genesis.md
  CHANGELOG.md
Labels: merge

#4398 define and check minimum supported Rust version in CI
  .changelog/unreleased/miscellanous/4398-add-msrv.md
  .github/workflows/pr.yml
  Cargo.toml
  crates/account/Cargo.toml
  crates/apps_lib/Cargo.toml
  crates/controller/Cargo.toml
  crates/core/Cargo.toml
  crates/ethereum_bridge/Cargo.toml
  crates/events/Cargo.toml
  crates/gas/Cargo.toml
  crates/governance/Cargo.toml
  crates/ibc/Cargo.toml
  crates/io/Cargo.toml
  crates/light_sdk/Cargo.toml
  crates/macros/Cargo.toml
  crates/merkle_tree/Cargo.toml
  crates/migrations/Cargo.toml
  crates/node/Cargo.toml
  crates/parameters/Cargo.toml
  crates/proof_of_stake/Cargo.toml
  crates/replay_protection/Cargo.toml
  crates/sdk/Cargo.toml
  crates/shielded_token/Cargo.toml
  crates/state/Cargo.toml
  crates/storage/Cargo.toml
  crates/systems/Cargo.toml
  crates/test_utils/Cargo.toml
  crates/tests/Cargo.toml
  crates/token/Cargo.toml
  crates/trans_token/Cargo.toml
  crates/tx/Cargo.toml
  crates/tx_env/Cargo.toml
  crates/tx_prelude/Cargo.toml
  crates/vm/Cargo.toml
  crates/vm_env/Cargo.toml
  crates/vote_ext/Cargo.toml
  crates/vp/Cargo.toml
  crates/vp_env/Cargo.toml
  crates/vp_prelude/Cargo.toml
  crates/wallet/Cargo.toml
Labels: merge, backport-libs-0.47

#4418 Fixed the `speculative_context` integration test for the hardware wallet.
  .changelog/unreleased/testing/4418-fix-hw-speculative_context.md
  crates/tests/src/integration/masp.rs
Labels: testing, MASP, merge, backport-libs-0.47

#4417 Murisi/sequential payment addresses
  .changelog/unreleased/improvements/4417-sequential-payment-addresses.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/cli/wallet.rs
  crates/core/src/masp.rs
  crates/sdk/src/args.rs
  crates/wallet/src/lib.rs
  crates/wallet/src/store.rs
Labels: wallet, MASP, merge, breaking:api

#4420 ci/pr: lock msrv deps versions
  .github/workflows/pr.yml
Labels: CI, merge, backport-libs-0.47

#4378 deps: update rocksdb
  .changelog/unreleased/miscellaneous/4378-up-rocksdb.md
  .github/workflows/pr.yml
  Cargo.lock
  Cargo.toml
  crates/node/src/shims/abcipp_shim.rs
  crates/node/src/storage/rocksdb.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: merge, backport-libs-0.47

#4369 Increase the accuracy of rewards by minting based on the real reward.
  .changelog/unreleased/improvements/4369-increase-masp-minting-accuracy.md
  crates/shielded_token/src/conversion.rs
  crates/tests/src/integration/masp.rs
Labels: MASP, merge, backport-libs-0.47
