Repository namada-net/namada, pull requests merged in 2025-01, with the labels that each got.

#4224 fix apps version fallback
  .changelog/unreleased/bug-fixes/4224-fix-apps-version-fallback.md
  Cargo.lock
  Cargo.toml
  crates/apps_lib/Cargo.toml
  crates/apps_lib/build.rs
  crates/systems/Cargo.toml
Labels: merge

#4223 client/rpc: small improvements
  crates/apps_lib/src/client/rpc.rs
Labels: merge

#4228 Murisi/fix hw tests by unbatching
  .changelog/unreleased/improvements/4228-fix-hw-tests-by-unbatching.md
  crates/apps_lib/src/client/tx.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/integration/ledger_tests.rs
Labels: merge

#4236 fix make-package.sh to work on windows
  scripts/make-package.sh
Labels: merge

#4225 add missing trait to `TxUnshieldingTransfer`
  crates/sdk/src/args.rs
Labels: merge

#4234 Offline signatures from SDK
  .changelog/unreleased/SDK/4234-offline-sigs-in-sdk.md
  crates/apps_lib/src/cli.rs
  crates/apps_lib/src/client/utils.rs
  crates/sdk/src/args.rs
  crates/sdk/src/signing.rs
Labels: SDK, merge, breaking:SDK

#4241 client: print last stake ration and improve msg on zero inflation
  .changelog/unreleased/improvements/4241-client-staking-rewards-query.md
  crates/apps_lib/src/client/rpc.rs
Labels: cli, client, merge

#4226 deps: switch to released sparse-merkle-tree fork
  Cargo.lock
  Cargo.toml
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: merge

#4243 scripts/make-package.sh - fix typo
  scripts/make-package.sh
Labels: merge

#4244 build with no jemalloc on windows
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  Makefile
Labels: merge

#4251 Support IBC signing on hardware wallets not supporting MASP
  .changelog/unreleased/bug-fixes/4251-ibc-for-maspless-hw.md
  crates/apps_lib/src/client/tx.rs
Labels: MASP, merge

#4134 Support invalid receivers in the IBC PFM flow
  .changelog/unreleased/features/4082-ibc-pfm.md
  .changelog/unreleased/features/4134-ibc-pfm-with-invalid-addrs.md
  .github/workflows/scripts/e2e.json
  Cargo.lock
  Cargo.toml
  crates/benches/native_vps.rs
  crates/core/src/address.rs
  crates/ibc/Cargo.toml
  crates/ibc/src/context/common.rs
  crates/ibc/src/context/middlewares.rs
  crates/ibc/src/context/middlewares/pfm_mod.rs
  crates/ibc/src/context/mod.rs
  crates/ibc/src/context/nft_transfer_mod.rs
  crates/ibc/src/context/token_transfer.rs
  crates/ibc/src/context/transfer_mod.rs
  crates/ibc/src/context/validation.rs
  crates/ibc/src/lib.rs
  crates/ibc/src/storage.rs
  crates/ibc/src/vp/mod.rs
  crates/tests/Cargo.toml
  crates/tests/src/e2e/helpers.rs
  crates/tests/src/e2e/ibc_tests.rs
  crates/tests/src/e2e/setup.rs
  crates/tx_prelude/src/ibc.rs
  wasm/Cargo.lock
  wasm_for_tests/Cargo.lock
Labels: ledger, IBC, breaking: protocol, breaking: tx, merge

#4245 avoid running cometbft as a validator when tendermint_node is set to non-validator
  .changelog/unreleased/bug-fixes/4245-fix-tm-mode.md
  crates/apps/src/bin/namada-node/cli.rs
  crates/apps_lib/src/config/mod.rs
  crates/apps_lib/src/tendermint_node.rs
  crates/node/src/lib.rs
Labels: merge

#4264 PoS: fix and improve chained redelegation error msg
  .changelog/unreleased/bug-fixes/4264-fix-redeleg-err.md
  crates/sdk/src/error.rs
  crates/sdk/src/tx.rs
Labels: merge

#4271 Improve error message on failed fee payment
  .changelog/unreleased/improvements/4271-masp-fee-error-msg.md
  crates/node/src/protocol.rs
  crates/node/src/shell/process_proposal.rs
Labels: non-breaking-change, merge

#4277 ci/mergify: update for maint-1.1 and maint-libs-0.47
  .mergify.yml
Labels: CI, merge, backport-libs-0.47

#4218 Display transaction fees in normal mode
  .changelog/unreleased/improvements/4218-normal-mode-display-tx-fees.md
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/sdk/src/lib.rs
  crates/sdk/src/signing.rs
Labels: merge
