Repository namada-net/namada, pull requests merged in 2025-06, with the labels that each got.

#4659 Soft limit the number of wasm transfer targets
  .changelog/unreleased/improvements/4659-soft-limit-tx-transfer-targets.md
  crates/token/src/lib.rs
  crates/tx_prelude/src/token.rs
  wasm/tx_ibc/src/lib.rs
  wasm/tx_transfer/src/lib.rs
Labels: wasm, non-breaking-change, merge, backport-libs-0.149

#4666 optimize claim rewards tx
  .changelog/unreleased/improvements/4666-optimize-claim-rewards.md
  crates/proof_of_stake/src/lib.rs
  crates/proof_of_stake/src/rewards.rs
  crates/proof_of_stake/src/slashing.rs
  crates/proof_of_stake/src/tests/test_helper_fns.rs
Labels: merge, backport-libs-0.149

#4667 pgf/governance disallow non-native transfers
  .changelog/unreleased/bug-fixes/4667-governance-non-native-transfer-fix.md
  crates/governance/src/vp/mod.rs
  crates/governance/src/vp/pgf.rs
  crates/sdk/src/validation.rs
Labels: breaking:consensus, merge, breaking:api

#4682 CI: bump maint version libs-v0.150 and apps-101.1
  .changelog/v101.1.0/miscellaneous/4680-v101.1.0-release.md
  .github/workflows/pr.yml
  .mergify.yml
  CHANGELOG.md
Labels: merge, backport-libs-0.150

#4684 fix: remove redundant reads from governance vp
  .changelog/unreleased/bug-fixes/4684-fix-gov-gas-cost.md
  crates/governance/src/vp/mod.rs
Labels: merge, backport-libs-0.150

#4573 Added an example program to derive constraints on shielded reward parameters
  .changelog/unreleased/testing/4573-shielded-rewards-example.md
  Cargo.lock
  crates/core/src/token.rs
  examples/Cargo.toml
  examples/shielded_rewards.rs
Labels: MASP, merge, backport-libs-0.149

#4695 Add custom multisig signature
  .changelog/unreleased/bug-fixes/4695-add-multisig-signature-custom-tx.md
  crates/tx/src/types.rs
Labels: merge, backport-libs-0.150

#4697 app v101.1.2 and libs-v0.150.2 release logs
  .changelog/libs-v0.150.2/bug-fixes/4695-add-multisig-signature-custom-tx.md
  .changelog/libs-v0.150.2/summary.md
  .changelog/v101.1.2/summary.md
  CHANGELOG.md
Labels: merge

#4698 deps: lock proptest version to avoid rand/rand_core update
  Cargo.toml
Labels: dependencies, merge, breaking:api, backport-libs-0.150

#4700 Murisi/compress hw displays rebased
  .changelog/unreleased/improvements/4436-compress-hw-displays.md
  .github/workflows/ci.yml
  crates/sdk/src/signing.rs
Labels: merge, backport-libs-0.150
